import {DEFAULT_SETTINGS,PLANTS,plantSupport,parseRows,reparsePendingRows,makeDemo,autocolor,parseClock,formatClock,formatDuration,validateSettings,isSpecial,colorTimeGuide,withSessionBackgrounds,inspectManualSchedule} from './domain.mjs';
import {saveJob,getJobs,removeJob,validateProject,remoteMap,durationInput,csvCell,matchSheetName} from './storage.mjs';
import {windowReport,backgroundReport} from './validation.mjs';
import {DEFAULT_MEASUREMENT_SETTINGS,normalizeMeasurementSettings,generateMeasurements,setSegmentA,setRowB} from './measurements.mjs';
import {activeResult,resultIsCurrent,currentJobRows,reconcileMeasurements,storeMeasurements} from './job-rows.mjs';
import {normalizeManualSettings,createManualMorningPlan,createManualAfternoon,confirmManualMorning,reopenManualMorning,manualPlanReady,setManualExcluded,candidateRows,mapManualTimes,setManualInterval,setManualMappedTimes} from './manual-time.mjs';
import {manualDraftRows,manualHalfRows} from './manual-preview.mjs';
import {manualTimeView,manualSettingsFor,manualWindowsView} from './manual-ui.mjs';
import {captureManualState,restoreManualState,manualHistoryView} from './manual-history.mjs';
import {PLANT_NAMES,REVERSED_SOURCE_PLANTS,normalizePlantRule} from './plant-parser.mjs';
import {plantRulesView} from './plant-settings.mjs';
import {normalizeImportParams,importParamsView} from './import-settings.mjs';
import {readPlantProfile,writePlantProfile} from './plant-profiles.mjs';
import {createTxtOutput} from './txt-output-ui.mjs';
import './version.js';
import {createUpdater,fetchReleaseVersion} from './update.mjs';

const icons={
 folder:'M3 7V5a1 1 0 0 1 1-1h5l2 3h9a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7Z',
 file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8M8 17h5',
 upload:'M12 16V3m-5 5 5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5',
 download:'M12 3v13m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4',
 paint:'m15 3 6 6-9 9-6-6ZM6 12l-3 3 6 6 3-3M4 3l10 10',
 clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 sliders:'M4 4v5m0 6v5m8-16v9m0 6v1m8-16v1m0 6v9M1 9h6v6H1ZM9 13h6v6H9ZM17 5h6v6h-6Z',
 chart:'M4 3v17h17M8 15v-4m5 4V6m5 9v-7',
 chevron:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6',close:'m6 6 12 12M18 6 6 18',
 plus:'M12 5v14M5 12h14',undo:'M8 3 3 8l5 5M3 8h10a7 7 0 0 1 0 14',
 link:'m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l6-6a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-6 6a4 4 0 0 1-6 0',
 route:'M5 5h11a3 3 0 0 1 0 6H8a3 3 0 0 0 0 6h11M16 14l3 3-3 3',
 shield:'m12 2 9 4v7c0 5-9 9-9 9s-9-4-9-9V6ZM8 12l3 3 5-6',
 info:'M12 11v6M12 7h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 rocket:'M12 15 9 12c0-4 6-9 12-9 0 6-5 12-9 12ZM9 9H5l-3 6h7m6 0v4l-6 3v-7M16 8h.01M6 18l-3 3',
 grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',
 sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',
 moon:'M20 15a9 9 0 0 1-11-11 9 9 0 1 0 11 11Z',
 more:'M5 12h.01M12 12h.01M19 12h.01',refresh:'M20 7a9 9 0 1 0 1 8M20 2v6h-6',
 trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',
 arrow:'M4 12h16m-6-6 6 6-6 6',search:'M11 3a8 8 0 1 0 0 16 8 8 0 0 0 0-16ZM17 17l5 5',
 edit:'m16 3 5 5-12 12-6 1 1-6ZM13 6l5 5',stop:'M5 5h14v14H5Z'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.file}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,act,style='',ico='',attrs='')=>`<button class="button ${style}" data-act="${act}" ${attrs}>${ico?icon(ico):''}${label}</button>`;
const tabs=[['data','資料','folder'],['marks','標記','paint'],['settings','時間設定','clock'],['plant-rules','廠別規則','sliders'],['import-params','匯入參數','file'],['measurements','背景/值','edit'],['results','結果','chart']];
const root=document.getElementById('app'),modal=document.getElementById('modal');
let jobs=[],job,tab='data',selection=new Set(),search='',regionFilter='',markFilter='all',shown=60,expanded=new Set(),undoStack=[],busy=false,solver=null,solverTimer,saveTimer,saveChain=Promise.resolve(),saveState='尚未儲存',offlineReady=false,importer=null,importData=null,toastTimer;
let viewMode='table',showContext=false,paletteOpen=false,updater=null,deletingJob=false,updateIdle=true,rowObserver=null,showShortCode=false;
const manualUi={jobId:null,period:'am',selection:new Set(),rangeMode:false,anchor:null,shown:400,history:[],feedback:''};
let manualProposal=null,configPlant=null,configJobId=null,plantProposal=null;
function selectedPlant(){if(configJobId!==job.id){configJobId=job.id;configPlant=null;}return configPlant??(PLANT_NAMES.includes(job.plant)?job.plant:'');}
function plantProfile(plant){return readPlantProfile(localStorage,plant,job);}
function savePlantProfile(plant,patch){writePlantProfile(localStorage,plant,patch,job);}
function plantRulesPage(){const plant=selectedPlant();return plantRulesView(plant,plantProfile(plant).rules,{esc,button})+'<p class="inline-hint">儲存規則供下次匯入使用。套用至目前卡夾會先預覽，再重新判定；標記與原碼保留。</p>';}
function importParamsPage(){const plant=selectedPlant();return importParamsView(plant,plantProfile(plant).importParams,{esc,button});}
function previewPlantRules(){
 const plant=selectedPlant();if(!job.rows.length)throw new Error('目前卡夾沒有元件，儲存後可直接匯入新卡夾。');
 const form=document.getElementById('plant-rule-form'),rules=normalizePlantRule(plant,Object.fromEntries(new FormData(form))),rows=reparsePendingRows(job.rows,plant,rules,{all:true});
 plantProposal={jobId:job.id,revision:job.revision,plant,rules,rows};
 showModal('套用廠別規則',`<p>${esc(job.plant||'未選廠別')} → <b>${esc(plant)}</b> · ${rows.length}筆</p><p>重新判定區域、設備、樓層、型式與小組，包含人工修改的解析；D／E原碼與標記保留。套用後時間結果須重新生成，可從資料頁復原。</p><p class="notice">預覽後有 ${rows.filter(row=>row.issues.length).length} 筆需要確認。</p><div class="sample-preview">${rows.slice(0,3).map(row=>`<p><b>${esc(row.equipment||'待確認')}</b> · ${esc(row.floor??'—')}F · ${esc(row.form)}<br>${esc(row.issues.join('；'))}</p>`).join('')}</div><div class="foot-actions">${button('確認套用','plant-rule-confirm','primary')}${button('取消','close-modal','light')}</div>`);
}
function importParamsFromForm(){return normalizeImportParams({first:document.getElementById('import-start').value,count:document.getElementById('import-amount').value,dColumn:document.getElementById('import-d-column').value,eColumn:document.getElementById('import-e-column').value,reverse:document.getElementById('import-reverse').checked},document.getElementById('import-plant').value);}
function loadImportParams(){const params=plantProfile(document.getElementById('import-plant').value).importParams;for(const [key,id] of [['first','start'],['count','amount'],['dColumn','d-column'],['eColumn','e-column']])document.getElementById('import-'+id).value=params[key];document.getElementById('import-reverse').checked=params.reverse;}

const txtOutput=createTxtOutput({getJob:()=>job,ensureIdle,persist,showModal,esc,button,toast,navigate:target=>{closeModal();changeTab(target);}});
function resetManualSelection(){manualUi.selection.clear();manualUi.anchor=null;}
function manualState(){if(manualUi.jobId!==job.id){Object.assign(manualUi,{jobId:job.id,period:'am',rangeMode:false,shown:400,history:[],feedback:''});resetManualSelection();manualProposal=null;}return {...manualUi,busy,canUndo:manualUi.history.length>0};}
function manualCheckpoint(label='編輯時間'){manualState();manualUi.history.push(captureManualState(job,label));if(manualUi.history.length>20)manualUi.history.shift();}
function manualDraftChanged(){manualProposal=null;job.manualRevision=Math.max(Date.now(),(job.manualRevision||0)+1);job.updated=new Date().toISOString();saveSoon();}
function timingModeControls(){const manual=job.timeMode==='manual';return `<div class="card time-mode"><h3>時間方式</h3><div class="segmented"><button class="segment ${manual?'':'active'}" data-act="time-mode" data-value="auto" aria-pressed="${!manual}">自動</button><button class="segment ${manual?'active':''}" data-act="time-mode" data-value="manual" aria-pressed="${manual}">手動</button></div>${manual?button('開啟手動時間','manual-open','primary','edit'):''}</div>`;}
function manualPage(){return manualTimeView(job,manualState(),{esc,button});}
function revealManualCandidate(index){
 requestAnimationFrame(()=>{
  const container=document.getElementById('manual-list'),row=container?.querySelector('tr[data-index="'+index+'"]');
  if(!container||!row)return;
  const head=container.querySelector('thead').getBoundingClientRect().height,box=container.getBoundingClientRect(),rect=row.getBoundingClientRect();
  if(rect.top<box.top+head)container.scrollTop+=rect.top-box.top-head;
  else if(rect.bottom>box.bottom)container.scrollTop+=rect.bottom-box.bottom;
  const workbench=container.parentElement,nav=document.querySelector('.mobile-nav'),bottom=nav?.getBoundingClientRect().top||window.innerHeight;
  if(workbench.getBoundingClientRect().bottom>bottom)workbench.scrollIntoView({block:'center'});
 });
}
function selectManualCandidate(period,index){
 manualState();if(!job.manualPlan)return;
 manualUi.feedback='';
 if(!candidateRows(job.manualPlan,period).some(row=>row.index===index))return;
 if(manualUi.period!==period){manualUi.period=period;resetManualSelection();}
 if(manualUi.rangeMode){if(manualUi.anchor===null){manualUi.anchor=index;manualUi.selection.add(index);}else{const lo=Math.min(index,manualUi.anchor),hi=Math.max(index,manualUi.anchor);for(let i=lo;i<=hi;i++)manualUi.selection.add(i);manualUi.anchor=null;}}
 else manualUi.selection.has(index)?manualUi.selection.delete(index):manualUi.selection.add(index);
 renderKeepScroll();revealManualCandidate(index);
}
function startManualAdjustment(){
 ensureIdle();if(!job.manualPlan)throw new Error('請先產生候選。');
 if(!manualPlanReady(job.manualPlan))throw new Error('先確認上午末筆，再生成下午，才能調整全天。');
 const rows=withSessionBackgrounds(manualDraftRows(job,job.manualPlan));
 if(rows.length!==job.rows.length)throw new Error('候選不足，請先補足上午與下午筆數。');
 const token=crypto.randomUUID(),jobId=job.id,revision=job.revision,draftRevision=job.manualRevision;
 manualProposal=null;resetManualSelection();busy=true;manualUi.feedback='正在核算 <80、逐筆規則與收尾時間…';renderKeepScroll();
 try{solver=new Worker('./manual-adjust-worker.mjs',{type:'module'});}catch(error){busy=false;renderKeepScroll();throw error;}
 const finish=()=>{clearTimeout(solverTimer);solver?.terminate();solver=null;busy=false;};
 solver.onmessage=({data})=>{
  if(data.token!==token)return;
  finish();manualUi.feedback='';renderKeepScroll();
  if(job.id!==jobId||job.revision!==revision||job.manualRevision!==draftRevision){toast('資料已變動，修正方案未套用。');return;}
  if(data.type!=='result'||!data.result?.ok){const errors=data.result?.errors||[data.message||'本次未找到修正方案。'];showModal('這次未能調整',`<p>原候選與結果保留。</p><ul>${errors.map(error=>`<li>${esc(error)}</li>`).join('')}</ul><p class="inline-hint">可調整上午筆數、時段或規則後再試。</p>`);return;}
  const result=data.result;
  manualProposal={jobId,revision,draftRevision,result};
  const g=seconds=>seconds==null?'—':Math.floor(seconds/60)+'分';
  const before=inspectManualSchedule(rows,job.settings,remoteMap(job),{manualStart:true});
  const summaries=['am','pm'].map((half,i)=>`<tr><th>${i?'下午':'上午'}</th><td>${g(result.beforeWindows[half+'Minimum'])} → <b>${g(result.windows[half+'Minimum'])}</b></td><td>${formatClock(before.summary[half+'LastTime'])} → <b>${formatClock(result.review.summary[half+'LastTime'])}</b></td></tr>`).join('');
  showModal('自動調整預覽',`<p>調整 ${result.changes.length} 筆；筆數、順序、底色與午休切點保留。</p><div class="table-scroll"><table class="manual-proposal-table"><thead><tr><th></th><th>&lt;80最低</th><th>末筆</th></tr></thead><tbody>${summaries}</tbody></table></div><p class="notice">${job.settings.mode==='outdoor'?'逐筆與收尾檢查通過；廠外不套80門檻。':'80窗、逐筆與收尾檢查通過。'}</p><details><summary>查看秒數變更</summary><div class="manual-proposal-changes">${result.changes.map(change=>`<p>元件 ${change.index+1}：${formatDuration(change.beforeInterval)} → ${formatDuration(change.interval)}</p>`).join('')}</div></details><div class="foot-actions">${button('採用到候選','manual-adjust-accept','primary','check')}${button('保留原候選','close-modal','light')}</div><p class="inline-hint">採用後可復原；確認後再按「套用至結果」。</p>`);
 };
 solver.onerror=()=>{finish();manualUi.feedback='調整未完成，原候選保留。';renderKeepScroll();};
 solverTimer=setTimeout(()=>{finish();manualUi.feedback='本次調整超過20秒，原候選保留。';renderKeepScroll();},20000);
 solver.postMessage({token,rows,settings:job.settings,remotes:remoteMap(job)});
}
function acceptManualAdjustment(){
 ensureIdle();const proposal=manualProposal;
 if(!proposal||proposal.jobId!==job.id||proposal.revision!==job.revision||proposal.draftRevision!==job.manualRevision)throw new Error('方案已過期，請重新預覽。');
 const next=setManualMappedTimes(job.manualPlan,proposal.result.rows,job.settings);
 const mapped=withSessionBackgrounds(manualDraftRows(job,next));
 if(mapped.length!==job.rows.length||mapped.some((row,i)=>row.id!==proposal.result.rows[i].id||row.time!==proposal.result.rows[i].time)||!inspectManualSchedule(mapped,job.settings,remoteMap(job),{manualStart:true}).rulesOk)throw new Error('候選回填驗算未通過，原候選保留。');
 manualCheckpoint('採用自動調整');job.manualPlan=next;manualDraftChanged();manualProposal=null;resetManualSelection();manualUi.feedback='修正已放入候選，可復原；尚未套用至結果。';closeModal();renderKeepScroll();
}
function applyManualTimes(){
 ensureIdle();if(job.timeMode!=='manual')throw new Error('請先切換手動時間。');
 if(!job.manualPlan)throw new Error('請先產生候選。');
 const mapped=mapManualTimes(job.rows,job.manualPlan),rows=withSessionBackgrounds(mapped);
 for(let i=0;i<rows.length;i++){const row=rows[i],key=row.period==='上午'?'am':'pm',start=parseClock(job.settings[key+'Start']),end=parseClock(job.settings[key+'End']);if(row.time<start||row.time>end)throw new Error(`第 ${i+1} 筆超出時間設定的${row.period}時段，請調整候選或時間設定。`);if(i===0||row.period!==rows[i-1].period)row.interval=row.time-start;}
 const review=inspectManualSchedule(rows,job.settings,remoteMap(job),{manualStart:true});
 snapshot();job.manualResult={ok:true,source:'manual',rows,...review,revision:job.revision,planRevision:job.manualRevision||0,warnings:['手動時間保留原值；背景、樓層、特殊與遠距只驗證，不自動補秒。'],errors:[]};
 reconcileMeasurements(job);job.updated=new Date().toISOString();saveSoon();changeTab('results');toast(review.rulesOk?'手動時間已套用，規則檢查通過。':'手動時間已套用；有規則提醒，請在結果頁核對。');
}
function blankJob(name='未命名卡夾'){return {schema:1,id:crypto.randomUUID(),name,sourceName:'',sheet:'',plant:'',rows:[],settings:{...DEFAULT_SETTINGS},measurementSettings:{...DEFAULT_MEASUREMENT_SETTINGS},remotes:[],overrides:{},result:null,revision:0,updated:new Date().toISOString(),demo:false};}
function toast(message){const el=document.getElementById('toast');el.classList.toggle('manual-toast',tab==='manual');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500);}
function ensureIdle(){if(updater?.state==='applying')throw new Error('正在儲存並更新，請稍候。');if(busy)throw new Error('正在試排。請先按「取消」，再修改資料。');}
function snapshot(){undoStack.push(structuredClone(job));if(undoStack.length>12)undoStack.shift();}
function changed(){job.revision++;job.updated=new Date().toISOString();saveSoon();}
function saveSoon(){saveState='正在儲存';clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(),300);}
async function persist(){
 if(deletingJob)return false;
 if(!job.rows.length&&!job.revision&&job.name==='未命名卡夾'&&!jobs.some(j=>j.id===job.id)){saveState='尚未匯入';try{localStorage.removeItem('log-active');}catch{}document.querySelectorAll('[data-save]').forEach(el=>el.textContent=saveState);return true;}
 const copy=structuredClone(job);saveChain=saveChain.catch(()=>{}).then(()=>saveJob(copy));let saved=false;
 try{await saveChain;const index=jobs.findIndex(x=>x.id===copy.id);if(index<0)jobs.push(copy);else jobs[index]=copy;try{localStorage.setItem('log-active',copy.id);}catch{}saveState='已存於此裝置';saved=true;}catch{saveState='未能儲存';toast('此裝置無法保存卡夾。請先匯出卡夾，避免關閉後遺失。');}
 document.querySelectorAll('[data-save]').forEach(el=>el.textContent=saveState);return saved;
}
function showModal(title,html,kind='editor'){modal.dataset.kind=kind;modal.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-act="close-modal" aria-label="關閉視窗">${icon('close')}</button></div><div class="modal-body">${html}</div>`;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();delete modal.dataset.kind;importer?.terminate();importer=null;importData=null;}
modal.addEventListener('cancel',()=>{delete modal.dataset.kind;importer?.terminate();importer=null;importData=null;});
function changeTab(next){tab=next;shown=60;render();window.scrollTo({top:0,behavior:'instant'});}
function rememberUi(){try{localStorage.setItem('log-row-view',viewMode);localStorage.setItem('log-filter-context',showContext?'1':'0');}catch{}}
function renderKeepScroll(){const x=window.scrollX,y=window.scrollY,positions=['row-list','result-list','measurement-list','manual-list'].map(id=>({id,left:document.getElementById(id)?.scrollLeft||0,top:document.getElementById(id)?.scrollTop||0}));render();requestAnimationFrame(()=>{window.scrollTo({left:x,top:y,behavior:'instant'});for(const position of positions){const table=document.getElementById(position.id);if(table){table.scrollLeft=position.left;table.scrollTop=position.top;}}});}
function resultCurrent(){return resultIsCurrent(job);}
function counts(){const rows=currentJobRows(job);return {background:rows.filter(r=>r.background!=='none').length,floors:rows.filter(r=>r.floorMark).length,marked:rows.filter(r=>r.background!=='none'||r.floorMark||r.extraMark).length,issues:rows.filter(r=>r.issues?.length).length};}
function remoteCount(){return Object.keys(remoteMap(job)).length;}
function updateButton(){return `<button class="icon-button update-control" data-act="check-update" aria-label="檢查並更新" title="檢查並更新">${icon('refresh')}<span class="update-label">更新</span><span class="update-dot" hidden></span></button>`;}
function updaterInfo(){const info=updater?.info||{},current=info.currentVersion||globalThis.LOG_RELEASE?.version||'—',latest=info.latestVersion||'尚未取得';return {current,latest,released:globalThis.LOG_RELEASE?.released||'—',state:info.state||updater?.state||'idle',message:info.message||'可檢查是否有新版。',expected:info.expectedVersion||''};}
function infoHtml(){const info=updaterInfo();return `<div class="info-dialog" data-info-dialog><dl class="version-grid"><dt>目前版本</dt><dd data-info-current>${esc(info.current)}</dd><dt>線上版本</dt><dd data-info-latest>${esc(info.latest)}</dd><dt>發布日期</dt><dd>${esc(info.released)}</dd><dt>狀態</dt><dd data-info-state>${esc(info.message)}</dd></dl><p class="inline-hint">「更新」會先保存卡夾，再套用已下載的新版。若顯示需要再載入，按下方按鈕完成。</p><div class="foot-actions" data-info-actions>${info.state==='recovery'?button('儲存並重新載入','recover-update','primary','refresh'):button('檢查並更新','check-update','primary','refresh')}</div></div>`;}
function refreshInfoDialog(){if(!modal.open||modal.dataset.kind!=='info')return;const info=updaterInfo();modal.querySelector('[data-info-current]')?.replaceChildren(info.current);modal.querySelector('[data-info-latest]')?.replaceChildren(info.latest);modal.querySelector('[data-info-state]')?.replaceChildren(info.message);const actions=modal.querySelector('[data-info-actions]');if(actions)actions.innerHTML=info.state==='recovery'?button('儲存並重新載入','recover-update','primary','refresh'):button('檢查並更新','check-update','primary','refresh');}
function refreshUpdateState(){const state=updater?.state||'idle';refreshInfoDialog();document.querySelectorAll('[data-act="check-update"],[data-act="recover-update"]').forEach(el=>{const ready=state==='available',label={checking:'檢查中',downloading:'下載中',applying:'更新中',recovery:'再載入'}[state]||'更新';el.disabled=state==='applying';el.setAttribute('aria-label',state==='recovery'?'儲存並重新載入':ready?'立即更新':state==='applying'?'更新中':'檢查並更新');el.title=state==='recovery'?'完成新版載入':ready?'有新版，儲存後更新':label==='更新'?'檢查並更新':label;el.querySelector('.update-label')?.replaceChildren(label);const dot=el.querySelector('.update-dot');if(dot)dot.hidden=!(ready||state==='recovery');});offlineReady=updater?.hasOfflineShell||offlineReady;}
function render(){
 rowObserver?.disconnect();rowObserver=null;
 if(reconcileMeasurements(job))saveSoon();
 const title={data:'資料',marks:'標記',settings:'時間設定',results:'結果',measurements:'背景/值','plant-rules':'廠別規則','import-params':'匯入參數',manual:'手動時間',guide:'操作說明'}[tab];
 const subtitle={data:'匯入或檢視元件資料。',marks:'篩選、選取，再套用標記或遠距。',settings:'設定時段、規則與遠距組合。',results:'確認全部資料與驗證結果。',measurements:'A 同底色段共用；B 逐筆填寫。','plant-rules':'各廠別的判定規則。','import-params':'各廠別的匯入欄位與參數。',manual:'選時間、批次刪除，累加後套用。',guide:`顏色與時間 · 目前${job.settings.difficulty==='hard'?'難檢':'一般'} · 分:秒`}[tab];
 root.innerHTML=`<header class="topbar"><div class="brand"><img class="brand-logo" src="./icon-192.png" alt="LOG"><div class="brand-title">LOG</div></div><div class="top-actions"><span class="status-pill"><i class="status-dot"></i><span data-save>${esc(saveState)}</span></span>${updateButton()}<button class="icon-button" data-act="help" aria-label="資訊">${icon('info')}</button>${button('卡夾','shelf','light','folder')}</div></header>
 <main class="workspace"><div class="page-heading"><div>${job.rows.length?`<div class="eyebrow">${esc(job.plant)}</div>`:''}<h1>${title}</h1><p>${subtitle}</p></div>${tab==='guide'?button('返回','guide-back','light','undo'):job.rows.length?button('匯出卡夾','backup','light desktop-only','download'):''}</div>
 <nav class="tabs" aria-label="工作流程">${tabs.map(([id,label,ico],i)=>`<button class="tab ${(tab==='manual'?'settings':tab)===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${(tab==='manual'?'settings':tab)===id?'page':'false'}"><span class="step">0${i+1}</span>${icon(ico)}${label}</button>`).join('')}</nav>
 <div class="layout ${tab==='results'?'result-layout':['guide','measurements','manual','plant-rules','import-params'].includes(tab)?'guide-layout':''}"><section class="main-col">${tab==='data'?dataView():tab==='marks'?marksView():tab==='settings'?settingsView():tab==='guide'?guideView():tab==='manual'?manualPage():tab==='measurements'?measurementsView():tab==='plant-rules'?plantRulesPage():tab==='import-params'?importParamsPage():`<div class="txt-entry-actions">${button('產出 TXT','txt-open','primary','download')}${button('上傳暫存','txt-open-upload','light','upload')}${button('鑰匙取件','txt-retrieve','light','link')}</div>${resultsView()}`}</section>${['guide','measurements','results','manual','plant-rules','import-params'].includes(tab)?'':`<aside class="aside">${asideView()}</aside>`}</div>
 </main>
 <nav class="mobile-nav" aria-label="工作流程">${tabs.map(([id,label,ico])=>`<button class="nav-item ${(tab==='manual'?'settings':tab)===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${(tab==='manual'?'settings':tab)===id?'page':'false'}">${icon(ico)}<span>${label}</span></button>`).join('')}</nav>
 <input type="file" id="source-file" class="file-input" accept=".xlsx,.xlsm"><input type="file" id="project-file" class="file-input" accept=".json,application/json">`;
 document.getElementById('source-file').onchange=event=>openWorkbook(event.target.files[0]);
 document.getElementById('project-file').onchange=event=>loadProject(event.target.files[0]);
 refreshUpdateState();
 setupCardObserver();
}
function empty(title='匯入資料',detail='選擇 XLSX，或載入合成示範資料。'){return `<div class="card empty-state">${icon('folder')}<h2>${title}</h2><p>${detail}</p>${button('選擇 XLSX','import','primary','upload')} ${button('載入示範','demo','light')}</div>`;}
function sourceCard(){const c=counts();return `<div class="card source-compact"><div class="source-banner"><div class="source-info"><h2>${esc(job.name)}</h2><p>${esc(job.plant)} · ${job.rows.length}筆 · ${c.marked}筆標記 · ${c.issues}筆待確認</p></div><button class="icon-button" data-act="rename" aria-label="重新命名卡夾">${icon('edit')}</button></div></div>`;}
function dataView(){if(!job.rows.length)return empty();return sourceCard()+`${counts().issues?`<div class="notice" style="margin-top:16px">有 ${counts().issues} 筆解析需要確認。原碼與標記保留。<div class="foot-actions">${button('重新判定待確認','reparse-pending','light small','refresh')}</div></div>`:''}`+filters()+rowList(false)+`<div class="sticky-actions">${undoStack.length?button('復原','undo','light','undo'):''}${button('前往標記','to-marks','primary','paint')}${button('匯入另一份','import','light','upload')}</div>`;}
function matchesBase(r){const text=search.toLowerCase();return (!text||[r.d,r.e,r.region,r.equipment,r.group,r.form].some(v=>String(v??'').toLowerCase().includes(text)))&&(!regionFilter||r.region===regionFilter);}
function matchesMark(r){return markFilter==='all'||(markFilter==='yellow'&&r.background==='yellow')||(markFilter==='red'&&r.background==='red')||(markFilter==='blue'&&r.background==='blue')||(markFilter==='floor'&&r.floorMark)||(markFilter==='extra'&&r.extraMark)||(markFilter==='issues'&&r.issues?.length);}
function filtered(){return currentJobRows(job).filter(r=>matchesBase(r)&&matchesMark(r));}
function displayRows(){const rows=currentJobRows(job),matches=filtered(),matchIds=new Set(matches.map(r=>r.id));if(!showContext||markFilter==='all')return matches.map(row=>({row,context:false}));const indexes=new Set();rows.forEach((r,i)=>{if(matchIds.has(r.id)){indexes.add(i);if(i)indexes.add(i-1);if(i+1<rows.length)indexes.add(i+1);}});return [...indexes].sort((a,b)=>a-b).map(i=>({row:rows[i],context:!matchIds.has(rows[i].id)}));}
function filters(){const regions=[...new Set(job.rows.map(r=>r.region).filter(Boolean))];return `<div class="filter-bar"><input id="search" type="text" placeholder="搜尋編碼、設備或小組" aria-label="搜尋資料" value="${esc(search)}"><select id="region-filter" aria-label="區域篩選"><option value="">全部區域</option>${regions.map(r=>`<option ${regionFilter===r?'selected':''} value="${esc(r)}">${esc(r)}</option>`).join('')}</select><select id="mark-filter" aria-label="標記篩選">${[['all','全部'],['yellow','黃底'],['red','紅底'],['blue','藍底'],['floor','樓層'],['extra','加時'],['issues','待確認']].map(([value,label])=>`<option value="${value}" ${markFilter===value?'selected':''}>${label}</option>`).join('')}</select><label class="context-toggle"><input id="context-filter" type="checkbox" ${showContext?'checked':''} ${markFilter==='all'?'disabled':''}>保留前後1筆</label><div class="view-toggle" role="group" aria-label="資料檢視"><button class="${viewMode==='table'?'active':''}" data-act="view-mode" data-value="table" aria-pressed="${viewMode==='table'}">表格</button><button class="${viewMode==='cards'?'active':''}" data-act="view-mode" data-value="cards" aria-pressed="${viewMode==='cards'}">卡片</button></div></div>`;}
function rowList(selectable,resultRows=null,windowById={}){const matches=filtered(),entries=displayRows(),lookup=new Map((resultRows||[]).map(r=>[r.id,r])),backgrounds=backgroundReport(currentJobRows(job)).byId;const resolved=entries.map(({row,context})=>({row:lookup.get(row.id)||row,context})),more=resolved.length>shown;const cardMore=more?(typeof IntersectionObserver==='undefined'?button(`再顯示 ${Math.min(60,resolved.length-shown)} 筆`,'more','light more-rows'):'<div class="load-sentinel" data-more-sentinel aria-hidden="true"></div>'):'';const body=viewMode==='table'?tableRows(resolved,selectable,windowById,backgrounds):`<div class="row-list" id="row-list">${resolved.slice(0,shown).map(x=>rowHtml(x.row,selectable,x.context,windowById[x.row.id],backgrounds[x.row.id])).join('')||'<div class="empty-state">沒有符合篩選的元件。</div>'}</div>${cardMore}`;return `<div class="selection-line"><span id="filter-count">${matches.length} 筆${resolved.length!==matches.length?` · 含 ${resolved.length-matches.length} 筆情境`:''}${selectable?' · 已選 '+selection.size+' 筆':''}</span>${selectable?`<div class="selection-actions"><button data-act="select-filter">選取篩選結果</button><button data-act="select-group" ${selection.size?'':'disabled'}>同小組</button></div>`:''}</div>${body}`;}
function setupCardObserver(){const manualSentinel=document.querySelector('[data-manual-more-sentinel]');if(manualSentinel&&typeof IntersectionObserver!=='undefined'){rowObserver=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;rowObserver?.disconnect();rowObserver=null;manualUi.shown+=200;renderKeepScroll();},{root:document.getElementById('manual-list'),rootMargin:'240px 0px'});rowObserver.observe(manualSentinel);return;}const sentinel=document.querySelector('[data-more-sentinel]');if(!sentinel||typeof IntersectionObserver==='undefined')return;rowObserver=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;rowObserver?.disconnect();rowObserver=null;shown+=60;renderKeepScroll();},{rootMargin:'240px 0px'});rowObserver.observe(sentinel);}
function rowClasses(r,context=false){return `bg-${esc(r.background)} ${r.floorMark?'floor-mark':''} ${r.extraMark?'extra-mark':''} ${selection.has(r.id)?'selected':''} ${context?'context-row':''}`;}
function equipmentChange(r){const index=job.rows.findIndex(row=>row.id===r.id);if(index<=0)return '';const previous=job.rows[index-1],changed=String(previous.equipment??'')!==String(r.equipment??'');if(!changed)return '';return `<span class="tag equipment-change">換設備</span>${r.background==='none'?'<span class="tag missing-background">未標背景</span>':''}`;}
function intervalCell(value){if(!Number.isInteger(value))return '<span class="interval-empty">—</span>';return `<span class="interval-pill ${value>=91?'interval-alert':''}">${formatDuration(value)}</span>`;}
function formCell(row,empty='—'){const text=esc(row.form||empty);return isSpecial(row)?`<span class="special-form" title="${job.timeMode==='manual'?'特殊型式，間隔需包含 1:00 加時':'特殊型式，自動加 1:00'}">${text}<small>+1:00</small></span>`:text;}
function detailHtml(r,windowInfo=null){const remote=remoteMap(job)[r.id];return `<div class="row-detail"><dl><dt>元件編號</dt><dd>${esc(r.d)}</dd><dt>設備原碼</dt><dd>${esc(r.e)}</dd><dt>小組 / 型式</dt><dd>${esc(r.group||'待確認')} / ${formCell(r,'無')}</dd>${windowInfo&&Number.isInteger(windowInfo.seconds)?`<dt>80窗時間</dt><dd>第 ${windowInfo.startRow}→${windowInfo.endRow} 筆 · ${formatDuration(windowInfo.seconds)}</dd>`:''}${r.parts?`<dt>間隔組成</dt><dd>${esc(Array.isArray(r.parts)?r.parts.join('；'):JSON.stringify(r.parts))}</dd>`:''}${remote?`<dt>遠距加時</dt><dd>${esc(remote.name)} · ${formatDuration(remote.min)}～${formatDuration(remote.max)}</dd>`:''}</dl>${r.issues?.length?`<p class="notice" style="margin-top:10px">${r.issues.map(esc).join('；')}</p>`:''}<div class="flex wrap">${button('修正解析','edit-row','light small','edit',`data-id="${esc(r.id)}"`)}${button('單筆遠距','edit-distance','light small','route',`data-id="${esc(r.id)}"`)}</div></div>`;}
function backgroundCell(info){return `<div class="background-counter ${info?.overLimit?'background-over':''}" title="${info?.total?`第 ${info.startRow}～${info.endRow} 筆；最多29筆`:'尚未設定背景段首'}"><small>本段筆數</small><strong>${info?.total?`${info.position}<span> / ${info.total}</span>`:'—'}</strong></div>`;}
function windowCell(info){if(!info||!Number.isInteger(info.minutes))return '<span class="window-empty" title="往後不足81點、跨午休或資料無效">—</span>';return `<span class="window-value window-${esc(info.status)}" title="第 ${info.startRow}→${info.endRow} 筆 · ${formatDuration(info.seconds)}">${info.minutes}</span>`;}
function rowHtml(r,selectable,context=false,windowInfo=null,backgroundInfo=null){const remote=remoteMap(job)[r.id],index=job.rows.findIndex(x=>x.id===r.id)+1,hasTime=Number.isInteger(r.time);return `<article class="data-row ${rowClasses(r,context)}"><div class="row-main" ${context?'':selectable?`data-act="select" data-id="${esc(r.id)}"`:`data-act="expand" data-id="${esc(r.id)}" role="button" tabindex="0" aria-label="展開第 ${index} 筆"`}>
 <span class="row-select">${selectable&&!context?`<input type="checkbox" aria-label="選取第 ${index} 筆 ${esc(r.e)}" ${selection.has(r.id)?'checked':''}>`:''}</span><span class="row-no">${String(index).padStart(2,'0')}</span><div class="row-content"><div class="row-code"><strong class="raw-e">${esc(r.e)}</strong><span class="raw-d">${esc(r.d)}</span></div><div class="row-meta"><strong class="equipment-name">${esc(r.equipment||'待確認')}</strong>${equipmentChange(r)}<span>${r.floor!=null?esc(r.floor)+'F':'待確認'}</span><span>${formCell(r,'無型式')}</span><span>${esc(r.group||'小組待確認')}</span>${context?'<span class="context-label">情境</span>':''}${r.background!=='none'?`<span class="tag ${r.background}">${{yellow:'黃底',red:'紅底',blue:'藍底'}[r.background]}</span>`:''}${r.floorMark?'<span class="tag red">樓層</span>':''}${r.extraMark?'<span class="tag warn">加時</span>':''}${remote?`<span class="tag remote-chip">遠距 +${formatDuration(remote.min)}起</span>`:''}${r.issues?.length?'<span class="tag warn">待確認</span>':''}</div></div><button class="row-detail-button" data-act="expand" data-id="${esc(r.id)}" aria-label="${expanded.has(r.id)?'收合':'查看'}第 ${index} 筆詳情" aria-expanded="${expanded.has(r.id)}">${icon('more')}</button><div class="row-metrics ${hasTime?'has-time':'marks-only'}">${hasTime?`<div class="row-time"><strong>${formatClock(r.time)}</strong><small>間隔 ${intervalCell(r.interval)}</small></div>`:''}${backgroundCell(backgroundInfo)}${hasTime?`<div class="window-metric"><small>80窗（分）</small>${windowCell(windowInfo)}</div>`:''}</div></div>${expanded.has(r.id)?detailHtml(r,windowInfo):''}</article>`;}
function tableRows(entries,selectable,windowById={},backgrounds={}){if(!entries.length)return '<div class="empty-state">沒有符合篩選的元件。</div>';return `<div class="table-scroll" id="row-list" tabindex="0" aria-label="資料表，可水平捲動"><table class="data-table"><thead><tr><th class="select-cell">${selectable?'選':''}</th><th>#</th><th class="e-head">設備原碼</th><th>元件編號</th><th>設備名稱</th><th>樓層</th><th>型式</th><th>小組</th><th>本段筆數</th><th>時間</th><th>間隔</th><th>80窗（分）</th><th>詳情</th></tr></thead><tbody>${entries.map(({row:r,context})=>{const index=job.rows.findIndex(x=>x.id===r.id)+1,info=windowById[r.id];return `<tr class="${rowClasses(r,context)}" ${context?'':selectable?`data-act="select" data-id="${esc(r.id)}"`:`data-act="expand" data-id="${esc(r.id)}" tabindex="0" aria-label="展開第 ${index} 筆"`}><td class="select-cell">${selectable&&!context?`<input type="checkbox" aria-label="選取第 ${index} 筆 ${esc(r.e)}" ${selection.has(r.id)?'checked':''}>`:context?'<span class="context-label">情境</span>':''}</td><td>${index}</td><td class="raw-e">${esc(r.e)}</td><td class="raw-d">${esc(r.d)}</td><td class="equipment-name">${esc(r.equipment||'待確認')}<span class="equipment-tags">${equipmentChange(r)}</span></td><td>${r.floor!=null?esc(r.floor)+'F':'待確認'}</td><td>${formCell(r)}</td><td>${esc(r.group||'待確認')}</td><td>${backgroundCell(backgrounds[r.id])}</td><td class="time-cell">${Number.isInteger(r.time)?formatClock(r.time):'—'}</td><td class="time-cell">${intervalCell(r.interval)}</td><td class="time-cell">${windowCell(info)}</td><td><button class="row-detail-button" data-act="expand" data-id="${esc(r.id)}" aria-label="${expanded.has(r.id)?'收合':'查看'}第 ${index} 筆詳情" aria-expanded="${expanded.has(r.id)}">${icon('more')}</button></td></tr>${expanded.has(r.id)?`<tr class="table-detail"><td colspan="13">${detailHtml(r,info)}</td></tr>`:''}`;}).join('')}</tbody></table></div>`;}
function selectionDock(){if(!selection.size)return '';return `<div class="selection-dock"><div class="dock-main"><strong>已選 ${selection.size} 筆</strong><button data-act="palette-toggle" aria-expanded="${paletteOpen}">上色</button><button data-act="remote-add">遠距</button><button data-act="deselect">清除選取</button></div>${paletteOpen?`<div class="dock-palette" aria-label="標記顏色">${[['yellow','黃底',''],['red','紅底',''],['floor','樓層紅字','F'],['extra','加時黃字','+'],['clear','清除標記','×']].map(([type,label,letter])=>`<button class="paint paint-${type}" data-act="paint" data-color="${type}" ${busy?'disabled':''}><span class="swatch">${letter}</span>${label}</button>`).join('')}</div>`:''}</div>`;}
function marksView(){if(!job.rows.length)return empty();return `${sourceCard()}<div class="mark-tools">${button('自動標色','autocolor','light','paint')}${button('復原','undo','light','undo',undoStack.length?'':'disabled')}${button('時間設定','to-settings','primary','clock')}</div>${filters()}${rowList(true)}${selectionDock()}`;}
function field(label,key,type='clock',value=job.settings[key]){return `<div class="field"><label for="setting-${key}">${label}</label><input id="setting-${key}" type="text" inputmode="${type==='clock'?'numeric':'decimal'}" data-setting="${key}" data-kind="${type}" value="${esc(type==='duration'?formatDuration(value):value)}" autocomplete="off" spellcheck="false"></div>`;}
function segment(key,options){return `<div class="segmented">${options.map(([v,label])=>`<button class="segment ${job.settings[key]===v?'active':''}" data-act="setting-choice" data-key="${key}" data-value="${v}" aria-pressed="${job.settings[key]===v}">${label}</button>`).join('')}</div>`;}
function settingsView(){return `<div class="stack settings-main">${timingModeControls()}${button('操作說明 · 顏色時間','color-guide','light','paint')}<div class="card"><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('sun')}</span><div><h3>上午時段</h3><p>可直接輸入 0820，或 08:20</p></div></div><div class="time-range">${field('開始','amStart')}<span class="time-arrow">→</span>${field('截止','amEnd')}</div></div><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('moon')}</span><div><h3>下午時段</h3><p>下午從 1F 重新出發</p></div></div><div class="time-range">${field('開始','pmStart')}<span class="time-arrow">→</span>${field('截止','pmEnd')}</div></div></div>
 <div class="card settings-section"><div class="section-title"><span class="section-icon">${icon('sliders')}</span><h3>檢測規則</h3></div><div class="setting-row"><div class="left"><h3>檢測難度</h3><p>黃底 ${job.settings.difficulty==='hard'?'2:31～3:10':'1:31～2:10'}，樓層與特殊另加</p></div>${segment('difficulty',[['normal','一般'],['hard','難']])}</div><div class="setting-row"><div class="left"><h3>80 顆驗證</h3><p>廠外仍保留其他時間規則</p></div>${segment('mode',[['auto','Auto'],['outdoor','廠外']])}</div>
 <details class="details-panel"><summary>首筆進場、收尾與跨區</summary><p class="inline-hint">分秒可填 1.30 或 130（1分30秒）。</p><h3 class="settings-title">首筆進場等待 · 分:秒</h3><div class="fields">${field('下限','entryMin','duration')}${field('上限','entryMax','duration')}</div><h3 class="settings-title">上午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','amEarlyMin','duration')}${field('最多提前','amEarlyMax','duration')}</div><h3 class="settings-title">下午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','pmEarlyMin','duration')}${field('最多提前','pmEarlyMax','duration')}</div><h3 class="settings-title">跨區額外加時 · 分:秒</h3><div class="fields">${field('下限','crossMin','duration')}${field('上限','crossMax','duration')}</div></details>
 <details class="details-panel"><summary>普通間隔範圍</summary><div class="info-note">這版把「基礎＋差值」顯示為實際秒數範圍。設定只影響本卡夾，不會更改 Excel。</div><div class="fields" style="margin-top:14px">${field('一般下限（秒）','normalMin','seconds')}${field('一般上限（秒）','normalMax','seconds')}${field('難檢下限（秒）','hardMin','seconds')}${field('難檢上限（秒）','hardMax','seconds')}</div></details></div>
 <div class="card settings-section"><div class="card-head"><div class="card-label">${icon('route')}<h3>遠距組合</h3></div>${button('新增','remote-add','light small','plus')}</div><p class="inline-hint" style="margin-bottom:16px">先在「標記」選元件，再加入組合。單筆可另外設定；遠距加在原有間隔上。</p>${remoteCards()}</div>
 ${button(busy?'正在試排…':job.timeMode==='manual'?'開啟手動時間':'依設定試排全天','generate','primary w100','rocket',busy?'disabled':'')}${busy?button('取消本次試排','cancel','light w100','stop'):''}</div>`;}
function remoteCards(){return job.remotes.length?job.remotes.map(g=>`<div class="remote-card"><div class="flex between"><div><h3>${esc(g.name)}</h3><p class="meta">${g.rowIds.length} 筆 · 額外 +${formatDuration(g.min)}～${formatDuration(g.max)}</p></div><button class="icon-button" data-act="remote-edit" data-id="${esc(g.id)}" aria-label="編輯 ${esc(g.name)}">${icon('edit')}</button></div><div class="flex wrap">${button('查看成員','remote-members','light small','grid',`data-id="${esc(g.id)}"`)}${button('加入所選','remote-append','light small','plus',`data-id="${esc(g.id)}" ${selection.size?'':'disabled'}`)}</div></div>`).join(''):'<div class="info-note">尚未建立組合。可把 T 區黃底一次選好，設定例如 2:20～4:00。</div>';}
function resultDataTable(resultRows=null,windowById={}){
 if(!job.rows.length)return '<div class="card card-pad quiet-note">目前沒有資料。</div>';
 const lookup=new Map((resultRows||[]).map(row=>[row.id,row])),backgrounds=backgroundReport(resultRows||job.rows).byId,codeKey=showShortCode?'d':'e';
 return `<div class="result-controls"><label><input id="result-short-code" type="checkbox" ${showShortCode?'checked':''}>顯示短編碼</label><span>${job.rows.length} 筆 · 上下、左右滑看明細</span></div><div class="table-scroll result-scroll" id="result-list" tabindex="0" aria-label="結果資料表，設備編碼固定，可上下左右捲動"><table class="data-table result-table"><colgroup>${[28,140,50,50,64,40,64,54,90,138,52,68,48].map(width=>`<col style="width:${width}px">`).join('')}</colgroup><thead><tr><th>#</th><th class="result-code-head">${showShortCode?'短編碼':'完整設備原碼'}</th><th>A<small>背景</small></th><th>B<small>淨檢</small></th><th>型式</th><th>&lt;80<small>分</small></th><th>時間</th><th>間隔</th><th>本段筆數</th><th>設備名稱</th><th>樓層</th><th>小組</th><th>詳情</th></tr></thead><tbody>${job.rows.map((base,index)=>{
  const scheduled=lookup.get(base.id),row=scheduled?{...base,...scheduled}:base,windowInfo=scheduled?windowById[base.id]:null;const manualStart=job.timeMode==='manual'&&scheduled&&(index===0||scheduled.period!==lookup.get(job.rows[index-1].id)?.period);
  return `<tr class="${rowClasses(row)}"><td>${index+1}</td><td class="result-code ${codeKey==='e'?'raw-e':'raw-d'}">${esc(base[codeKey])}</td><td class="time-cell measurement-result">${base.a==null?'—':esc(measurementDisplay(base.a))}</td><td class="time-cell measurement-result">${base.b==null?'—':esc(measurementDisplay(base.b))}</td><td>${formCell(base)}</td><td class="time-cell">${windowCell(windowInfo)}</td><td class="time-cell">${Number.isInteger(scheduled?.time)?formatClock(scheduled.time):'—'}</td><td class="time-cell">${manualStart?'<span class="interval-empty">起點</span>':intervalCell(scheduled?.interval)}</td><td>${backgroundCell(backgrounds[base.id])}</td><td class="equipment-name">${esc(base.equipment||'待確認')}<span class="equipment-tags">${equipmentChange(row)}</span></td><td>${base.floor!=null?esc(base.floor)+'F':'待確認'}</td><td>${esc(base.group||'待確認')}</td><td><button class="row-detail-button" data-act="expand" data-id="${esc(base.id)}" aria-label="${expanded.has(base.id)?'收合':'查看'}第 ${index+1} 筆詳情" aria-expanded="${expanded.has(base.id)}">${icon('more')}</button></td></tr>${expanded.has(base.id)?`<tr class="table-detail"><td colspan="13">${detailHtml(row,windowInfo)}</td></tr>`:''}`;
 }).join('')}</tbody></table></div>`;
}
function measurementDisplay(value){
 if(value==null)return '';
 const digits=(job.measurementSettings?.format||'1000')==='2020'?1:2;
 return Number(value.toFixed(digits))===value?value.toFixed(digits):String(value);
}
function measurementProgress(){const rows=job.rows;return `${rows.length} 筆 · A ${rows.filter(r=>r.a!=null).length} / B ${rows.filter(r=>r.b!=null).length}`;}
function measurementsView(){
 if(!job.rows.length)return empty();
 const rows=currentJobRows(job),settings={...DEFAULT_MEASUREMENT_SETTINGS,...job.measurementSettings};
 return `<div class="measurement-toolbar">${button('生成 A/B','generate-measurements','primary','edit',busy?'disabled':'')}${button('復原','undo','light','undo',undoStack.length&&!busy?'':'disabled')}<span data-measurement-count>${measurementProgress()}</span></div>
 ${job.measurementNotice?`<p class="notice measurement-notice">${esc(job.measurementNotice)}</p>`:''}
 <details class="card measurement-settings"><summary>範圍設定 · ${settings.format}</summary><form id="measurement-settings-form"><div class="field"><label for="measurement-format">格式</label><select id="measurement-format" name="format"><option value="1000" ${settings.format==='1000'?'selected':''}>1000 · 兩位小數</option><option value="2020" ${settings.format==='2020'?'selected':''}>2020 · 一位小數</option></select></div><div class="fields">${[['aMin','A 下限'],['aMax','A 上限'],['bMin','B 下限'],['bMax','B 上限']].map(([key,label])=>`<div class="field"><label for="measurement-${key}">${label}</label><input id="measurement-${key}" name="${key}" inputmode="decimal" value="${settings[key]}" required></div>`).join('')}</div><button type="submit" class="button light">套用範圍</button></form></details>
 <div class="table-scroll measurement-scroll" id="measurement-list" tabindex="0" aria-label="A/B 填寫表"><table class="data-table measurement-table"><colgroup><col style="width:42%"><col style="width:20%"><col style="width:20%"><col style="width:18%"></colgroup><thead><tr><th>設備長碼</th><th>A<small>背景</small></th><th>B<small>淨檢</small></th><th>型式</th></tr></thead><tbody>${rows.map((row,index)=>`<tr class="${rowClasses(row)}"><td class="measurement-code"><small>${index+1}</small><span>${esc(row.e)}</span></td>${['a','b'].map(key=>`<td><input class="measurement-input" data-measurement="${key}" data-id="${esc(row.id)}" inputmode="decimal" autocomplete="off" aria-label="第 ${index+1} 筆 ${key.toUpperCase()}" value="${esc(measurementDisplay(row[key]))}" ${busy?'disabled':''}></td>`).join('')}<td>${formCell(row)}</td></tr>`).join('')}</tbody></table></div>`;
}
function measurementChanged(){document.querySelector('.measurement-toolbar [data-act="undo"]')?.removeAttribute('disabled');job.updated=new Date().toISOString();clearTimeout(saveTimer);void persist();document.querySelectorAll('[data-measurement-count]').forEach(el=>el.textContent=measurementProgress());}
function generateAB(){
 ensureIdle();if(!resultCurrent())throw new Error('請先完成時間試排，再生成 A/B。');
 const rows=currentJobRows(job);if(rows.some(row=>!Number.isInteger(row.time)))throw new Error('時間尚未完整，請重新試排。');
 const generated=generateMeasurements(rows,job.measurementSettings);
 snapshot();storeMeasurements(job,generated);measurementChanged();renderKeepScroll();toast('A/B 已生成，可直接修改；A 會同步同背景段。');
}
function resultsView(){if(busy)return `<div class="card card-pad"><div class="card-label">${icon('refresh','loading-icon')}<h2>正在裝置內試排</h2></div><p class="quiet-note">檢查完整小組切點、上下樓、特殊加時與起訖時間。</p><div class="progress-bar"><i></i></div>${button('取消本次試排','cancel','light w100','stop')}</div>`;
 const current=resultCurrent(),stored=activeResult(job),result=current?{...stored,rows:currentJobRows(job)}:stored;
 if(!result)return `<div class="notice" style="margin-bottom:16px">${job.timeMode==='manual'?'尚未套用手動時間':'尚未試排'}；時間、間隔與 &lt;80 先顯示為 —。</div><div class="sticky-actions">${button(job.timeMode==='manual'?'編排手動時間':'試排全天','generate','primary','rocket',job.rows.length?'':'disabled')}${button('調整設定','to-settings','light','sliders')}</div>${resultDataTable()}`;
 if(!current){const failed=!result.ok,items=(result.errors||result.checks?.filter(c=>!c.ok).map(c=>c.detail)||[]).slice(0,5);return `<div class="notice ${failed?'error':''}" style="margin-bottom:16px"><strong>${failed?'這次尚未排出結果':'設定或標記已變動'}</strong><p>${failed?'這是第一版搜尋結果，不代表這份資料一定無解。':job.timeMode==='manual'?'舊結果不再顯示時間或 G，請重新套用手動時間。':'舊結果不再顯示時間或 G，請重新試排。'}</p>${items.length?`<ul>${items.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:''}</div><div class="sticky-actions">${button('回設定調整','to-settings','primary','sliders')}${button(job.timeMode==='manual'?'編輯手動時間':'重新試排','generate','light','refresh')}</div>${resultDataTable()}`;}
 const r=result.summary,windows=windowReport(result.rows,job.settings.mode),minimum=value=>Number.isInteger(value)?Math.floor(value/60)+' 分':'—';
 const filledA=job.rows.filter(row=>row.a!=null).length,filledB=job.rows.filter(row=>row.b!=null).length,completeAB=filledA===job.rows.length&&filledB===job.rows.length;
 return `<div class="review-status ${result.source==='manual'&&!result.rulesOk?'manual-review-warning':''}"><strong>${result.source==='manual'?(result.rulesOk?'手動時間 · 檢查通過':'手動時間 · 有規則提醒'):'時間檢查通過'}</strong><span class="${completeAB?'':'review-incomplete'}">A ${filledA}/${job.rows.length} · B ${filledB}/${job.rows.length}</span>${completeAB?'':button('填寫背景/值','to-measurements','light small','edit')}</div>
 <div class="review-summary">${[['上午',r.amCount,result.source==='manual'?r.amLastTime:r.amReturn,windows.amMinimum],['下午',r.pmCount,result.source==='manual'?r.pmLastTime:r.pmReturn,windows.pmMinimum]].map(([label,count,time,min])=>`<div><span>${label} · ${count} 筆</span><strong>${time!=null?formatClock(time):'—'}</strong><small>${result.source==='manual'?'最後一筆':'返回 1F'}</small><p>80窗最低 <b>${minimum(min)}</b></p></div>`).join('')}</div>
 <details class="card review-validation" ${result.source==='manual'&&!result.rulesOk?'open':''}><summary>${result.source==='manual'?'手動規則提醒':'驗證明細'} · ${windows.mode==='outdoor'?'廠外，80窗僅顯示':`低於61分 ${windows.belowThreshold} 筆`}</summary>${(result.checks||[]).map(c=>`<div class="check-row ${c.ok?'':'fail'}">${icon(c.ok?'check':'info')}<div><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div></div>`).join('')}<p class="inline-hint">${(result.warnings||[]).map(esc).join(' ')}</p></details>
 <div class="sticky-actions review-actions">${button('匯出 CSV','export-csv','light','download')}${button(job.timeMode==='manual'?'編輯手動時間':'重新試排','generate','light','refresh')}</div>${resultDataTable(result.rows,windows.byId)}`;

}
function asideView(){if(!job.rows.length||tab==='marks')return '';return `<div class="card card-pad"><div class="card-head"><h3>操作</h3></div>${button(busy?'正在試排…':job.timeMode==='manual'?'手動時間':'試排全天','generate','primary w100','rocket',job.rows.length&&!busy?'':'disabled')}${busy?button('取消','cancel','light w100','stop'):''}</div>`;
}

function selectRow(id){if(selection.has(id))selection.delete(id);else selection.add(id);if(!selection.size)paletteOpen=false;renderKeepScroll();}
function applyColor(color){ensureIdle();if(!selection.size)return;snapshot();for(const r of job.rows)if(selection.has(r.id)){if(['yellow','red'].includes(color))r.background=color;else if(color==='floor'){r.floorMark=true;if(r.background==='none')r.background='yellow';}else if(color==='extra')r.extraMark=true;else{r.background='none';r.floorMark=false;r.extraMark=false;}}changed();renderKeepScroll();toast(`已套用到 ${selection.size} 筆，可按復原。`);}
function editRow(id){const r=job.rows.find(x=>x.id===id);showModal('確認解析',`<p>D／E 原始字串不會更動。此處修改的是本卡夾的解析結果。</p><div class="sample-preview">D：${esc(r.d)}<br>E：${esc(r.e)}</div><form id="edit-row-form" data-id="${esc(id)}"><div class="fields">${[['region','區域',r.region],['equipment','設備',r.equipment],['floor','樓層（數字）',r.floor??''],['group','小組',r.group],['form','型式',r.form]].map(([key,label,v])=>`<div class="field"><label for="row-${key}">${label}</label><input id="row-${key}" name="${key}" value="${esc(v)}" ${key==='floor'?'inputmode="numeric"':''} maxlength="100"></div>`).join('')}</div><button class="button primary w100" type="submit">套用解析</button></form>`);}
function remoteDialog(id=null){const existing=job.remotes.find(g=>g.id===id);if(!existing&&!selection.size){toast('先到標記頁選取元件，再加入遠距組合。');changeTab('marks');return;}const g=existing||{name:`遠距組合 ${job.remotes.length+1}`,min:140,max:240,rowIds:[...selection]};showModal(existing?'編輯遠距組合':'建立遠距組合',`<p>共 ${g.rowIds.length} 筆。時間額外加在原本間隔上，背景、樓層與特殊照常計算。</p><form id="remote-form" data-id="${id||''}"><div class="field"><label for="remote-name">組合名稱</label><input id="remote-name" name="name" value="${esc(g.name)}" maxlength="60" required></div><div class="fields"><div class="field"><label for="remote-min">下限 · 分.秒</label><input id="remote-min" name="min" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(g.min)}" required></div><div class="field"><label for="remote-max">上限 · 分.秒</label><input id="remote-max" name="max" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(g.max)}" required></div></div><p class="inline-hint">1.30／130＝1分30秒；2.22＝2分22秒。已有單筆設定者保留。</p><div class="foot-actions">${existing?button('刪除組合','remote-delete','danger','trash',`data-id="${id}" type="button"`):''}<button class="button primary" type="submit">${existing?'儲存組合':'加入組合'}</button></div></form>`);}
function singleRemote(id){const r=job.rows.find(x=>x.id===id),remote=remoteMap(job)[id]||{min:140,max:240};showModal('單筆遠距加時',`<p>${esc(r.d)}<br>只改這一筆，其他組合成員維持原時間。</p><form id="single-remote-form" data-id="${esc(id)}"><div class="fields"><div class="field"><label for="single-min">下限 · 分.秒</label><input id="single-min" name="min" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(remote.min)}"></div><div class="field"><label for="single-max">上限 · 分.秒</label><input id="single-max" name="max" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(remote.max)}"></div></div><p class="inline-hint">1.30／130＝1分30秒；2.22＝2分22秒。</p><div class="foot-actions">${button('恢復組合時間','remote-reset','light','undo',`data-id="${esc(id)}" type="button"`)}<button class="button primary" type="submit">套用單筆</button></div></form>`);}
async function shelf(){await persist();showModal('我的卡夾',`<p>卡夾保留在這台裝置；透過匯出、匯入帶到另一台。</p>${jobs.sort((a,b)=>b.updated.localeCompare(a.updated)).map(j=>`<button class="job-card ${j.id===job.id?'active':''}" data-act="load-job" data-id="${esc(j.id)}"><div><strong>${esc(j.name)}</strong><p>${esc(j.rows.length?j.plant:'未選廠別')} · ${j.rows.length} 筆 · ${new Date(j.updated).toLocaleDateString('zh-TW')}</p></div>${icon('chevron')}</button>`).join('')}<div class="shelf-tools">${button('新增空白卡夾','new-job','primary','plus')}${button('匯入卡夾','restore','light','upload')}${button('匯出目前','backup','light','download')}</div>${button('刪除目前卡夾','delete-job','ghost small','trash','style="margin-top:18px"')}`);}
async function openWorkbook(file){if(!file)return;try{ensureIdle();if(file.size>20*1024*1024)throw new Error('檔案超過 20 MB，請先另存需要的工作頁。');showModal('讀取工作頁',`<p>${esc(file.name)}</p><div class="progress-bar"><i></i></div><p>只在本機讀取，不會執行活頁簿的巨集。</p>`);const token=crypto.randomUUID();importData={token,fileName:file.name,rows:[],sheets:[]};importer?.terminate();importer=new Worker('./import-worker.js');importer.onerror=()=>{toast('活頁簿讀取失敗，請重新選擇。');closeModal();};importer.onmessage=({data})=>{if(importData?.token!==token)return;if(data.type==='error'){toast(data.message);closeModal();return;}if(data.type==='sheets'){importData.sheets=data.sheets;importData.visibility=data.visibility;importDialog();requestSheet();}if(data.type==='rows'){if(data.requestId!==importData.requestId)return;importData.rows=data.rows;renderImportPreview();const c=document.getElementById('import-count');if(c)c.textContent=`讀到 ${data.rows.length} 筆`;const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=!data.rows.length||!document.getElementById('import-plant').value;}};const buffer=await file.arrayBuffer();if(importData?.token===token)importer.postMessage({action:'open',buffer},[buffer]);}catch(error){toast(error.message);}}
function importDialog(){const inferred=PLANTS.filter(p=>!['示範廠','手動'].includes(p)).sort((a,b)=>b.length-a.length).find(p=>importData.fileName.toUpperCase().includes(p.toUpperCase()))||'';showModal('選擇匯入範圍',`<p>${esc(importData.fileName)}</p><div class="field" style="margin-bottom:12px"><label for="sheet-search">搜尋工作頁</label><input id="sheet-search" type="text" placeholder="份數、中文字或 (區域)"></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="show-hidden">顯示隱藏工作頁</label><div class="field"><label for="import-sheet">工作頁（完整原名）</label><select id="import-sheet">${sheetOptions()}</select></div><div class="fields three"><div class="field"><label for="import-start">從第幾列開始</label><input id="import-start" inputmode="numeric" type="number" min="1" max="100000" value="3"></div><div class="field"><label for="import-amount">最多幾筆</label><input id="import-amount" inputmode="numeric" type="number" min="1" max="448" value="400"></div><div class="field"><label for="import-plant">廠別</label><select id="import-plant"><option value="" ${inferred?'':'selected'}>請選擇廠別</option>${PLANTS.filter(p=>p!=='示範廠').map(p=>`<option ${p===inferred?'selected':''}>${esc(p)}</option>`).join('')}</select></div></div><div class="fields"><div class="field"><label for="import-d-column">D 元件來源欄</label><input id="import-d-column" value="B" autocapitalize="characters"></div><div class="field"><label for="import-e-column">E 長碼來源欄</label><input id="import-e-column" value="C" autocapitalize="characters"></div></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="import-reverse">再反轉 D／E 來源</label><div class="import-mapping" id="import-mapping">一般來源 B→D、C→E；油類使用廠別的反轉設定。</div><p class="inline-hint" id="import-count">讀取中…</p><div id="import-preview" class="sample-preview" style="margin-top:10px">準備預覽前三筆。</div><div class="foot-actions">${button('匯入新卡夾','accept-import','primary','arrow','disabled')}</div>`);loadImportParams();}
function sheetOptions(query='',includeHidden=false){return (importData.visibility||importData.sheets.map(name=>({name,hidden:0}))).filter(s=>(includeHidden||!s.hidden)&&matchSheetName(s.name,query)).map(s=>`<option value="${esc(s.name)}">${esc(s.name)}${s.hidden===2?' · 深度隱藏':s.hidden?' · 隱藏':''}</option>`).join('');}
let sheetTimer;
function filterSheets(){const select=document.getElementById('import-sheet'),previous=select.value;select.innerHTML=sheetOptions(document.getElementById('sheet-search').value,document.getElementById('show-hidden').checked);if([...select.options].some(o=>o.value===previous)){select.value=previous;return;}importData.rows=[];importData.requestId=(importData.requestId||0)+1;document.querySelector('[data-act="accept-import"]').disabled=true;clearTimeout(sheetTimer);sheetTimer=setTimeout(()=>requestSheet(),250);}
function requestSheet(){if(!importer)return;const sheet=document.getElementById('import-sheet').value;importData.rows=[];const acceptButton=document.querySelector('[data-act="accept-import"]');if(acceptButton)acceptButton.disabled=true;if(!sheet){document.getElementById('import-preview').textContent='沒有符合條件的工作頁，可調整搜尋或顯示隱藏頁。';document.getElementById('import-count').textContent='0 筆';return;}const params=importParamsFromForm(),{first,count}=params;const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=true;importData.requestId=(importData.requestId||0)+1;document.getElementById('import-count').textContent='正在讀取所選頁面…';importer.postMessage({action:'sheet',name:sheet,first,count,bColumn:params.dColumn,cColumn:params.eColumn,requestId:importData.requestId});}
function renderImportPreview(){
 const select=document.getElementById('import-plant'),box=document.getElementById('import-preview'),mapping=document.getElementById('import-mapping');
 if(!select||!box||!importData)return;
 const plant=select.value,params=importParamsFromForm(),reverse=params.reverse;
 const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=!plant||!importData.rows.length;
 if(!plant){mapping.textContent='請選擇本次廠別，不沿用上一張卡夾。';box.innerHTML=importData.rows.slice(0,3).map(r=>`<p>${esc(params.dColumn)}：${esc(r.b)}<br>${esc(params.eColumn)}：${esc(r.c)}</p>`).join('')||'此範圍沒有資料。';return;}
 const swap=REVERSED_SOURCE_PLANTS.has(plant)!==reverse,support=plantSupport(plant);
 mapping.textContent=`${plant} · ${support.label} · ${reverse?params.eColumn:params.dColumn}→D、${reverse?params.dColumn:params.eColumn}→E`;
 const rows=parseRows(importData.rows.slice(0,3),plant,swap,plantProfile(plant).rules);
 box.innerHTML=rows.map(r=>`<div class="import-parsed"><strong>${esc(r.equipment||'設備待確認')}</strong><span>${r.floor==null?'樓層待確認':r.floor+'F'} · ${esc(r.form||'型式待確認')}</span><small>區域 ${esc(r.region||'—')} · 小組 ${esc(r.group||'—')}</small>${r.issues.length?`<p class="parse-warning">${r.issues.map(esc).join('；')}</p>`:''}<details><summary>原碼</summary><p>${esc(r.d)}<br>${esc(r.e)}</p></details></div>`).join('')||'此範圍沒有資料。';
}
async function acceptImport(){ensureIdle();const plant=document.getElementById('import-plant').value,params=importParamsFromForm(),rules=plantProfile(plant).rules,rows=parseRows(importData.rows,plant,REVERSED_SOURCE_PLANTS.has(plant)!==params.reverse,rules),sheet=document.getElementById('import-sheet').value;if(!PLANTS.includes(plant))throw new Error('請先選擇廠別。');if(!rows.length)throw new Error('沒有資料可匯入。');const name=importData.fileName;await persist();job=blankJob(`${plant} · ${sheet}`);Object.assign(job,{sourceName:name,sheet,plant,rows,parserRules:rules,importParams:params});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];closeModal();await persist();changeTab('data');toast(`已匯入 ${rows.length} 筆。原有卡夾已保留。`);}
async function loadProject(file){if(!file)return;try{ensureIdle();if(file.size>5*1024*1024)throw new Error('卡夾大於 5 MB，無法匯入。');const data=validateProject(JSON.parse(await file.text()));const errors=validateSettings(data.settings);if(errors.length)throw new Error(errors.join('；'));await persist();job=data;selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');toast('卡夾已匯入；時間結果會重新驗算。');}catch(error){toast(error.message);}}
function download(content,name,mime='application/json'){const blob=new Blob([content],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
function backup(){const visible=currentJobRows(job);const copy={...job,rows:job.rows.map((row,i)=>({...row,background:visible[i].background}))};download(JSON.stringify(copy,null,2),`${job.name.replace(/[\\/:*?"<>|]/g,'_')}.log.json`);toast('卡夾已交給瀏覽器下載，手機可在「檔案」保留。');}
function exportCSV(){if(!resultCurrent())throw new Error('請先完成本次設定的試排。');const lines=[['試排資料（未完成 Excel 正式驗收）'],['序號','元件 D','設備原碼 E','設備','區域','樓層','小組','型式','時段','時間','間隔','背景','樓層標記','額外標記','A 背景','B 淨檢']];currentJobRows(job).forEach((r,i)=>lines.push([i+1,r.d,r.e,r.equipment,r.region,r.floor,r.group,r.form,r.period,formatClock(r.time),formatDuration(r.interval),r.background,r.floorMark,r.extraMark,r.a,r.b]));download('\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n',`${job.name.replace(/[\\/:*?"<>|]/g,'_')}-試排.csv`,'text/csv;charset=utf-8');}
async function generate(){ensureIdle();if(job.timeMode==='manual'){changeTab('manual');return;}if(!job.rows.length)throw new Error('請先匯入資料。');const errors=validateSettings(job.settings);if(errors.length)throw new Error(errors.join('；'));busy=true;try{snapshot();job.rows=autocolor(job.rows);changed();tab='results';render();window.scrollTo({top:0,behavior:'instant'});await persist();if(!busy)return;solver=new Worker('./solver-worker.mjs',{type:'module'});}catch(error){busy=false;render();throw error;}const revision=job.revision;
 const finish=()=>{solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;};
 solver.onmessage=({data})=>{finish();if(data.type==='result'&&data.revision===job.revision){job.result={...data.result,revision};saveSoon();render();toast(data.result.ok?'試排完成，可點元件查看間隔組成。':'本次尚未找到方案，詳情已列出。');}else{render();toast(data.message||'資料已變動，結果未套用。');}};
 solver.onerror=()=>{finish();render();toast('試排器未能完成，原有資料與結果保留。');};
 solverTimer=setTimeout(()=>{finish();render();toast('本次試排超過 20 秒，已停止工作程序，原資料保留。');},20000);
 solver.postMessage({rows:job.rows,settings:job.settings,remoteMap:remoteMap(job),seed:crypto.getRandomValues(new Uint32Array(1))[0],revision});
}
function cancel(){solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;if(tab==='manual'){manualProposal=null;manualUi.feedback='已取消調整，原候選保留。';renderKeepScroll();}else{render();toast('已取消試排，資料與標記保留。');}}
let guideReturn='settings';
function guideView(){
 const rule=colorTimeGuide(job.settings),range=values=>values.map(formatDuration).join('～');
 const rows=[
  ['yellow','黃底',range(rule.background),'換背景'],
  ['blue','藍底',range(rule.background),'程式補背景，同黃底'],
  ['red','紅底',range(rule.cross),'已含背景＋跨區；換樓層再加移動'],
  ['floor','樓層紅字','背景＋樓層移動','依相差樓層計算，底色保留'],
  ['extra','黃字',range(rule.extra),'無底色、未換樓層時使用；有底色則依底色時間'],
  ['special','粉字 CPRSAI',`＋${formatDuration(rule.special)}`,'型式命中任一字母，每筆只加一次'],
 ];
 return `<div class="color-guide">${rows.map(([color,label,time,note])=>`<article class="card color-guide-row"><span class="guide-swatch guide-${color}" aria-hidden="true">${['floor','extra','special'].includes(color)?'字':''}</span><div><h2>${label}</h2><p>${note}</p></div><strong class="guide-time">${time}</strong></article>`).join('')}<details class="card guide-floors"><summary>樓層紅字 · 含黃底時間</summary><div class="guide-floor-table"><table><thead><tr><th>相差</th><th>上樓</th><th>下樓</th></tr></thead><tbody>${rule.floors.map(f=>`<tr><th>${f.difference} 層</th><td>${range(f.up)}</td><td>${range(f.down)}</td></tr>`).join('')}</tbody></table></div></details><p class="inline-hint guide-note">每段首筆黃底依進場 ${range(rule.entry)}，上樓另加。粉字、遠距另行疊加。</p></div>`;
}
function help(){showModal('資訊',button('操作說明 · 顏色時間','color-guide','light w100','paint')+infoHtml(),'info');refreshUpdateState();void updater?.check(true);}

async function action(name,el){
 const mutating=['reparse-pending','time-mode','manual-open','manual-apply','manual-adjust','manual-adjust-accept','manual-delete','manual-restore','manual-undo','manual-use-settings','generate-measurements','paint','undo','autocolor','remote-add','remote-edit','remote-append','remote-delete','remote-reset','edit-row','edit-distance','setting-choice','new-job','delete-job','load-job','demo','rename','import','restore'];if(mutating.includes(name))ensureIdle();
 const id=el.dataset.id;
 switch(name){

 case 'tab':changeTab(el.dataset.tab);break;
 case 'time-mode':{const mode=el.dataset.value;if(!['auto','manual'].includes(mode))return;if(job.timeMode!==mode){snapshot();job.timeMode=mode;job.updated=new Date().toISOString();saveSoon();}render();break;}
 case 'manual-open':changeTab('manual');break;
 case 'manual-confirm-am':{ensureIdle();const next=confirmManualMorning(job.manualPlan,Number(el.dataset.index));manualCheckpoint('確認上午至第 '+next.settings.amCount+' 筆');job.manualPlan=next;manualDraftChanged();resetManualSelection();manualUi.period='pm';manualUi.feedback='上午至第 '+next.settings.amCount+' 筆；下午從第 '+(next.settings.amCount+1)+' 筆開始。';render();requestAnimationFrame(()=>document.querySelector('.manual-config')?.scrollIntoView({block:'center'}));break;}
 case 'manual-reopen-am':{ensureIdle();if(!confirm('保留上午時刻，重新選擇上午末筆；下午候選會清除，之後另行生成。可按復原還原。'))return;const next=reopenManualMorning(job.manualPlan,job.rows.length);manualCheckpoint('重開上午');job.manualPlan=next;manualDraftChanged();resetManualSelection();manualUi.period='am';manualUi.feedback='上午時刻已保留，請重新確認末筆。';renderKeepScroll();break;}
 case 'manual-results':changeTab('results');break;
 case 'manual-use-settings':{manualCheckpoint();job.manualSettings=normalizeManualSettings({...manualSettingsFor(job),...Object.fromEntries(['amStart','amEnd','pmStart','pmEnd'].map(key=>[key,job.settings[key]]))});saveSoon();renderKeepScroll();toast('已取用目前時段，產生候選後套用。');break;}
 case 'plant-rule-reset':ensureIdle();savePlantProfile(selectedPlant(),{rules:{}});render();toast(selectedPlant()+' 已恢復預設規則，並儲存至本機。');break;
 case 'import-params-reset':ensureIdle();savePlantProfile(selectedPlant(),{importParams:normalizeImportParams({},selectedPlant())});render();toast(selectedPlant()+' 匯入參數已恢復預設，並儲存至本機。');break;
 case 'plant-rule-apply':ensureIdle();previewPlantRules();break;
 case 'plant-rule-confirm':{ensureIdle();const proposal=plantProposal;if(!proposal||proposal.jobId!==job.id||proposal.revision!==job.revision)throw new Error('卡夾已變更，請重新預覽。');savePlantProfile(proposal.plant,{rules:proposal.rules});snapshot();job.rows=proposal.rows;job.plant=proposal.plant;job.parserRules=proposal.rules;changed();plantProposal=null;selection.clear();closeModal();changeTab('data');toast('廠別已重新判定，可復原；時間須重新生成。');break;}
 case 'manual-history':showModal('復原紀錄',manualHistoryView(manualUi.history,{esc,button}));break;
 case 'manual-history-restore':{ensureIdle();const entry=manualUi.history[Number(el.dataset.index)],restored=restoreManualState(job,entry);manualCheckpoint('返回「'+entry.label+'」紀錄');Object.assign(job,restored);manualDraftChanged();resetManualSelection();manualUi.feedback='已回到「'+entry.label+'」之前，可按復原回到剛才。';if(job.manualPlan?.schema===4&&job.manualPlan.phase==='am')manualUi.period='am';closeModal();renderKeepScroll();break;}
 case 'manual-windows':showModal((manualUi.period==='am'?'上午':'下午')+' &lt;80 驗證',manualWindowsView(job,job.manualPlan,manualUi.period,{esc,button}));break;
 case 'manual-window-focus':{const index=Number(el.dataset.index),list=manualHalfRows(job,job.manualPlan,manualUi.period),position=list.findIndex(row=>row.index===index&&row.window?.seconds!=null);if(position<0)throw new Error('此窗口已變動，請重新查看。');resetManualSelection();manualUi.selection.add(index);manualUi.shown=Math.max(manualUi.shown,position+1);closeModal();render();requestAnimationFrame(()=>{const container=document.getElementById('manual-list'),row=container?.querySelector('tr[data-index="'+index+'"]');if(container&&row){container.scrollLeft=0;container.scrollTop=row.offsetTop-container.querySelector('thead').offsetHeight;container.scrollIntoView({block:'center'});}});break;}
 case 'manual-period':manualState();manualUi.period=el.dataset.period;resetManualSelection();renderKeepScroll();break;
 case 'manual-range-mode':manualUi.rangeMode=!manualUi.rangeMode;manualUi.anchor=null;renderKeepScroll();break;
 case 'manual-select':selectManualCandidate(el.dataset.period,Number(el.dataset.index));break;
 case 'manual-clear':resetManualSelection();renderKeepScroll();break;
 case 'manual-delete':case 'manual-restore':{if(!manualUi.selection.size||!job.manualPlan)return;const next=setManualExcluded(job.manualPlan,manualUi.period,[...manualUi.selection],name==='manual-delete');const selected=manualHalfRows(job,job.manualPlan,manualUi.period).filter(row=>manualUi.selection.has(row.index)&&row.target).map(row=>row.sourceIndex+1);manualCheckpoint((name==='manual-delete'?'刪除':'還原')+(manualUi.period==='am'?'上午':'下午')+' '+manualUi.selection.size+' 個時刻'+(selected.length?'（元件'+selected.slice(0,4).join('、')+(selected.length>4?'等':'')+'）':''));job.manualPlan=next;manualDraftChanged();resetManualSelection();manualUi.feedback=name==='manual-delete'?'已刪除，<80 已重新核算。':'已還原，<80 已重新核算。';document.getElementById('toast').hidden=true;renderKeepScroll();break;}
 case 'manual-undo':{manualState();const previous=manualUi.history.at(-1);if(previous){const restored=restoreManualState(job,previous);manualUi.history.pop();Object.assign(job,restored);manualDraftChanged();manualProposal=null;resetManualSelection();manualUi.feedback='已復原候選，<80 已重新核算。';job.updated=new Date().toISOString();saveSoon();renderKeepScroll();}break;}
 case 'manual-apply':applyManualTimes();break;
 case 'manual-adjust':startManualAdjustment();break;
 case 'manual-adjust-accept':acceptManualAdjustment();break;
 case 'manual-more':manualUi.shown+=200;renderKeepScroll();break;
 case 'to-measurements':changeTab('measurements');break;
 case 'to-marks':changeTab('marks');break;case 'to-settings':changeTab('settings');break;
 case 'close-modal':closeModal();break;case 'help':help();break;
 case 'color-guide':if(tab!=='guide')guideReturn=tab;if(modal.open)closeModal();changeTab('guide');break;
 case 'guide-back':changeTab(guideReturn);break;
 case 'check-update':if(updater?.state==='recovery')await updater.recover();else await updater?.update();break;
 case 'recover-update':await updater?.recover();break;
 case 'import':document.getElementById('source-file').click();break;
 case 'restore':closeModal();document.getElementById('project-file').click();break;
 case 'accept-import':await acceptImport();break;
 case 'demo':{await persist();const demo=makeDemo();job=blankJob(demo.name);Object.assign(job,demo,{demo:true});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];await persist();changeTab('data');toast('這是合成資料，可放心試標記。');break;}
 case 'select':selectRow(id);break;
 case 'expand':expanded.has(id)?expanded.delete(id):expanded.add(id);renderKeepScroll();break;
 case 'select-filter':filtered().forEach(r=>selection.add(r.id));renderKeepScroll();break;
 case 'select-group':{const keys=new Set(job.rows.filter(r=>selection.has(r.id)).map(r=>[r.region,r.equipment,r.group].join('|')));job.rows.forEach(r=>{if(r.group&&keys.has([r.region,r.equipment,r.group].join('|')))selection.add(r.id);});renderKeepScroll();break;}
 case 'deselect':selection.clear();paletteOpen=false;renderKeepScroll();break;
 case 'palette-toggle':paletteOpen=!paletteOpen;renderKeepScroll();break;
 case 'view-mode':viewMode=el.dataset.value;shown=60;rememberUi();renderKeepScroll();break;
 case 'more':shown+=60;renderKeepScroll();break;
 case 'paint':applyColor(el.dataset.color);break;
 case 'undo':if(undoStack.length){job=undoStack.pop();manualUi.history=[];resetManualSelection();saveSoon();render();toast('已復原前一步。');}break;
 case 'autocolor':snapshot();job.rows=autocolor(job.rows);changed();render();toast('已依設備、樓層、區域檢查標記。');break;
 case 'setting-choice':snapshot();job.settings[el.dataset.key]=el.dataset.value;changed();render();break;
 case 'edit-row':editRow(id);break;case 'edit-distance':singleRemote(id);break;
 case 'remote-add':remoteDialog();break;case 'remote-edit':remoteDialog(id);break;
 case 'remote-members':{const g=job.remotes.find(x=>x.id===id);showModal(esc(g.name),`<p>${g.rowIds.length} 筆 · 點「單筆遠距」可覆寫其中一筆。</p>${g.rowIds.map(rid=>{const r=job.rows.find(x=>x.id===rid),m=remoteMap(job)[rid];return `<div class="job-card"><div><strong>${esc(r.d)}</strong><p>+${formatDuration(m.min)}～${formatDuration(m.max)}${job.overrides[rid]?' · 單筆覆寫':''}</p></div>${button('單筆','edit-distance','light small','',`data-id="${rid}"`)}</div>`;}).join('')}`);break;}
 case 'remote-append':snapshot();for(const g of job.remotes)g.rowIds=g.rowIds.filter(rid=>!selection.has(rid));job.remotes.find(g=>g.id===id).rowIds.push(...selection);selection.clear();changed();render();toast('已加入組合；每筆只套一組遠距。');break;
 case 'remote-delete':if(confirm('移除這個遠距組合？單筆自訂仍會保留。')){snapshot();job.remotes=job.remotes.filter(g=>g.id!==id);changed();closeModal();render();}break;
 case 'remote-reset':snapshot();delete job.overrides[id];changed();closeModal();render();toast('已恢復組合時間。');break;
 case 'generate-measurements':generateAB();break;
 case 'generate':await generate();break;case 'cancel':cancel();break;
 case 'shelf':await shelf();break;case 'backup':backup();break;case 'export-csv':exportCSV();break;
 case 'new-job':await persist();job=blankJob();selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');break;
 case 'load-job':await persist();job=structuredClone(jobs.find(j=>j.id===id));selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();changeTab('data');await persist();break;
 case 'delete-job':if(confirm(`只刪除此裝置的「${job.name}」卡夾？原始 XLSX 不會刪除。`)){deletingJob=true;clearTimeout(saveTimer);try{await saveChain.catch(()=>{});await removeJob(job.id);jobs=jobs.filter(j=>j.id!==job.id);job=jobs.length?structuredClone(jobs[0]):blankJob();selection.clear();expanded.clear();undoStack=[];search='';regionFilter='';markFilter='all';paletteOpen=false;closeModal();}finally{deletingJob=false;}await persist();changeTab('data');}break;
 case 'reparse-pending':{const next=reparsePendingRows(job.rows,job.plant,job.parserRules||{}),keys=['region','equipment','floor','group','form','issues'];if(!next.some((r,i)=>keys.some(k=>JSON.stringify(r[k])!==JSON.stringify(job.rows[i][k])))){toast('已核對，目前待確認項目仍需人工修正。');break;}snapshot();job.rows=next;changed();selection.clear();renderKeepScroll();toast(`重新判定完成；剩 ${counts().issues} 筆待確認。時間需重新生成，可復原。`);break;}
 case 'rename':showModal('卡夾名稱',`<form id="rename-form"><div class="field"><label for="job-name">方便你下次找到</label><input id="job-name" name="name" maxlength="100" required value="${esc(job.name)}"></div><div class="foot-actions"><button class="button primary" type="submit">儲存</button></div></form>`);break;
 }
}
let dispatchBusy=false;
document.addEventListener('click',event=>{const el=event.target.closest('[data-act]');if(!el||el.disabled)return;event.preventDefault();const exclusive=['demo','new-job','load-job','delete-job','accept-import','shelf'].includes(el.dataset.act);if(exclusive&&dispatchBusy)return;if(exclusive)dispatchBusy=true;action(el.dataset.act,el).catch(e=>toast(e.message)).finally(()=>{if(exclusive)dispatchBusy=false;});});
document.addEventListener('keydown',event=>{if(event.target.closest('button,input,select,textarea,a'))return;const el=event.target.closest('[role="button"][data-act],tr[data-act],.row-main[data-act="select"]');if(el&&(event.key==='Enter'||event.key===' ')){event.preventDefault();action(el.dataset.act,el).catch(e=>toast(e.message));}});
document.addEventListener('input',event=>{if(event.target.id==='sheet-search'){filterSheets();return;}if(event.target.id==='search'){search=event.target.value;const focus=event.target.selectionStart,scrollY=window.scrollY;render();const input=document.getElementById('search');input.focus({preventScroll:true});input.setSelectionRange(focus,focus);window.scrollTo({top:scrollY,behavior:'instant'});}});
document.addEventListener('change',event=>{const el=event.target;try{

 if(el.dataset.manualSetting){ensureIdle();const key=el.dataset.manualSetting,current=manualSettingsFor(job),value=['base','rand'].includes(key)?Number(el.value):el.value;job.manualSettings=normalizeManualSettings({...current,[key]:value});job.updated=new Date().toISOString();saveSoon();el.value=job.manualSettings[key];return;}
 if(el.id==='manual-cut'){ensureIdle();const n=Number(el.value);if(!Number.isInteger(n)||n<0||n>job.rows.length)throw new Error('上午筆數須在元件總筆數內。');manualCheckpoint();job.manualPlan={...job.manualPlan,settings:{...job.manualPlan.settings,amCount:n}};job.manualSettings={...manualSettingsFor(job),amCount:n};manualDraftChanged();renderKeepScroll();return;}
 if(el.dataset.measurement){ensureIdle();const rows=currentJobRows(job),updated=el.dataset.measurement==='a'?setSegmentA(rows,el.dataset.id,el.value):setRowB(rows,el.dataset.id,el.value);snapshot();storeMeasurements(job,updated);measurementChanged();const values=new Map(job.rows.map(row=>[row.id,row]));document.querySelectorAll('[data-measurement]').forEach(input=>{input.value=measurementDisplay(values.get(input.dataset.id)?.[input.dataset.measurement]);});document.querySelector('.measurement-notice')?.remove();return;}
 if(el.id==='region-filter'){regionFilter=el.value;shown=60;renderKeepScroll();}else if(el.id==='mark-filter'){markFilter=el.value;shown=60;renderKeepScroll();}else if(el.id==='context-filter'){showContext=el.checked;rememberUi();renderKeepScroll();}
 else if(el.id==='result-short-code'){showShortCode=el.checked;renderKeepScroll();}
 else if(['rule-plant','params-plant'].includes(el.id)){configPlant=el.value;renderKeepScroll();}
 else if(el.id==='import-plant'){loadImportParams();requestSheet();}
 else if(el.id==='import-reverse')renderImportPreview();
 else if(['import-sheet','import-start','import-amount','import-d-column','import-e-column'].includes(el.id))requestSheet();else if(el.id==='show-hidden')filterSheets();
 else if(el.dataset.setting){ensureIdle();const key=el.dataset.setting;let value;if(el.dataset.kind==='clock')value=formatClock(parseClock(el.value)).slice(0,5);else if(el.dataset.kind==='duration')value=durationInput(el.value);else{value=Number(el.value);if(!Number.isInteger(value)||value<1||value>3600)throw new Error('秒數請填 1～3600 的整數。');}snapshot();job.settings[key]=value;changed();el.value=el.dataset.kind==='duration'?formatDuration(value):value;toast('設定已儲存，原結果需要重新試排。');}
 }catch(error){toast(error.message);if(el.dataset.manualSetting)el.value=manualSettingsFor(job)[el.dataset.manualSetting];if(el.id==='manual-cut')el.value=job.manualPlan.settings.amCount;if(el.dataset.measurement)el.value=measurementDisplay(job.rows.find(row=>row.id===el.dataset.id)?.[el.dataset.measurement]);if(el.dataset.setting){const v=job.settings[el.dataset.setting];el.value=el.dataset.kind==='duration'?formatDuration(v):v;}}
});
document.addEventListener('submit',event=>{event.preventDefault();try{ensureIdle();const form=event.target,fd=new FormData(form);if(form.id==='manual-settings-form'||form.id==='manual-afternoon-form'){const input=Object.fromEntries(fd);for(const key of ['base','rand'])input[key]=Number(input[key]);const settings=normalizeManualSettings({...manualSettingsFor(job),...input}),afternoon=form.id==='manual-afternoon-form';if((afternoon?job.manualPlan?.phase==='pm':job.manualPlan)&&!confirm(afternoon?'只重建下午候選；上午保留。可按復原還原。':'重建會更換上午亂數並清除下午候選；已套用的結果保留。'))return;const plan=afternoon?createManualAfternoon(job.manualPlan,settings):createManualMorningPlan(settings,job.rows.length);manualCheckpoint(afternoon?'生成下午':'生成上午');job.manualSettings=settings;job.manualPlan=plan;manualDraftChanged();resetManualSelection();manualUi.period=afternoon?'pm':'am';manualUi.shown=400;manualUi.feedback=afternoon?'下午候選已生成，接續上午剩餘元件。':'上午候選已生成；編排完成後確認末筆。';renderKeepScroll();}
 else if(form.id==='plant-rule-form'){savePlantProfile(selectedPlant(),{rules:normalizePlantRule(selectedPlant(),Object.fromEntries(fd))});renderKeepScroll();toast(selectedPlant()+' 自訂規則已儲存至本機，下次自動讀取。');}
 else if(form.id==='import-params-form'){savePlantProfile(selectedPlant(),{importParams:normalizeImportParams({...Object.fromEntries(fd),reverse:fd.has('reverse')},selectedPlant())});renderKeepScroll();toast(selectedPlant()+' 匯入參數已儲存至本機，下次自動讀取。');}
 else if(form.id==='manual-range-form'){if(!job.manualPlan)return;const first=Number(fd.get('first')),last=Number(fd.get('last')),rows=manualHalfRows(job,job.manualPlan,manualUi.period).filter(row=>row.target&&row.sourceIndex+1>=first&&row.sourceIndex+1<=last);if(!Number.isInteger(first)||!Number.isInteger(last)||first<1||last<first||last>job.rows.length||!rows.length||rows.length!==last-first+1)throw new Error('請輸入目前半日可見的元件編號範圍。');rows.forEach(row=>manualUi.selection.add(row.index));manualUi.anchor=null;manualUi.shown=Math.max(manualUi.shown,rows.at(-1).index+1);renderKeepScroll();}
 else if(form.id==='manual-seconds-form'){const period=form.dataset.period,index=Number(form.dataset.index),seconds=durationInput(fd.get('seconds')),current=manualHalfRows(job,job.manualPlan,period).find(row=>row.index===index);if(current?.first)throw new Error('首筆是起點，請在亂數與時段設定起始時刻。');const before=current?.interval;const next=setManualInterval(job.manualPlan,period,index,seconds,parseClock(job.settings[period+'Start']));manualCheckpoint('修改元件 '+(current.sourceIndex+1)+' 間隔');job.manualPlan=next;manualDraftChanged();const delta=seconds-before;manualUi.feedback='間隔已改為 '+formatDuration(seconds)+'；本筆及'+(period==='am'?'上午':'下午')+'後續'+(delta<0?'提前 ':'延後 ')+formatDuration(Math.abs(delta))+'。<80 已重算。';renderKeepScroll();}
 else if(form.id==='edit-row-form'){const floor=Number(fd.get('floor'));if(!Number.isInteger(floor)||floor<1||floor>99||!String(fd.get('region')).trim()||!String(fd.get('equipment')).trim()||!String(fd.get('group')).trim())throw new Error('請填區域、設備、小組，以及 1～99 的樓層。');snapshot();const row=job.rows.find(r=>r.id===form.dataset.id);for(const k of ['region','equipment','group','form'])row[k]=String(fd.get(k)).trim();row.floor=floor;row.issues=[];changed();closeModal();render();}
 else if(['remote-form','single-remote-form'].includes(form.id)){const min=durationInput(fd.get('min')),max=durationInput(fd.get('max'));if(min>max)throw new Error('下限不能大於上限。');snapshot();if(form.id==='single-remote-form')job.overrides[form.dataset.id]={min,max};else{const name=String(fd.get('name')).trim();if(!name)throw new Error('請填組合名稱。');const existing=job.remotes.find(g=>g.id===form.dataset.id);if(existing)Object.assign(existing,{name,min,max});else{for(const g of job.remotes)g.rowIds=g.rowIds.filter(id=>!selection.has(id));job.remotes.push({id:crypto.randomUUID(),name,min,max,rowIds:[...selection]});selection.clear();}}changed();closeModal();render();toast('遠距加時已儲存，重新試排才會套用。');}
 else if(form.id==='measurement-settings-form'){const settings=normalizeMeasurementSettings(Object.fromEntries(fd));snapshot();job.measurementSettings=settings;measurementChanged();renderKeepScroll();toast('範圍已套用；按「生成 A/B」才會更換數值。');}
 else if(form.id==='rename-form'){job.name=String(fd.get('name')).trim()||'未命名卡夾';job.updated=new Date().toISOString();saveSoon();closeModal();render();}
 }catch(error){toast(error.message);}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);persist();}});
window.addEventListener('pagehide',()=>{solver?.terminate();importer?.terminate();});
async function start(){try{jobs=await getJobs();let last;try{last=localStorage.getItem('log-active');viewMode=localStorage.getItem('log-row-view')||'table';showContext=localStorage.getItem('log-filter-context')==='1';}catch{}if(!['table','cards'].includes(viewMode))viewMode='table';job=structuredClone(jobs.find(j=>j.id===last)||jobs.sort((a,b)=>b.updated.localeCompare(a.updated))[0]||blankJob());saveState=jobs.length?'已存於此裝置':'尚未儲存';}catch{job=blankJob();saveState='此瀏覽器無法儲存';}render();
 updater=createUpdater({serviceWorker:navigator.serviceWorker,currentVersion:globalThis.LOG_RELEASE?.version,getLatestVersion:fetchReleaseVersion,isBusy:()=>busy||Boolean(importer)||txtOutput.isBusy(),hasOpenEditor:()=>modal.open&&modal.dataset.kind!=='info',canAutoUpdate:()=>updateIdle,
  save:async()=>{clearTimeout(saveTimer);return await persist();},
  onStatus:(_state,message)=>{refreshUpdateState();if(message)toast(message);}
 });
 for(const event of ['pointerdown','touchstart','wheel','keydown','input'])document.addEventListener(event,()=>{updateIdle=false;},{capture:true,passive:true});
 await updater.update({automatic:true});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')updateIdle=true;else updater.update({automatic:true});});
 window.addEventListener('pageshow',event=>{if(event.persisted)updater.update({automatic:true});});
 window.addEventListener('online',()=>updater.check(true));
}

start();
