import {DEFAULT_SETTINGS,PLANTS,parseRows,makeDemo,autocolor,parseClock,formatClock,formatDuration,validateSettings} from './domain.mjs';
import {saveJob,getJobs,removeJob,validateProject,remoteMap,durationInput,csvCell,matchSheetName} from './storage.mjs';

const icons={
 folder:'M3 7V5a1 1 0 0 1 1-1h5l2 3h9a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7Z',
 file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8M8 17h5',
 upload:'M12 16V3m-5 5 5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5',
 download:'M12 3v13m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4',
 paint:'m15 3 6 6-9 9-6-6ZM6 12l-3 3 6 6 3-3M4 3l10 10',
 clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 sliders:'M4 4v5m0 6v5m8-16v9m0 6v1m8-16v1m0 6v9M1 9h6v6H1ZM9 13h6v6H9ZM17 5h6v6h-6Z',
 chart:'M4 3v17h17M8 15v-4m5 4V6m5 9v-7',
 chevron:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6',close:'m6 6 12 12M18 6 6 18',
 plus:'M12 5v14M5 12h14',undo:'M8 3 3 8l5 5M3 8h10a7 7 0 0 1 0 14',
 link:'m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l6-6a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-6 6a4 4 0 0 1-6 0',
 route:'M5 5h11a3 3 0 0 1 0 6H8a3 3 0 0 0 0 6h11M16 14l3 3-3 3',
 shield:'m12 2 9 4v7c0 5-9 9-9 9s-9-4-9-9V6ZM8 12l3 3 5-6',
 info:'M12 11v6M12 7h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 rocket:'M12 15 9 12c0-4 6-9 12-9 0 6-5 12-9 12ZM9 9H5l-3 6h7m6 0v4l-6 3v-7M16 8h.01M6 18l-3 3',
 grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',
 sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',
 moon:'M20 15a9 9 0 0 1-11-11 9 9 0 1 0 11 11Z',
 more:'M5 12h.01M12 12h.01M19 12h.01',refresh:'M20 7a9 9 0 1 0 1 8M20 2v6h-6',
 trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',
 arrow:'M4 12h16m-6-6 6 6-6 6',search:'M11 3a8 8 0 1 0 0 16 8 8 0 0 0 0-16ZM17 17l5 5',
 edit:'m16 3 5 5-12 12-6 1 1-6ZM13 6l5 5',stop:'M5 5h14v14H5Z'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.file}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,act,style='',ico='',attrs='')=>`<button class="button ${style}" data-act="${act}" ${attrs}>${ico?icon(ico):''}${label}</button>`;
const tabs=[['data','資料','folder'],['marks','標記','paint'],['settings','設定','sliders'],['results','結果','chart']];
const root=document.getElementById('app'),modal=document.getElementById('modal');
let jobs=[],job,tab='data',selection=new Set(),search='',regionFilter='',markFilter='all',shown=60,expanded=new Set(),undoStack=[],busy=false,solver=null,solverTimer,saveTimer,saveChain=Promise.resolve(),saveState='尚未儲存',offlineReady=false,importer=null,importData=null,toastTimer;
function blankJob(name='未命名卡夾'){return {schema:1,id:crypto.randomUUID(),name,sourceName:'',sheet:'',plant:'ARO1',rows:[],settings:{...DEFAULT_SETTINGS},remotes:[],overrides:{},result:null,revision:0,updated:new Date().toISOString(),demo:false};}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
function ensureIdle(){if(busy)throw new Error('正在試排。請先按「取消」，再修改資料。');}
function snapshot(){undoStack.push(structuredClone(job));if(undoStack.length>12)undoStack.shift();}
function changed(){job.revision++;job.updated=new Date().toISOString();saveSoon();}
function saveSoon(){saveState='正在儲存';clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(),300);}
async function persist(){const copy=structuredClone(job);saveChain=saveChain.catch(()=>{}).then(()=>saveJob(copy));try{await saveChain;const index=jobs.findIndex(x=>x.id===copy.id);if(index<0)jobs.push(copy);else jobs[index]=copy;try{localStorage.setItem('log-active',copy.id);}catch{}saveState='已存於此裝置';}catch{saveState='未能儲存';toast('此裝置無法保存卡夾。請先匯出卡夾，避免關閉後遺失。');}document.querySelectorAll('[data-save]').forEach(el=>el.textContent=saveState);}
function showModal(title,html){modal.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-act="close-modal" aria-label="關閉視窗">${icon('close')}</button></div><div class="modal-body">${html}</div>`;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();importer?.terminate();importer=null;importData=null;}
modal.addEventListener('cancel',()=>{importer?.terminate();importer=null;importData=null;});
function changeTab(next){tab=next;shown=60;render();window.scrollTo({top:0,behavior:'instant'});}
function resultCurrent(){return job.result?.ok&&job.result.revision===job.revision;}
function counts(){return {background:job.rows.filter(r=>r.background!=='none').length,floors:job.rows.filter(r=>r.floorMark).length,issues:job.rows.filter(r=>r.issues?.length).length};}
function remoteCount(){return Object.keys(remoteMap(job)).length;}
function render(){
 const title={data:job.rows.length?'這份工作，準備好了。':'把今天的工作帶著走。',marks:'點選、標記，就這麼簡單。',settings:'時間，照你的步調。',results:'看清楚每一筆時間。'}[tab];
 const subtitle={data:'匯入對照表，從一份資料開始。',marks:'先選元件，再套用顏色或遠距離加時。',settings:'起訖時間、檢測規則與遠距組合，各自管理。',results:'查看上午、下午與每筆間隔的組成。'}[tab];
 root.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark">L<span>•</span></span><div><div class="brand-title">LOG <span class="build-label">行動工作台</span></div><div class="brand-sub">YOUR FIELD WORKSPACE</div></div></div><div class="top-actions"><span class="status-pill"><i class="status-dot"></i><span data-save>${esc(saveState)}</span></span><button class="icon-button" data-act="help" aria-label="使用說明">${icon('info')}</button>${button('卡夾','shelf','light','folder')}</div></header>
 <main class="workspace"><div class="page-heading"><div><div class="eyebrow">${esc(job.plant)} / ${['data','marks','settings','results'].indexOf(tab)+1} OF 4</div><h1>${title}</h1><p>${subtitle}</p></div>${job.rows.length?button('匯出卡夾','backup','light desktop-only','download'):''}</div>
 <nav class="tabs" aria-label="工作流程">${tabs.map(([id,label,ico],i)=>`<button class="tab ${tab===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${tab===id?'page':'false'}"><span class="step">0${i+1}</span>${icon(ico)}${label}</button>`).join('')}</nav>
 <div class="layout"><section class="main-col">${tab==='data'?dataView():tab==='marks'?marksView():tab==='settings'?settingsView():resultsView()}</section><aside class="aside">${asideView()}</aside></div>
 <div class="privacy-foot">${icon('shield')}檔案在裝置內處理 · ${offlineReady?'離線資源已備妥':'首次開啟需要網路'} · 手機試用版</div></main>
 <nav class="mobile-nav" aria-label="工作流程">${tabs.map(([id,label,ico])=>`<button class="nav-item ${tab===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${tab===id?'page':'false'}">${icon(ico)}<span>${label}</span></button>`).join('')}</nav>
 <input type="file" id="source-file" class="file-input" accept=".xlsx,.xlsm"><input type="file" id="project-file" class="file-input" accept=".json,application/json">`;
 document.getElementById('source-file').onchange=event=>openWorkbook(event.target.files[0]);
 document.getElementById('project-file').onchange=event=>loadProject(event.target.files[0]);
}
function empty(title='先匯入一份資料',detail='匯入 XLSX 或載入示範，就能選取元件、標色與設定時間。'){return `<div class="card empty-state">${icon('folder')}<h2>${title}</h2><p>${detail}</p>${button('選擇檔案','import','primary','upload')} ${button('載入示範','demo','light')}</div>`;}
function sourceCard(){const c=counts();return `<div class="card"><div class="source-banner"><div class="source-icon">${icon('file')}</div><div class="source-info"><h2>${esc(job.name)}</h2><p>${esc(job.sourceName||'本機卡夾')} ${job.sheet?' · '+esc(job.sheet):''}</p><div class="flex small-gap wrap" style="margin-top:9px"><span class="tag">${esc(job.plant)}</span><span class="tag ${job.demo?'warn':'green'}">${job.demo?'合成示範資料':'原始碼完整保留'}</span></div></div><button class="icon-button" data-act="rename" aria-label="重新命名卡夾">${icon('edit')}</button></div><div class="stats-strip"><div><strong>${job.rows.length}</strong><span>元件</span></div><div><strong>${c.background}</strong><span>背景標記</span></div><div><strong>${c.issues}</strong><span>待確認解析</span></div></div></div>`;}
function dataView(){if(!job.rows.length)return `<div class="card import-card"><div class="copy"><h2>匯入你的對照表</h2><p>從手機「檔案」選擇 XLSX，挑選工作頁，就能開始整理。</p>${button('選擇 XLSX','import','primary','upload')}</div><div class="file-art" aria-hidden="true"><div class="art-sheet"><div class="art-lines"><i></i><i></i><i></i><i></i><i></i></div></div><span class="art-check">${icon('check')}</span></div></div><div class="demo-link">想先看看操作？ <button class="text-button" data-act="demo">載入示範卡夾 →</button></div><div class="flow-cards"><div class="flow-card"><div class="num">01 / IMPORT</div>${icon('folder')}<h3>挑選資料</h3><p>選廠別與工作頁<br>完整保留原始碼</p></div><div class="flow-card"><div class="num">02 / MARK</div>${icon('paint')}<h3>快速標記</h3><p>點選、多選小組<br>一按就能上色</p></div><div class="flow-card"><div class="num">03 / PLAN</div>${icon('clock')}<h3>安排時間</h3><p>設定上午與下午<br>逐筆查看試排結果</p></div></div><div class="quiet-note">你的卡夾保存在這台裝置。要換手機或保留副本，可以匯出卡夾後再匯入。</div>`;
 return sourceCard()+`${counts().issues?`<div class="notice" style="margin-top:16px">有 ${counts().issues} 筆解析需要確認。點開元件可修改設備、區域、樓層與小組，原始 D/E 保持原文。</div>`:''}`+filters()+rowList(false)+`<div class="sticky-actions">${button('前往標記','to-marks','primary','paint')}${button('匯入另一份','import','light','upload')}</div>`;
}
function filtered(){const text=search.toLowerCase();return job.rows.filter(r=>(!text||[r.d,r.e,r.region,r.equipment,r.group,r.form].some(v=>String(v).toLowerCase().includes(text)))&&(!regionFilter||r.region===regionFilter)&&(markFilter==='all'||(markFilter==='marked'&&r.background!=='none')||(markFilter==='issues'&&r.issues?.length)));}
function filters(){const regions=[...new Set(job.rows.map(r=>r.region).filter(Boolean))];return `<div class="filter-bar"><input id="search" type="text" placeholder="搜尋元件、設備或小組" aria-label="搜尋資料" value="${esc(search)}"><select id="region-filter" aria-label="區域篩選"><option value="">全部區域</option>${regions.map(r=>`<option ${regionFilter===r?'selected':''} value="${esc(r)}">${esc(r)}</option>`).join('')}</select><select id="mark-filter" aria-label="標記篩選"><option value="all" ${markFilter==='all'?'selected':''}>全部元件</option><option value="marked" ${markFilter==='marked'?'selected':''}>有底色</option><option value="issues" ${markFilter==='issues'?'selected':''}>待確認</option></select></div>`;}
function rowList(selectable,resultRows=null){const visible=filtered(),lookup=new Map((resultRows||[]).map(r=>[r.id,r]));return `<div class="selection-line"><span id="filter-count">${visible.length} 筆${selectable?' · 已選 '+selection.size+' 筆':''}</span>${selectable?`<div class="selection-actions"><button data-act="select-filter">選全部篩選</button><button data-act="select-group" ${selection.size?'':'disabled'}>同小組</button><button data-act="deselect">清除選取</button></div>`:''}</div><div class="row-list" id="row-list">${visible.slice(0,shown).map(r=>rowHtml(lookup.get(r.id)||r,selectable)).join('')||'<div class="empty-state">沒有符合篩選的元件。</div>'}</div>${visible.length>shown?button(`再顯示 ${Math.min(60,visible.length-shown)} 筆`,'more','light more-rows'):''}`;}
function rowHtml(r,selectable){const remote=remoteMap(job)[r.id];return `<article class="data-row bg-${esc(r.background)} ${r.floorMark?'floor-mark':''} ${r.extraMark?'extra-mark':''} ${selection.has(r.id)?'selected':''}"><div class="row-main" data-act="${selectable?'select':'expand'}" data-id="${esc(r.id)}" ${selectable?'':`role="button" tabindex="0" aria-expanded="${expanded.has(r.id)}"`}>
 ${selectable?`<input type="checkbox" aria-label="選取第 ${job.rows.findIndex(x=>x.id===r.id)+1} 筆 ${esc(r.d)}" ${selection.has(r.id)?'checked':''}>`:''}<span class="row-no">${String(job.rows.findIndex(x=>x.id===r.id)+1).padStart(2,'0')}</span><div class="row-content"><div class="row-code">${esc(r.d||r.e)}</div><div class="row-meta"><span>${esc(r.equipment||'設備待確認')}</span><span>·</span><span>${r.floor!=null?esc(r.floor)+'F':'樓層待確認'}</span><span>· ${esc(r.region||'區域待確認')}</span>${r.background!=='none'?`<span class="tag ${r.background}">${{yellow:'黃底',red:'跨區',blue:'自動補色'}[r.background]}</span>`:''}${r.floorMark?'<span class="tag red">樓層</span>':''}${r.extraMark?'<span class="tag warn">加時字</span>':''}${remote?`<span class="tag remote-chip">遠距 +${formatDuration(remote.min)}起</span>`:''}${r.issues?.length?'<span class="tag warn">待確認</span>':''}</div></div>${Number.isInteger(r.time)?`<div class="row-time"><strong>${formatClock(r.time)}</strong><small>+${formatDuration(r.interval)}</small></div>`:`<button class="icon-button" data-act="expand" data-id="${esc(r.id)}" aria-label="查看元件詳情">${icon('more')}</button>`}</div>
 ${expanded.has(r.id)?`<div class="row-detail"><dl><dt>D 元件編號</dt><dd>${esc(r.d)}</dd><dt>E 設備原碼</dt><dd>${esc(r.e)}</dd><dt>小組 / 型式</dt><dd>${esc(r.group||'待確認')} / ${esc(r.form||'無')}</dd>${r.parts?`<dt>間隔組成</dt><dd>${esc(Array.isArray(r.parts)?r.parts.join('；'):JSON.stringify(r.parts))}</dd>`:''}${remote?`<dt>遠距加時</dt><dd>${esc(remote.name)} · ${formatDuration(remote.min)}～${formatDuration(remote.max)}</dd>`:''}</dl>${r.issues?.length?`<p class="notice" style="margin-top:10px">${r.issues.map(esc).join('；')}</p>`:''}<div class="flex wrap">${button('修正解析','edit-row','light small','edit',`data-id="${esc(r.id)}"`)}${button('單筆遠距','edit-distance','light small','route',`data-id="${esc(r.id)}"`)}</div></div>`:''}</article>`;}
function palette(){return `<div class="palette"><div class="caption">已選 <strong>${selection.size}</strong> 筆 · 套用到 E 設備欄的標記</div><div class="palette-buttons">${[['yellow','黃底',''],['red','紅底',''],['floor','樓層紅字','F'],['extra','加時黃字','+'],['clear','清除標記','×']].map(([type,label,letter])=>`<button class="paint paint-${type}" data-act="paint" data-color="${type}" ${selection.size&&!busy?'':'disabled'}><span class="swatch">${letter}</span>${label}</button>`).join('')}</div><div class="palette-footer"><button data-act="undo" ${undoStack.length?'':'disabled'}>↶ 復原</button><button data-act="remote-add" ${selection.size?'':'disabled'}>＋ 加入遠距組合</button></div></div>`;}
function marksView(){if(!job.rows.length)return empty();return `${sourceCard()}<div class="mobile-generate desktop-hide">${button('自動辨識標色','autocolor','light','paint')}${button('時間設定','to-settings','primary','clock')}</div>${filters()}${rowList(true)}<div class="mobile-tools">${palette()}</div>`;}
function field(label,key,type='clock',value=job.settings[key]){return `<div class="field"><label for="setting-${key}">${label}</label><input id="setting-${key}" type="text" inputmode="${type==='clock'?'numeric':'decimal'}" data-setting="${key}" data-kind="${type}" value="${esc(type==='duration'?formatDuration(value):value)}" autocomplete="off" spellcheck="false"></div>`;}
function segment(key,options){return `<div class="segmented">${options.map(([v,label])=>`<button class="segment ${job.settings[key]===v?'active':''}" data-act="setting-choice" data-key="${key}" data-value="${v}" aria-pressed="${job.settings[key]===v}">${label}</button>`).join('')}</div>`;}
function settingsView(){return `<div class="stack settings-main"><div class="card"><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('sun')}</span><div><h3>上午時段</h3><p>可直接輸入 0820，或 08:20</p></div></div><div class="time-range">${field('開始','amStart')}<span class="time-arrow">→</span>${field('截止','amEnd')}</div></div><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('moon')}</span><div><h3>下午時段</h3><p>下午從 1F 重新出發</p></div></div><div class="time-range">${field('開始','pmStart')}<span class="time-arrow">→</span>${field('截止','pmEnd')}</div></div></div>
 <div class="card settings-section"><div class="section-title"><span class="section-icon">${icon('sliders')}</span><h3>檢測規則</h3></div><div class="setting-row"><div class="left"><h3>檢測難度</h3><p>黃底 ${job.settings.difficulty==='hard'?'2:31～3:10':'1:31～2:10'}，樓層與特殊另加</p></div>${segment('difficulty',[['normal','一般'],['hard','難']])}</div><div class="setting-row"><div class="left"><h3>80 顆驗證</h3><p>廠外仍保留其他時間規則</p></div>${segment('mode',[['auto','Auto'],['outdoor','廠外']])}</div>
 <details class="details-panel"><summary>首筆進場、收尾與跨區</summary><h3 class="settings-title">首筆進場等待 · 分:秒</h3><div class="fields">${field('下限','entryMin','duration')}${field('上限','entryMax','duration')}</div><h3 class="settings-title">上午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','amEarlyMin','duration')}${field('最多提前','amEarlyMax','duration')}</div><h3 class="settings-title">下午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','pmEarlyMin','duration')}${field('最多提前','pmEarlyMax','duration')}</div><h3 class="settings-title">跨區額外加時 · 分:秒</h3><div class="fields">${field('下限','crossMin','duration')}${field('上限','crossMax','duration')}</div></details>
 <details class="details-panel"><summary>普通間隔範圍</summary><div class="info-note">這版把「基礎＋差值」顯示為實際秒數範圍。設定只影響本卡夾，不會更改 Excel。</div><div class="fields" style="margin-top:14px">${field('一般下限（秒）','normalMin','seconds')}${field('一般上限（秒）','normalMax','seconds')}${field('難檢下限（秒）','hardMin','seconds')}${field('難檢上限（秒）','hardMax','seconds')}</div></details></div>
 <div class="card settings-section"><div class="card-head"><div class="card-label">${icon('route')}<h3>遠距組合</h3></div>${button('新增','remote-add','light small','plus')}</div><p class="inline-hint" style="margin-bottom:16px">先在「標記」選元件，再加入組合。單筆可另外設定；遠距加在原有間隔上。</p>${remoteCards()}</div>
 <div class="notice">手機版目前提供規則試排；尚未完成與 2027-10 全部案例的對照驗收，正式 TXT 暫不開放。</div>${button(busy?'正在試排…':'依設定試排全天','generate','primary w100','rocket',busy?'disabled':'')}${busy?button('取消本次試排','cancel','light w100','stop'):''}</div>`;}
function remoteCards(){return job.remotes.length?job.remotes.map(g=>`<div class="remote-card"><div class="flex between"><div><h3>${esc(g.name)}</h3><p class="meta">${g.rowIds.length} 筆 · 額外 +${formatDuration(g.min)}～${formatDuration(g.max)}</p></div><button class="icon-button" data-act="remote-edit" data-id="${esc(g.id)}" aria-label="編輯 ${esc(g.name)}">${icon('edit')}</button></div><div class="flex wrap">${button('查看成員','remote-members','light small','grid',`data-id="${esc(g.id)}"`)}${button('加入所選','remote-append','light small','plus',`data-id="${esc(g.id)}" ${selection.size?'':'disabled'}`)}</div></div>`).join(''):'<div class="info-note">尚未建立組合。可把 T 區黃底一次選好，設定例如 2:20～4:00。</div>';}
function resultsView(){if(busy)return `<div class="card card-pad"><div class="card-label">${icon('refresh','loading-icon')}<h2>正在裝置內試排</h2></div><p class="quiet-note">檢查完整小組切點、上下樓、特殊加時與起訖時間。</p><div class="progress-bar"><i></i></div>${button('取消本次試排','cancel','light w100','stop')}</div>`;
 const result=job.result;if(!result)return empty('讓設定變成看得見的時間','資料與標記完成後，按「試排全天」。第一版會逐筆列出間隔與規則檢查。')+`<div class="sticky-actions">${button('試排全天','generate','primary','rocket',job.rows.length?'':'disabled')}${button('調整設定','to-settings','light','sliders')}</div>`;
 const stale=result.revision!==job.revision;
 if(!result.ok)return `<div class="notice error"><strong>這次尚未排出結果</strong><p>來源與標記都保留。這是第一版搜尋結果，不代表這份資料一定無解。</p><ul>${(result.errors||result.checks?.filter(c=>!c.ok).map(c=>c.detail)||[]).slice(0,5).map(e=>`<li>${esc(e)}</li>`).join('')}</ul></div><div class="sticky-actions">${button('回設定調整','to-settings','primary','sliders')}${button('重新試排','generate','light','refresh')}</div>`;
 const r=result.summary;return `${stale?'<div class="notice" style="margin-bottom:16px">設定或標記已變動。以下是舊結果，請重新試排；目前不提供匯出。</div>':'<div class="notice good" style="margin-bottom:16px"><strong>本版規則檢查完成</strong> · 試排結果，尚非 Excel 正式驗收。</div>'}<div class="stat-grid"><div class="result-stat"><span>上午 · ${r.amCount} 筆</span><strong>${r.amReturn!=null?formatClock(r.amReturn):'—'}</strong><small>返回 1F 的時間</small></div><div class="result-stat"><span>下午 · ${r.pmCount} 筆</span><strong>${r.pmReturn!=null?formatClock(r.pmReturn):'—'}</strong><small>返回 1F 的時間</small></div></div><div class="card card-pad"><h3>檢查紀錄</h3>${(result.checks||[]).map(c=>`<div class="check-row ${c.ok?'':'fail'}">${icon(c.ok?'check':'info')}<div><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div></div>`).join('')}<p class="inline-hint">${(result.warnings||[]).map(esc).join(' ')}</p></div><div class="sticky-actions">${button('匯出試排 CSV','export-csv','primary','download',stale?'disabled':'')}${button('重新試排','generate','light','refresh')}</div>${filters()}${rowList(false,result.rows)}`;
}
function asideView(){if(tab==='marks'&&job.rows.length)return palette()+`<div class="card card-pad"><h3>先自動，再微調</h3><p class="quiet-note">依設備、樓層與區域辨識標色。你已經手動標記的地方會保留。</p><div class="side-footer">${button('自動辨識標色','autocolor','light w100','paint')}</div></div>`;
 return `<div class="card card-pad"><div class="card-head"><h3>本次工作</h3><span class="tag">本機卡夾</span></div><p style="font-size:14px;font-weight:650;overflow-wrap:anywhere">${esc(job.name)}</p><div class="mini-stat"><span>廠別</span><strong>${esc(job.plant)}</strong></div><div class="mini-stat"><span>元件數</span><strong>${job.rows.length} 筆</strong></div><div class="mini-stat"><span>上午</span><strong>${esc(job.settings.amStart)}—${esc(job.settings.amEnd)}</strong></div><div class="mini-stat"><span>下午</span><strong>${esc(job.settings.pmStart)}—${esc(job.settings.pmEnd)}</strong></div><div class="mini-stat"><span>遠距組合</span><strong>${remoteCount()} 筆</strong></div><div class="side-footer">${button(busy?'正在試排…':'試排全天','generate','primary w100','rocket',job.rows.length&&!busy?'':'disabled')}${busy?button('取消','cancel','light w100','stop'):''}<p class="inline-hint">試排核心尚未與 Excel 完整對照。正式輸出仍使用現有工作簿。</p></div></div><div class="info-note"><div class="flex" style="margin-bottom:7px">${icon('shield')}<strong>只在你的裝置內</strong></div>卡夾、標記與時間不會上傳。記得匯出卡夾，可在另一台裝置接續。</div>`;
}

function selectRow(id){if(selection.has(id))selection.delete(id);else selection.add(id);render();}
function applyColor(color){ensureIdle();if(!selection.size)return;snapshot();for(const r of job.rows)if(selection.has(r.id)){if(['yellow','red'].includes(color))r.background=color;else if(color==='floor'){r.floorMark=true;if(r.background==='none')r.background='yellow';}else if(color==='extra')r.extraMark=true;else{r.background='none';r.floorMark=false;r.extraMark=false;}}changed();render();toast(`已套用到 ${selection.size} 筆，可按復原。`);}
function editRow(id){const r=job.rows.find(x=>x.id===id);showModal('確認解析',`<p>D／E 原始字串不會更動。此處修改的是本卡夾的解析結果。</p><div class="sample-preview">D：${esc(r.d)}<br>E：${esc(r.e)}</div><form id="edit-row-form" data-id="${esc(id)}"><div class="fields">${[['region','區域',r.region],['equipment','設備',r.equipment],['floor','樓層（數字）',r.floor??''],['group','小組',r.group],['form','型式',r.form]].map(([key,label,v])=>`<div class="field"><label for="row-${key}">${label}</label><input id="row-${key}" name="${key}" value="${esc(v)}" ${key==='floor'?'inputmode="numeric"':''} maxlength="100"></div>`).join('')}</div><button class="button primary w100" type="submit">套用解析</button></form>`);}
function remoteDialog(id=null){const existing=job.remotes.find(g=>g.id===id);if(!existing&&!selection.size){toast('先到標記頁選取元件，再加入遠距組合。');changeTab('marks');return;}const g=existing||{name:`遠距組合 ${job.remotes.length+1}`,min:140,max:240,rowIds:[...selection]};showModal(existing?'編輯遠距組合':'建立遠距組合',`<p>共 ${g.rowIds.length} 筆。時間額外加在原本間隔上，背景、樓層與特殊照常計算。</p><form id="remote-form" data-id="${id||''}"><div class="field"><label for="remote-name">組合名稱</label><input id="remote-name" name="name" value="${esc(g.name)}" maxlength="60" required></div><div class="fields"><div class="field"><label for="remote-min">下限 · 分:秒</label><input id="remote-min" name="min" inputmode="decimal" value="${formatDuration(g.min)}" required></div><div class="field"><label for="remote-max">上限 · 分:秒</label><input id="remote-max" name="max" inputmode="decimal" value="${formatDuration(g.max)}" required></div></div><p class="inline-hint">已有單筆覆寫的元件，會保留自己的時間。</p><div class="foot-actions">${existing?button('刪除組合','remote-delete','danger','trash',`data-id="${id}" type="button"`):''}<button class="button primary" type="submit">${existing?'儲存組合':'加入組合'}</button></div></form>`);}
function singleRemote(id){const r=job.rows.find(x=>x.id===id),remote=remoteMap(job)[id]||{min:140,max:240};showModal('單筆遠距加時',`<p>${esc(r.d)}<br>只改這一筆，其他組合成員維持原時間。</p><form id="single-remote-form" data-id="${esc(id)}"><div class="fields"><div class="field"><label for="single-min">下限 · 分:秒</label><input id="single-min" name="min" inputmode="decimal" value="${formatDuration(remote.min)}"></div><div class="field"><label for="single-max">上限 · 分:秒</label><input id="single-max" name="max" inputmode="decimal" value="${formatDuration(remote.max)}"></div></div><div class="foot-actions">${button('恢復組合時間','remote-reset','light','undo',`data-id="${esc(id)}" type="button"`)}<button class="button primary" type="submit">套用單筆</button></div></form>`);}
async function shelf(){await persist();showModal('我的卡夾',`<p>卡夾保留在這台裝置；透過匯出、匯入帶到另一台。</p>${jobs.sort((a,b)=>b.updated.localeCompare(a.updated)).map(j=>`<button class="job-card ${j.id===job.id?'active':''}" data-act="load-job" data-id="${esc(j.id)}"><div><strong>${esc(j.name)}</strong><p>${esc(j.plant)} · ${j.rows.length} 筆 · ${new Date(j.updated).toLocaleDateString('zh-TW')}</p></div>${icon('chevron')}</button>`).join('')}<div class="shelf-tools">${button('新增空白卡夾','new-job','primary','plus')}${button('匯入卡夾','restore','light','upload')}${button('匯出目前','backup','light','download')}</div>${button('刪除目前卡夾','delete-job','ghost small','trash','style="margin-top:18px"')}`);}
async function openWorkbook(file){if(!file)return;try{ensureIdle();if(file.size>20*1024*1024)throw new Error('檔案超過 20 MB，請先另存需要的工作頁。');showModal('讀取工作頁',`<p>${esc(file.name)}</p><div class="progress-bar"><i></i></div><p>只在本機讀取，不會執行活頁簿的巨集。</p>`);const token=crypto.randomUUID();importData={token,fileName:file.name,rows:[],sheets:[]};importer?.terminate();importer=new Worker('./import-worker.js');importer.onerror=()=>{toast('活頁簿讀取失敗，請重新選擇。');closeModal();};importer.onmessage=({data})=>{if(importData?.token!==token)return;if(data.type==='error'){toast(data.message);closeModal();return;}if(data.type==='sheets'){importData.sheets=data.sheets;importData.visibility=data.visibility;importDialog();requestSheet();}if(data.type==='rows'){if(data.requestId!==importData.requestId)return;importData.rows=data.rows;const box=document.getElementById('import-preview');if(box)box.innerHTML=data.rows.slice(0,3).map(r=>`<p>B：${esc(r.b)}<br>C：${esc(r.c)}</p>`).join('')||'選取的範圍沒有 B／C 資料。';const c=document.getElementById('import-count');if(c)c.textContent=`讀到 ${data.rows.length} 筆`;const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=!data.rows.length;}};const buffer=await file.arrayBuffer();if(importData?.token===token)importer.postMessage({action:'open',buffer},[buffer]);}catch(error){toast(error.message);}}
function importDialog(){const inferred=PLANTS.find(p=>p!=='示範廠'&&importData.fileName.includes(p))||job.plant;showModal('選擇匯入範圍',`<p>${esc(importData.fileName)}</p><div class="field" style="margin-bottom:12px"><label for="sheet-search">搜尋工作頁</label><input id="sheet-search" type="text" placeholder="份數、中文字或 (區域)"></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="show-hidden">顯示隱藏工作頁</label><div class="field"><label for="import-sheet">工作頁（完整原名）</label><select id="import-sheet">${sheetOptions()}</select></div><div class="fields three"><div class="field"><label for="import-start">從第幾列開始</label><input id="import-start" inputmode="numeric" type="number" min="1" max="100000" value="3"></div><div class="field"><label for="import-amount">最多幾筆</label><input id="import-amount" inputmode="numeric" type="number" min="1" max="448" value="400"></div><div class="field"><label for="import-plant">廠別</label><select id="import-plant">${PLANTS.filter(p=>p!=='示範廠').map(p=>`<option ${p===inferred?'selected':''}>${esc(p)}</option>`).join('')}</select></div></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="import-reverse">反轉此廠預設的 D／E 方向</label><div class="import-mapping" id="import-mapping">一般來源 B→D、C→E；油類使用廠別的反轉設定。</div><p class="inline-hint" id="import-count">讀取中…</p><div id="import-preview" class="sample-preview" style="margin-top:10px">準備預覽前三筆。</div><div class="foot-actions">${button('匯入新卡夾','accept-import','primary','arrow','disabled')}</div>`);}
function sheetOptions(query='',includeHidden=false){return (importData.visibility||importData.sheets.map(name=>({name,hidden:0}))).filter(s=>(includeHidden||!s.hidden)&&matchSheetName(s.name,query)).map(s=>`<option value="${esc(s.name)}">${esc(s.name)}${s.hidden===2?' · 深度隱藏':s.hidden?' · 隱藏':''}</option>`).join('');}
let sheetTimer;
function filterSheets(){const select=document.getElementById('import-sheet'),previous=select.value;select.innerHTML=sheetOptions(document.getElementById('sheet-search').value,document.getElementById('show-hidden').checked);if([...select.options].some(o=>o.value===previous)){select.value=previous;return;}importData.rows=[];importData.requestId=(importData.requestId||0)+1;document.querySelector('[data-act="accept-import"]').disabled=true;clearTimeout(sheetTimer);sheetTimer=setTimeout(()=>requestSheet(),250);}
function requestSheet(){if(!importer)return;const sheet=document.getElementById('import-sheet').value;importData.rows=[];const acceptButton=document.querySelector('[data-act="accept-import"]');if(acceptButton)acceptButton.disabled=true;if(!sheet){document.getElementById('import-preview').textContent='沒有符合條件的工作頁，可調整搜尋或顯示隱藏頁。';document.getElementById('import-count').textContent='0 筆';return;}const first=Number(document.getElementById('import-start')?.value),count=Number(document.getElementById('import-amount')?.value);if(!Number.isInteger(first)||first<1||first>100000||!Number.isInteger(count)||count<1||count>448){toast('起始列須為 1～100000，筆數須為 1～448。');return;}const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=true;importData.requestId=(importData.requestId||0)+1;document.getElementById('import-count').textContent='正在讀取所選頁面…';importer.postMessage({action:'sheet',name:sheet,first,count,requestId:importData.requestId});}
async function acceptImport(){ensureIdle();const plant=document.getElementById('import-plant').value,reverse=document.getElementById('import-reverse').checked,rows=parseRows(importData.rows,plant,reverse),sheet=document.getElementById('import-sheet').value;if(!rows.length)throw new Error('沒有資料可匯入。');const name=importData.fileName;await persist();job=blankJob(`${plant} · ${sheet}`);Object.assign(job,{sourceName:name,sheet,plant,rows});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];closeModal();await persist();changeTab('data');toast(`已匯入 ${rows.length} 筆。原有卡夾已保留。`);}
async function loadProject(file){if(!file)return;try{ensureIdle();if(file.size>5*1024*1024)throw new Error('卡夾大於 5 MB，無法匯入。');const data=validateProject(JSON.parse(await file.text()));const errors=validateSettings(data.settings);if(errors.length)throw new Error(errors.join('；'));await persist();job=data;selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');toast('卡夾已匯入；時間結果會重新驗算。');}catch(error){toast(error.message);}}
function download(content,name,mime='application/json'){const blob=new Blob([content],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
function backup(){download(JSON.stringify(job,null,2),`${job.name.replace(/[\\/:*?"<>|]/g,'_')}.log.json`);toast('卡夾已交給瀏覽器下載，手機可在「檔案」保留。');}
function exportCSV(){if(!resultCurrent())throw new Error('請先完成本次設定的試排。');const lines=[['試排資料（未完成 Excel 正式驗收）'],['序號','元件 D','設備原碼 E','設備','區域','樓層','小組','型式','時段','時間','間隔','背景','樓層標記','額外標記']];job.result.rows.forEach((r,i)=>lines.push([i+1,r.d,r.e,r.equipment,r.region,r.floor,r.group,r.form,r.period,formatClock(r.time),formatDuration(r.interval),r.background,r.floorMark,r.extraMark]));download('\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n',`${job.name.replace(/[\\/:*?"<>|]/g,'_')}-試排.csv`,'text/csv;charset=utf-8');}
async function generate(){ensureIdle();if(!job.rows.length)throw new Error('請先匯入資料。');const errors=validateSettings(job.settings);if(errors.length)throw new Error(errors.join('；'));busy=true;try{snapshot();job.rows=autocolor(job.rows);changed();tab='results';render();window.scrollTo({top:0,behavior:'instant'});await persist();if(!busy)return;solver=new Worker('./solver-worker.mjs',{type:'module'});}catch(error){busy=false;render();throw error;}const revision=job.revision;
 const finish=()=>{solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;};
 solver.onmessage=({data})=>{finish();if(data.type==='result'&&data.revision===job.revision){job.result={...data.result,revision};saveSoon();render();toast(data.result.ok?'試排完成，可點元件查看間隔組成。':'本次尚未找到方案，詳情已列出。');}else{render();toast(data.message||'資料已變動，結果未套用。');}};
 solver.onerror=()=>{finish();render();toast('試排器未能完成，原有資料與結果保留。');};
 solverTimer=setTimeout(()=>{finish();render();toast('本次試排超過 20 秒，已停止工作程序，原資料保留。');},20000);
 solver.postMessage({rows:job.rows,settings:job.settings,remoteMap:remoteMap(job),seed:crypto.getRandomValues(new Uint32Array(1))[0],revision});
}
function cancel(){solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;render();toast('已取消試排，資料與標記保留。');}
function help(){showModal('隨手可用的 LOG',`<div class="stack"><div><h3>上色怎麼做？</h3><p class="quiet-note">到標記頁點選元件。可選同小組或全部篩選結果，再按底部的顏色。樓層紅字會一起補黃底；已有紅底會保留。單純加時使用黃字。</p></div><div><h3>要自己打鍵盤嗎？</h3><p class="quiet-note">使用手機原生鍵盤。時刻可以輸入 0820 或 13:06；等待和遠距可以輸入 2:20、3 或 3.5 分鐘。</p></div><div><h3>如何放到主畫面？</h3><p class="quiet-note">iPhone：用 Safari 開啟，按分享 → 加入主畫面。Android：在瀏覽器選安裝應用程式。首次連線並完成離線資源準備後，可離線開啟。</p></div><div class="notice"><strong>目前是手機第一版</strong><br>可匯入、標色、編輯解析、存卡夾與規則試排。尚未完成 -10 全廠解析、完整求解與 1000／2020 TXT 對照；正式作業仍以 Excel 為準。</div><p class="inline-hint">不需要 Excel、外掛 EXE 或 API 金鑰。清除網站資料會移除本機卡夾，請先匯出備份。</p></div>`);}

async function action(name,el){
 const mutating=['paint','undo','autocolor','remote-add','remote-edit','remote-append','remote-delete','remote-reset','edit-row','edit-distance','setting-choice','new-job','delete-job','load-job','demo','rename','import','restore'];if(mutating.includes(name))ensureIdle();
 const id=el.dataset.id;
 switch(name){
 case 'tab':changeTab(el.dataset.tab);break;
 case 'to-marks':changeTab('marks');break;case 'to-settings':changeTab('settings');break;
 case 'close-modal':closeModal();break;case 'help':help();break;
 case 'import':document.getElementById('source-file').click();break;
 case 'restore':closeModal();document.getElementById('project-file').click();break;
 case 'accept-import':await acceptImport();break;
 case 'demo':{await persist();const demo=makeDemo();job=blankJob(demo.name);Object.assign(job,demo,{demo:true});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];await persist();changeTab('data');toast('這是合成資料，可放心試標記。');break;}
 case 'select':selectRow(id);break;
 case 'expand':expanded.has(id)?expanded.delete(id):expanded.add(id);render();break;
 case 'select-filter':filtered().forEach(r=>selection.add(r.id));render();break;
 case 'select-group':{const keys=new Set(job.rows.filter(r=>selection.has(r.id)).map(r=>[r.region,r.equipment,r.group].join('|')));job.rows.forEach(r=>{if(r.group&&keys.has([r.region,r.equipment,r.group].join('|')))selection.add(r.id);});render();break;}
 case 'deselect':selection.clear();render();break;
 case 'more':shown+=60;render();break;
 case 'paint':applyColor(el.dataset.color);break;
 case 'undo':if(undoStack.length){job=undoStack.pop();saveSoon();render();toast('已復原前一步。');}break;
 case 'autocolor':snapshot();job.rows=autocolor(job.rows);changed();render();toast('已依設備、樓層、區域檢查標記。');break;
 case 'setting-choice':snapshot();job.settings[el.dataset.key]=el.dataset.value;changed();render();break;
 case 'edit-row':editRow(id);break;case 'edit-distance':singleRemote(id);break;
 case 'remote-add':remoteDialog();break;case 'remote-edit':remoteDialog(id);break;
 case 'remote-members':{const g=job.remotes.find(x=>x.id===id);showModal(esc(g.name),`<p>${g.rowIds.length} 筆 · 點「單筆遠距」可覆寫其中一筆。</p>${g.rowIds.map(rid=>{const r=job.rows.find(x=>x.id===rid),m=remoteMap(job)[rid];return `<div class="job-card"><div><strong>${esc(r.d)}</strong><p>+${formatDuration(m.min)}～${formatDuration(m.max)}${job.overrides[rid]?' · 單筆覆寫':''}</p></div>${button('單筆','edit-distance','light small','',`data-id="${rid}"`)}</div>`;}).join('')}`);break;}
 case 'remote-append':snapshot();for(const g of job.remotes)g.rowIds=g.rowIds.filter(rid=>!selection.has(rid));job.remotes.find(g=>g.id===id).rowIds.push(...selection);selection.clear();changed();render();toast('已加入組合；每筆只套一組遠距。');break;
 case 'remote-delete':if(confirm('移除這個遠距組合？單筆自訂仍會保留。')){snapshot();job.remotes=job.remotes.filter(g=>g.id!==id);changed();closeModal();render();}break;
 case 'remote-reset':snapshot();delete job.overrides[id];changed();closeModal();render();toast('已恢復組合時間。');break;
 case 'generate':await generate();break;case 'cancel':cancel();break;
 case 'shelf':await shelf();break;case 'backup':backup();break;case 'export-csv':exportCSV();break;
 case 'new-job':await persist();job=blankJob();selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');break;
 case 'load-job':await persist();job=structuredClone(jobs.find(j=>j.id===id));selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();changeTab('data');await persist();break;
 case 'delete-job':if(confirm(`只刪除此裝置的「${job.name}」卡夾？原始 XLSX 不會刪除。`)){clearTimeout(saveTimer);await saveChain.catch(()=>{});await removeJob(job.id);jobs=jobs.filter(j=>j.id!==job.id);job=jobs.length?structuredClone(jobs[0]):blankJob();selection.clear();undoStack=[];search='';regionFilter='';closeModal();await persist();changeTab('data');}break;
 case 'rename':showModal('卡夾名稱',`<form id="rename-form"><div class="field"><label for="job-name">方便你下次找到</label><input id="job-name" name="name" maxlength="100" required value="${esc(job.name)}"></div><div class="foot-actions"><button class="button primary" type="submit">儲存</button></div></form>`);break;
 }
}
let dispatchBusy=false;
document.addEventListener('click',event=>{const el=event.target.closest('[data-act]');if(!el||el.disabled)return;event.preventDefault();const exclusive=['demo','new-job','load-job','delete-job','accept-import','shelf'].includes(el.dataset.act);if(exclusive&&dispatchBusy)return;if(exclusive)dispatchBusy=true;action(el.dataset.act,el).catch(e=>toast(e.message)).finally(()=>{if(exclusive)dispatchBusy=false;});});
document.addEventListener('keydown',event=>{const el=event.target.closest('[role="button"][data-act]');if(el&&(event.key==='Enter'||event.key===' ')){event.preventDefault();action(el.dataset.act,el).catch(e=>toast(e.message));}});
document.addEventListener('input',event=>{if(event.target.id==='sheet-search'){filterSheets();return;}if(event.target.id==='search'){search=event.target.value;const focus=event.target.selectionStart;render();const input=document.getElementById('search');input.focus({preventScroll:true});input.setSelectionRange(focus,focus);}});
document.addEventListener('change',event=>{const el=event.target;try{
 if(el.id==='region-filter'){regionFilter=el.value;shown=60;render();}else if(el.id==='mark-filter'){markFilter=el.value;shown=60;render();}
 else if(['import-sheet','import-start','import-amount'].includes(el.id))requestSheet();else if(el.id==='show-hidden')filterSheets();
 else if(el.dataset.setting){ensureIdle();const key=el.dataset.setting;let value;if(el.dataset.kind==='clock')value=formatClock(parseClock(el.value)).slice(0,5);else if(el.dataset.kind==='duration')value=durationInput(el.value);else{value=Number(el.value);if(!Number.isInteger(value)||value<1||value>3600)throw new Error('秒數請填 1～3600 的整數。');}snapshot();job.settings[key]=value;changed();el.value=el.dataset.kind==='duration'?formatDuration(value):value;toast('設定已儲存，原結果需要重新試排。');}
 }catch(error){toast(error.message);if(el.dataset.setting){const v=job.settings[el.dataset.setting];el.value=el.dataset.kind==='duration'?formatDuration(v):v;}}
});
document.addEventListener('submit',event=>{event.preventDefault();try{ensureIdle();const form=event.target,fd=new FormData(form);if(form.id==='edit-row-form'){const floor=Number(fd.get('floor'));if(!Number.isInteger(floor)||floor<1||floor>99||!String(fd.get('region')).trim()||!String(fd.get('equipment')).trim()||!String(fd.get('group')).trim())throw new Error('請填區域、設備、小組，以及 1～99 的樓層。');snapshot();const row=job.rows.find(r=>r.id===form.dataset.id);for(const k of ['region','equipment','group','form'])row[k]=String(fd.get(k)).trim();row.floor=floor;row.issues=[];changed();closeModal();render();}
 else if(['remote-form','single-remote-form'].includes(form.id)){const min=durationInput(fd.get('min')),max=durationInput(fd.get('max'));if(min>max)throw new Error('下限不能大於上限。');snapshot();if(form.id==='single-remote-form')job.overrides[form.dataset.id]={min,max};else{const name=String(fd.get('name')).trim();if(!name)throw new Error('請填組合名稱。');const existing=job.remotes.find(g=>g.id===form.dataset.id);if(existing)Object.assign(existing,{name,min,max});else{for(const g of job.remotes)g.rowIds=g.rowIds.filter(id=>!selection.has(id));job.remotes.push({id:crypto.randomUUID(),name,min,max,rowIds:[...selection]});selection.clear();}}changed();closeModal();render();toast('遠距加時已儲存，重新試排才會套用。');}
 else if(form.id==='rename-form'){job.name=String(fd.get('name')).trim()||'未命名卡夾';job.updated=new Date().toISOString();saveSoon();closeModal();render();}
 }catch(error){toast(error.message);}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);persist();}});
window.addEventListener('pagehide',()=>{solver?.terminate();importer?.terminate();});
async function start(){try{jobs=await getJobs();let last;try{last=localStorage.getItem('log-active');}catch{}job=structuredClone(jobs.find(j=>j.id===last)||jobs.sort((a,b)=>b.updated.localeCompare(a.updated))[0]||blankJob());saveState=jobs.length?'已存於此裝置':'尚未儲存';}catch{job=blankJob();saveState='此瀏覽器無法儲存';}render();if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;offlineReady=true;document.querySelector('.privacy-foot').innerHTML=icon('shield')+'檔案在裝置內處理 · 離線資源已備妥 · 手機試用版';if(reg.waiting)toast('有新版程式。完成並匯出工作後，關閉所有工作台再開啟即可更新。');reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',()=>{if(reg.waiting)toast('新版已準備好，下次關閉再開啟時更新。');});});}catch{offlineReady=false;}}}
start();
