import {DEFAULT_SETTINGS,PLANTS,parseRows,makeDemo,autocolor,parseClock,formatClock,formatDuration,validateSettings,isSpecial,colorTimeGuide} from './domain.mjs';
import {saveJob,getJobs,removeJob,validateProject,remoteMap,durationInput,csvCell,matchSheetName} from './storage.mjs';
import {windowReport,backgroundReport} from './validation.mjs';
import {DEFAULT_MEASUREMENT_SETTINGS,normalizeMeasurementSettings,generateMeasurements,setSegmentA,setRowB} from './measurements.mjs';
import {resultIsCurrent,currentJobRows,reconcileMeasurements,storeMeasurements} from './job-rows.mjs';
import './version.js';
import {createUpdater,fetchReleaseVersion} from './update.mjs';

const icons={
 folder:'M3 7V5a1 1 0 0 1 1-1h5l2 3h9a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7Z',
 file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8M8 17h5',
 upload:'M12 16V3m-5 5 5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5',
 download:'M12 3v13m-5-5 5 5 5-5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4',
 paint:'m15 3 6 6-9 9-6-6ZM6 12l-3 3 6 6 3-3M4 3l10 10',
 clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 sliders:'M4 4v5m0 6v5m8-16v9m0 6v1m8-16v1m0 6v9M1 9h6v6H1ZM9 13h6v6H9ZM17 5h6v6h-6Z',
 chart:'M4 3v17h17M8 15v-4m5 4V6m5 9v-7',
 chevron:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6',close:'m6 6 12 12M18 6 6 18',
 plus:'M12 5v14M5 12h14',undo:'M8 3 3 8l5 5M3 8h10a7 7 0 0 1 0 14',
 link:'m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l6-6a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-6 6a4 4 0 0 1-6 0',
 route:'M5 5h11a3 3 0 0 1 0 6H8a3 3 0 0 0 0 6h11M16 14l3 3-3 3',
 shield:'m12 2 9 4v7c0 5-9 9-9 9s-9-4-9-9V6ZM8 12l3 3 5-6',
 info:'M12 11v6M12 7h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
 rocket:'M12 15 9 12c0-4 6-9 12-9 0 6-5 12-9 12ZM9 9H5l-3 6h7m6 0v4l-6 3v-7M16 8h.01M6 18l-3 3',
 grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',
 sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',
 moon:'M20 15a9 9 0 0 1-11-11 9 9 0 1 0 11 11Z',
 more:'M5 12h.01M12 12h.01M19 12h.01',refresh:'M20 7a9 9 0 1 0 1 8M20 2v6h-6',
 trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',
 arrow:'M4 12h16m-6-6 6 6-6 6',search:'M11 3a8 8 0 1 0 0 16 8 8 0 0 0 0-16ZM17 17l5 5',
 edit:'m16 3 5 5-12 12-6 1 1-6ZM13 6l5 5',stop:'M5 5h14v14H5Z'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.file}"/></svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,act,style='',ico='',attrs='')=>`<button class="button ${style}" data-act="${act}" ${attrs}>${ico?icon(ico):''}${label}</button>`;
const tabs=[['data','資料','folder'],['marks','標記','paint'],['settings','時間設定','sliders'],['results','結果','chart'],['measurements','A/B','edit']];
const root=document.getElementById('app'),modal=document.getElementById('modal');
let jobs=[],job,tab='data',selection=new Set(),search='',regionFilter='',markFilter='all',shown=60,expanded=new Set(),undoStack=[],busy=false,solver=null,solverTimer,saveTimer,saveChain=Promise.resolve(),saveState='尚未儲存',offlineReady=false,importer=null,importData=null,toastTimer;
let viewMode='table',showContext=false,paletteOpen=false,updater=null,deletingJob=false,updateIdle=true,rowObserver=null,showShortCode=false;
function blankJob(name='未命名卡夾'){return {schema:1,id:crypto.randomUUID(),name,sourceName:'',sheet:'',plant:'',rows:[],settings:{...DEFAULT_SETTINGS},measurementSettings:{...DEFAULT_MEASUREMENT_SETTINGS},remotes:[],overrides:{},result:null,revision:0,updated:new Date().toISOString(),demo:false};}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
function ensureIdle(){if(updater?.state==='applying')throw new Error('正在儲存並更新，請稍候。');if(busy)throw new Error('正在試排。請先按「取消」，再修改資料。');}
function snapshot(){undoStack.push(structuredClone(job));if(undoStack.length>12)undoStack.shift();}
function changed(){job.revision++;job.updated=new Date().toISOString();saveSoon();}
function saveSoon(){saveState='正在儲存';clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist(),300);}
async function persist(){
 if(deletingJob)return false;
 if(!job.rows.length&&!job.revision&&job.name==='未命名卡夾'&&!jobs.some(j=>j.id===job.id)){saveState='尚未匯入';try{localStorage.removeItem('log-active');}catch{}document.querySelectorAll('[data-save]').forEach(el=>el.textContent=saveState);return true;}
 const copy=structuredClone(job);saveChain=saveChain.catch(()=>{}).then(()=>saveJob(copy));let saved=false;
 try{await saveChain;const index=jobs.findIndex(x=>x.id===copy.id);if(index<0)jobs.push(copy);else jobs[index]=copy;try{localStorage.setItem('log-active',copy.id);}catch{}saveState='已存於此裝置';saved=true;}catch{saveState='未能儲存';toast('此裝置無法保存卡夾。請先匯出卡夾，避免關閉後遺失。');}
 document.querySelectorAll('[data-save]').forEach(el=>el.textContent=saveState);return saved;
}
function showModal(title,html,kind='editor'){modal.dataset.kind=kind;modal.innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="icon-button" data-act="close-modal" aria-label="關閉視窗">${icon('close')}</button></div><div class="modal-body">${html}</div>`;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();delete modal.dataset.kind;importer?.terminate();importer=null;importData=null;}
modal.addEventListener('cancel',()=>{delete modal.dataset.kind;importer?.terminate();importer=null;importData=null;});
function changeTab(next){tab=next;shown=60;render();window.scrollTo({top:0,behavior:'instant'});}
function rememberUi(){try{localStorage.setItem('log-row-view',viewMode);localStorage.setItem('log-filter-context',showContext?'1':'0');}catch{}}
function renderKeepScroll(){const x=window.scrollX,y=window.scrollY,positions=['row-list','result-list','measurement-list'].map(id=>({id,left:document.getElementById(id)?.scrollLeft||0,top:document.getElementById(id)?.scrollTop||0}));render();requestAnimationFrame(()=>{window.scrollTo({left:x,top:y,behavior:'instant'});for(const position of positions){const table=document.getElementById(position.id);if(table){table.scrollLeft=position.left;table.scrollTop=position.top;}}});}
function resultCurrent(){return resultIsCurrent(job);}
function counts(){const rows=currentJobRows(job);return {background:rows.filter(r=>r.background!=='none').length,floors:rows.filter(r=>r.floorMark).length,marked:rows.filter(r=>r.background!=='none'||r.floorMark||r.extraMark).length,issues:rows.filter(r=>r.issues?.length).length};}
function remoteCount(){return Object.keys(remoteMap(job)).length;}
function updateButton(){return `<button class="icon-button update-control" data-act="check-update" aria-label="檢查並更新" title="檢查並更新">${icon('refresh')}<span class="update-label">更新</span><span class="update-dot" hidden></span></button>`;}
function updaterInfo(){const info=updater?.info||{},current=info.currentVersion||globalThis.LOG_RELEASE?.version||'—',latest=info.latestVersion||'尚未取得';return {current,latest,released:globalThis.LOG_RELEASE?.released||'—',state:info.state||updater?.state||'idle',message:info.message||'可檢查是否有新版。',expected:info.expectedVersion||''};}
function infoHtml(){const info=updaterInfo();return `<div class="info-dialog" data-info-dialog><dl class="version-grid"><dt>目前版本</dt><dd data-info-current>${esc(info.current)}</dd><dt>線上版本</dt><dd data-info-latest>${esc(info.latest)}</dd><dt>發布日期</dt><dd>${esc(info.released)}</dd><dt>狀態</dt><dd data-info-state>${esc(info.message)}</dd></dl><p class="inline-hint">「更新」會先保存卡夾，再套用已下載的新版。若顯示需要再載入，按下方按鈕完成。</p><div class="foot-actions" data-info-actions>${info.state==='recovery'?button('儲存並重新載入','recover-update','primary','refresh'):button('檢查並更新','check-update','primary','refresh')}</div></div>`;}
function refreshInfoDialog(){if(!modal.open||modal.dataset.kind!=='info')return;const info=updaterInfo();modal.querySelector('[data-info-current]')?.replaceChildren(info.current);modal.querySelector('[data-info-latest]')?.replaceChildren(info.latest);modal.querySelector('[data-info-state]')?.replaceChildren(info.message);const actions=modal.querySelector('[data-info-actions]');if(actions)actions.innerHTML=info.state==='recovery'?button('儲存並重新載入','recover-update','primary','refresh'):button('檢查並更新','check-update','primary','refresh');}
function refreshUpdateState(){const state=updater?.state||'idle';refreshInfoDialog();document.querySelectorAll('[data-act="check-update"],[data-act="recover-update"]').forEach(el=>{const ready=state==='available',label={checking:'檢查中',downloading:'下載中',applying:'更新中',recovery:'再載入'}[state]||'更新';el.disabled=state==='applying';el.setAttribute('aria-label',state==='recovery'?'儲存並重新載入':ready?'立即更新':state==='applying'?'更新中':'檢查並更新');el.title=state==='recovery'?'完成新版載入':ready?'有新版，儲存後更新':label==='更新'?'檢查並更新':label;el.querySelector('.update-label')?.replaceChildren(label);const dot=el.querySelector('.update-dot');if(dot)dot.hidden=!(ready||state==='recovery');});offlineReady=updater?.hasOfflineShell||offlineReady;}
function render(){
 rowObserver?.disconnect();rowObserver=null;
 if(reconcileMeasurements(job))saveSoon();
 const title={data:'資料',marks:'標記',settings:'時間設定',results:'結果',measurements:'A/B 值',guide:'操作說明'}[tab];
 const subtitle={data:'匯入或檢視元件資料。',marks:'篩選、選取，再套用標記或遠距。',settings:'設定時段、規則與遠距組合。',results:'檢視試排時間與逐筆間隔。',measurements:'A 同底色段共用；B 逐筆填寫。',guide:`顏色與時間 · 目前${job.settings.difficulty==='hard'?'難檢':'一般'} · 分:秒`}[tab];
 root.innerHTML=`<header class="topbar"><div class="brand"><img class="brand-logo" src="./icon-192.png" alt="LOG"><div class="brand-title">LOG</div></div><div class="top-actions"><span class="status-pill"><i class="status-dot"></i><span data-save>${esc(saveState)}</span></span>${updateButton()}<button class="icon-button" data-act="help" aria-label="資訊">${icon('info')}</button>${button('卡夾','shelf','light','folder')}</div></header>
 <main class="workspace"><div class="page-heading"><div>${job.rows.length?`<div class="eyebrow">${esc(job.plant)}</div>`:''}<h1>${title}</h1><p>${subtitle}</p></div>${tab==='guide'?button('返回','guide-back','light','undo'):job.rows.length?button('匯出卡夾','backup','light desktop-only','download'):''}</div>
 <nav class="tabs" aria-label="工作流程">${tabs.map(([id,label,ico],i)=>`<button class="tab ${tab===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${tab===id?'page':'false'}"><span class="step">0${i+1}</span>${icon(ico)}${label}</button>`).join('')}</nav>
 <div class="layout ${['guide','measurements'].includes(tab)?'guide-layout':''}"><section class="main-col">${tab==='data'?dataView():tab==='marks'?marksView():tab==='settings'?settingsView():tab==='guide'?guideView():tab==='measurements'?measurementsView():resultsView()}</section>${['guide','measurements'].includes(tab)?'':`<aside class="aside">${asideView()}</aside>`}</div>
 </main>
 <nav class="mobile-nav" aria-label="工作流程">${tabs.map(([id,label,ico])=>`<button class="nav-item ${tab===id?'active':''}" data-act="tab" data-tab="${id}" aria-current="${tab===id?'page':'false'}">${icon(ico)}<span>${label}</span></button>`).join('')}</nav>
 <input type="file" id="source-file" class="file-input" accept=".xlsx,.xlsm"><input type="file" id="project-file" class="file-input" accept=".json,application/json">`;
 document.getElementById('source-file').onchange=event=>openWorkbook(event.target.files[0]);
 document.getElementById('project-file').onchange=event=>loadProject(event.target.files[0]);
 refreshUpdateState();
 setupCardObserver();
}
function empty(title='匯入資料',detail='選擇 XLSX，或載入合成示範資料。'){return `<div class="card empty-state">${icon('folder')}<h2>${title}</h2><p>${detail}</p>${button('選擇 XLSX','import','primary','upload')} ${button('載入示範','demo','light')}</div>`;}
function sourceCard(){const c=counts();return `<div class="card source-compact"><div class="source-banner"><div class="source-info"><h2>${esc(job.name)}</h2><p>${esc(job.plant)} · ${job.rows.length}筆 · ${c.marked}筆標記 · ${c.issues}筆待確認</p></div><button class="icon-button" data-act="rename" aria-label="重新命名卡夾">${icon('edit')}</button></div></div>`;}
function dataView(){if(!job.rows.length)return empty();return sourceCard()+`${counts().issues?`<div class="notice" style="margin-top:16px">有 ${counts().issues} 筆解析需要確認。可展開該列修正解析，原始 D／E 不會更動。</div>`:''}`+filters()+rowList(false)+`<div class="sticky-actions">${button('前往標記','to-marks','primary','paint')}${button('匯入另一份','import','light','upload')}</div>`;}
function matchesBase(r){const text=search.toLowerCase();return (!text||[r.d,r.e,r.region,r.equipment,r.group,r.form].some(v=>String(v??'').toLowerCase().includes(text)))&&(!regionFilter||r.region===regionFilter);}
function matchesMark(r){return markFilter==='all'||(markFilter==='yellow'&&r.background==='yellow')||(markFilter==='red'&&r.background==='red')||(markFilter==='blue'&&r.background==='blue')||(markFilter==='floor'&&r.floorMark)||(markFilter==='extra'&&r.extraMark)||(markFilter==='issues'&&r.issues?.length);}
function filtered(){return currentJobRows(job).filter(r=>matchesBase(r)&&matchesMark(r));}
function displayRows(){const rows=currentJobRows(job),matches=filtered(),matchIds=new Set(matches.map(r=>r.id));if(!showContext||markFilter==='all')return matches.map(row=>({row,context:false}));const indexes=new Set();rows.forEach((r,i)=>{if(matchIds.has(r.id)){indexes.add(i);if(i)indexes.add(i-1);if(i+1<rows.length)indexes.add(i+1);}});return [...indexes].sort((a,b)=>a-b).map(i=>({row:rows[i],context:!matchIds.has(rows[i].id)}));}
function filters(){const regions=[...new Set(job.rows.map(r=>r.region).filter(Boolean))];return `<div class="filter-bar"><input id="search" type="text" placeholder="搜尋編碼、設備或小組" aria-label="搜尋資料" value="${esc(search)}"><select id="region-filter" aria-label="區域篩選"><option value="">全部區域</option>${regions.map(r=>`<option ${regionFilter===r?'selected':''} value="${esc(r)}">${esc(r)}</option>`).join('')}</select><select id="mark-filter" aria-label="標記篩選">${[['all','全部'],['yellow','黃底'],['red','紅底'],['blue','藍底'],['floor','樓層'],['extra','加時'],['issues','待確認']].map(([value,label])=>`<option value="${value}" ${markFilter===value?'selected':''}>${label}</option>`).join('')}</select><label class="context-toggle"><input id="context-filter" type="checkbox" ${showContext?'checked':''} ${markFilter==='all'?'disabled':''}>保留前後1筆</label><div class="view-toggle" role="group" aria-label="資料檢視"><button class="${viewMode==='table'?'active':''}" data-act="view-mode" data-value="table" aria-pressed="${viewMode==='table'}">表格</button><button class="${viewMode==='cards'?'active':''}" data-act="view-mode" data-value="cards" aria-pressed="${viewMode==='cards'}">卡片</button></div></div>`;}
function rowList(selectable,resultRows=null,windowById={}){const matches=filtered(),entries=displayRows(),lookup=new Map((resultRows||[]).map(r=>[r.id,r])),backgrounds=backgroundReport(currentJobRows(job)).byId;const resolved=entries.map(({row,context})=>({row:lookup.get(row.id)||row,context})),more=resolved.length>shown;const cardMore=more?(typeof IntersectionObserver==='undefined'?button(`再顯示 ${Math.min(60,resolved.length-shown)} 筆`,'more','light more-rows'):'<div class="load-sentinel" data-more-sentinel aria-hidden="true"></div>'):'';const body=viewMode==='table'?tableRows(resolved,selectable,windowById,backgrounds):`<div class="row-list" id="row-list">${resolved.slice(0,shown).map(x=>rowHtml(x.row,selectable,x.context,windowById[x.row.id],backgrounds[x.row.id])).join('')||'<div class="empty-state">沒有符合篩選的元件。</div>'}</div>${cardMore}`;return `<div class="selection-line"><span id="filter-count">${matches.length} 筆${resolved.length!==matches.length?` · 含 ${resolved.length-matches.length} 筆情境`:''}${selectable?' · 已選 '+selection.size+' 筆':''}</span>${selectable?`<div class="selection-actions"><button data-act="select-filter">選取篩選結果</button><button data-act="select-group" ${selection.size?'':'disabled'}>同小組</button></div>`:''}</div>${body}`;}
function setupCardObserver(){const sentinel=document.querySelector('[data-more-sentinel]');if(!sentinel||typeof IntersectionObserver==='undefined')return;rowObserver=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;rowObserver?.disconnect();rowObserver=null;shown+=60;renderKeepScroll();},{rootMargin:'240px 0px'});rowObserver.observe(sentinel);}
function rowClasses(r,context=false){return `bg-${esc(r.background)} ${r.floorMark?'floor-mark':''} ${r.extraMark?'extra-mark':''} ${selection.has(r.id)?'selected':''} ${context?'context-row':''}`;}
function equipmentChange(r){const index=job.rows.findIndex(row=>row.id===r.id);if(index<=0)return '';const previous=job.rows[index-1],changed=String(previous.equipment??'')!==String(r.equipment??'');if(!changed)return '';return `<span class="tag equipment-change">換設備</span>${r.background==='none'?'<span class="tag missing-background">未標背景</span>':''}`;}
function intervalCell(value){if(!Number.isInteger(value))return '<span class="interval-empty">—</span>';return `<span class="interval-pill ${value>=91?'interval-alert':''}">${formatDuration(value)}</span>`;}
function formCell(row,empty='—'){const text=esc(row.form||empty);return isSpecial(row)?`<span class="special-form" title="特殊型式，自動加 1:00">${text}<small>+1:00</small></span>`:text;}
function detailHtml(r,windowInfo=null){const remote=remoteMap(job)[r.id];return `<div class="row-detail"><dl><dt>元件編號</dt><dd>${esc(r.d)}</dd><dt>設備原碼</dt><dd>${esc(r.e)}</dd><dt>小組 / 型式</dt><dd>${esc(r.group||'待確認')} / ${formCell(r,'無')}</dd>${windowInfo&&Number.isInteger(windowInfo.seconds)?`<dt>80窗時間</dt><dd>第 ${windowInfo.startRow}→${windowInfo.endRow} 筆 · ${formatDuration(windowInfo.seconds)}</dd>`:''}${r.parts?`<dt>間隔組成</dt><dd>${esc(Array.isArray(r.parts)?r.parts.join('；'):JSON.stringify(r.parts))}</dd>`:''}${remote?`<dt>遠距加時</dt><dd>${esc(remote.name)} · ${formatDuration(remote.min)}～${formatDuration(remote.max)}</dd>`:''}</dl>${r.issues?.length?`<p class="notice" style="margin-top:10px">${r.issues.map(esc).join('；')}</p>`:''}<div class="flex wrap">${button('修正解析','edit-row','light small','edit',`data-id="${esc(r.id)}"`)}${button('單筆遠距','edit-distance','light small','route',`data-id="${esc(r.id)}"`)}</div></div>`;}
function backgroundCell(info){return `<div class="background-counter ${info?.overLimit?'background-over':''}" title="${info?.total?`第 ${info.startRow}～${info.endRow} 筆；最多29筆`:'尚未設定背景段首'}"><small>本段筆數</small><strong>${info?.total?`${info.position}<span> / ${info.total}</span>`:'—'}</strong></div>`;}
function windowCell(info){if(!info||!Number.isInteger(info.minutes))return '<span class="window-empty" title="往後不足81點、跨午休或資料無效">—</span>';return `<span class="window-value window-${esc(info.status)}" title="第 ${info.startRow}→${info.endRow} 筆 · ${formatDuration(info.seconds)}">${info.minutes}</span>`;}
function rowHtml(r,selectable,context=false,windowInfo=null,backgroundInfo=null){const remote=remoteMap(job)[r.id],index=job.rows.findIndex(x=>x.id===r.id)+1,hasTime=Number.isInteger(r.time);return `<article class="data-row ${rowClasses(r,context)}"><div class="row-main" ${context?'':selectable?`data-act="select" data-id="${esc(r.id)}"`:`data-act="expand" data-id="${esc(r.id)}" role="button" tabindex="0" aria-label="展開第 ${index} 筆"`}>
 <span class="row-select">${selectable&&!context?`<input type="checkbox" aria-label="選取第 ${index} 筆 ${esc(r.e)}" ${selection.has(r.id)?'checked':''}>`:''}</span><span class="row-no">${String(index).padStart(2,'0')}</span><div class="row-content"><div class="row-code"><strong class="raw-e">${esc(r.e)}</strong><span class="raw-d">${esc(r.d)}</span></div><div class="row-meta"><strong class="equipment-name">${esc(r.equipment||'待確認')}</strong>${equipmentChange(r)}<span>${r.floor!=null?esc(r.floor)+'F':'待確認'}</span><span>${formCell(r,'無型式')}</span><span>${esc(r.group||'小組待確認')}</span>${context?'<span class="context-label">情境</span>':''}${r.background!=='none'?`<span class="tag ${r.background}">${{yellow:'黃底',red:'紅底',blue:'藍底'}[r.background]}</span>`:''}${r.floorMark?'<span class="tag red">樓層</span>':''}${r.extraMark?'<span class="tag warn">加時</span>':''}${remote?`<span class="tag remote-chip">遠距 +${formatDuration(remote.min)}起</span>`:''}${r.issues?.length?'<span class="tag warn">待確認</span>':''}</div></div><button class="row-detail-button" data-act="expand" data-id="${esc(r.id)}" aria-label="${expanded.has(r.id)?'收合':'查看'}第 ${index} 筆詳情" aria-expanded="${expanded.has(r.id)}">${icon('more')}</button><div class="row-metrics ${hasTime?'has-time':'marks-only'}">${hasTime?`<div class="row-time"><strong>${formatClock(r.time)}</strong><small>間隔 ${intervalCell(r.interval)}</small></div>`:''}${backgroundCell(backgroundInfo)}${hasTime?`<div class="window-metric"><small>80窗（分）</small>${windowCell(windowInfo)}</div>`:''}</div></div>${expanded.has(r.id)?detailHtml(r,windowInfo):''}</article>`;}
function tableRows(entries,selectable,windowById={},backgrounds={}){if(!entries.length)return '<div class="empty-state">沒有符合篩選的元件。</div>';return `<div class="table-scroll" id="row-list" tabindex="0" aria-label="資料表，可水平捲動"><table class="data-table"><thead><tr><th class="select-cell">${selectable?'選':''}</th><th>#</th><th class="e-head">設備原碼</th><th>元件編號</th><th>設備名稱</th><th>樓層</th><th>型式</th><th>小組</th><th>本段筆數</th><th>時間</th><th>間隔</th><th>80窗（分）</th><th>詳情</th></tr></thead><tbody>${entries.map(({row:r,context})=>{const index=job.rows.findIndex(x=>x.id===r.id)+1,info=windowById[r.id];return `<tr class="${rowClasses(r,context)}" ${context?'':selectable?`data-act="select" data-id="${esc(r.id)}"`:`data-act="expand" data-id="${esc(r.id)}" tabindex="0" aria-label="展開第 ${index} 筆"`}><td class="select-cell">${selectable&&!context?`<input type="checkbox" aria-label="選取第 ${index} 筆 ${esc(r.e)}" ${selection.has(r.id)?'checked':''}>`:context?'<span class="context-label">情境</span>':''}</td><td>${index}</td><td class="raw-e">${esc(r.e)}</td><td class="raw-d">${esc(r.d)}</td><td class="equipment-name">${esc(r.equipment||'待確認')}<span class="equipment-tags">${equipmentChange(r)}</span></td><td>${r.floor!=null?esc(r.floor)+'F':'待確認'}</td><td>${formCell(r)}</td><td>${esc(r.group||'待確認')}</td><td>${backgroundCell(backgrounds[r.id])}</td><td class="time-cell">${Number.isInteger(r.time)?formatClock(r.time):'—'}</td><td class="time-cell">${intervalCell(r.interval)}</td><td class="time-cell">${windowCell(info)}</td><td><button class="row-detail-button" data-act="expand" data-id="${esc(r.id)}" aria-label="${expanded.has(r.id)?'收合':'查看'}第 ${index} 筆詳情" aria-expanded="${expanded.has(r.id)}">${icon('more')}</button></td></tr>${expanded.has(r.id)?`<tr class="table-detail"><td colspan="13">${detailHtml(r,info)}</td></tr>`:''}`;}).join('')}</tbody></table></div>`;}
function selectionDock(){if(!selection.size)return '';return `<div class="selection-dock"><div class="dock-main"><strong>已選 ${selection.size} 筆</strong><button data-act="palette-toggle" aria-expanded="${paletteOpen}">上色</button><button data-act="remote-add">遠距</button><button data-act="deselect">清除選取</button></div>${paletteOpen?`<div class="dock-palette" aria-label="標記顏色">${[['yellow','黃底',''],['red','紅底',''],['floor','樓層紅字','F'],['extra','加時黃字','+'],['clear','清除標記','×']].map(([type,label,letter])=>`<button class="paint paint-${type}" data-act="paint" data-color="${type}" ${busy?'disabled':''}><span class="swatch">${letter}</span>${label}</button>`).join('')}</div>`:''}</div>`;}
function marksView(){if(!job.rows.length)return empty();return `${sourceCard()}<div class="mark-tools">${button('自動標色','autocolor','light','paint')}${button('復原','undo','light','undo',undoStack.length?'':'disabled')}${button('時間設定','to-settings','primary','clock')}</div>${filters()}${rowList(true)}${selectionDock()}`;}
function field(label,key,type='clock',value=job.settings[key]){return `<div class="field"><label for="setting-${key}">${label}</label><input id="setting-${key}" type="text" inputmode="${type==='clock'?'numeric':'decimal'}" data-setting="${key}" data-kind="${type}" value="${esc(type==='duration'?formatDuration(value):value)}" autocomplete="off" spellcheck="false"></div>`;}
function segment(key,options){return `<div class="segmented">${options.map(([v,label])=>`<button class="segment ${job.settings[key]===v?'active':''}" data-act="setting-choice" data-key="${key}" data-value="${v}" aria-pressed="${job.settings[key]===v}">${label}</button>`).join('')}</div>`;}
function settingsView(){return `<div class="stack settings-main">${button('操作說明 · 顏色時間','color-guide','light','paint')}<div class="card"><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('sun')}</span><div><h3>上午時段</h3><p>可直接輸入 0820，或 08:20</p></div></div><div class="time-range">${field('開始','amStart')}<span class="time-arrow">→</span>${field('截止','amEnd')}</div></div><div class="settings-section"><div class="section-title"><span class="section-icon">${icon('moon')}</span><div><h3>下午時段</h3><p>下午從 1F 重新出發</p></div></div><div class="time-range">${field('開始','pmStart')}<span class="time-arrow">→</span>${field('截止','pmEnd')}</div></div></div>
 <div class="card settings-section"><div class="section-title"><span class="section-icon">${icon('sliders')}</span><h3>檢測規則</h3></div><div class="setting-row"><div class="left"><h3>檢測難度</h3><p>黃底 ${job.settings.difficulty==='hard'?'2:31～3:10':'1:31～2:10'}，樓層與特殊另加</p></div>${segment('difficulty',[['normal','一般'],['hard','難']])}</div><div class="setting-row"><div class="left"><h3>80 顆驗證</h3><p>廠外仍保留其他時間規則</p></div>${segment('mode',[['auto','Auto'],['outdoor','廠外']])}</div>
 <details class="details-panel"><summary>首筆進場、收尾與跨區</summary><p class="inline-hint">分秒可填 1.30 或 130（1分30秒）。</p><h3 class="settings-title">首筆進場等待 · 分:秒</h3><div class="fields">${field('下限','entryMin','duration')}${field('上限','entryMax','duration')}</div><h3 class="settings-title">上午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','amEarlyMin','duration')}${field('最多提前','amEarlyMax','duration')}</div><h3 class="settings-title">下午返回 1F · 截止前多久</h3><div class="fields">${field('最少提前','pmEarlyMin','duration')}${field('最多提前','pmEarlyMax','duration')}</div><h3 class="settings-title">跨區額外加時 · 分:秒</h3><div class="fields">${field('下限','crossMin','duration')}${field('上限','crossMax','duration')}</div></details>
 <details class="details-panel"><summary>普通間隔範圍</summary><div class="info-note">這版把「基礎＋差值」顯示為實際秒數範圍。設定只影響本卡夾，不會更改 Excel。</div><div class="fields" style="margin-top:14px">${field('一般下限（秒）','normalMin','seconds')}${field('一般上限（秒）','normalMax','seconds')}${field('難檢下限（秒）','hardMin','seconds')}${field('難檢上限（秒）','hardMax','seconds')}</div></details></div>
 <div class="card settings-section"><div class="card-head"><div class="card-label">${icon('route')}<h3>遠距組合</h3></div>${button('新增','remote-add','light small','plus')}</div><p class="inline-hint" style="margin-bottom:16px">先在「標記」選元件，再加入組合。單筆可另外設定；遠距加在原有間隔上。</p>${remoteCards()}</div>
 ${button(busy?'正在試排…':'依設定試排全天','generate','primary w100','rocket',busy?'disabled':'')}${busy?button('取消本次試排','cancel','light w100','stop'):''}</div>`;}
function remoteCards(){return job.remotes.length?job.remotes.map(g=>`<div class="remote-card"><div class="flex between"><div><h3>${esc(g.name)}</h3><p class="meta">${g.rowIds.length} 筆 · 額外 +${formatDuration(g.min)}～${formatDuration(g.max)}</p></div><button class="icon-button" data-act="remote-edit" data-id="${esc(g.id)}" aria-label="編輯 ${esc(g.name)}">${icon('edit')}</button></div><div class="flex wrap">${button('查看成員','remote-members','light small','grid',`data-id="${esc(g.id)}"`)}${button('加入所選','remote-append','light small','plus',`data-id="${esc(g.id)}" ${selection.size?'':'disabled'}`)}</div></div>`).join(''):'<div class="info-note">尚未建立組合。可把 T 區黃底一次選好，設定例如 2:20～4:00。</div>';}
function resultDataTable(resultRows=null,windowById={}){
 if(!job.rows.length)return '<div class="card card-pad quiet-note">目前沒有資料。</div>';
 const lookup=new Map((resultRows||[]).map(row=>[row.id,row])),backgrounds=backgroundReport(resultRows||job.rows).byId,codeKey=showShortCode?'d':'e';
 return `<div class="result-controls"><label><input id="result-short-code" type="checkbox" ${showShortCode?'checked':''}>顯示短編碼</label><span>${job.rows.length} 筆 · 左右滑看明細</span></div><div class="table-scroll result-scroll" id="result-list" tabindex="0" aria-label="結果資料表，可水平捲動"><table class="data-table result-table"><colgroup>${[28,136,40,64,54,90,138,52,68,68,48].map(width=>`<col style="width:${width}px">`).join('')}</colgroup><thead><tr><th>#</th><th class="result-code-head">${showShortCode?'短編碼':'完整設備原碼'}</th><th>G<small>分</small></th><th>時間</th><th>間隔</th><th>本段筆數</th><th>設備名稱</th><th>樓層</th><th>小組</th><th>型式</th><th>詳情</th></tr></thead><tbody>${job.rows.map((base,index)=>{
  const scheduled=lookup.get(base.id),row=scheduled?{...base,...scheduled}:base,windowInfo=scheduled?windowById[base.id]:null;
  return `<tr class="${rowClasses(row)}"><td>${index+1}</td><td class="result-code ${codeKey==='e'?'raw-e':'raw-d'}">${esc(base[codeKey])}</td><td class="time-cell">${windowCell(windowInfo)}</td><td class="time-cell">${Number.isInteger(scheduled?.time)?formatClock(scheduled.time):'—'}</td><td class="time-cell">${intervalCell(scheduled?.interval)}</td><td>${backgroundCell(backgrounds[base.id])}</td><td class="equipment-name">${esc(base.equipment||'待確認')}<span class="equipment-tags">${equipmentChange(row)}</span></td><td>${base.floor!=null?esc(base.floor)+'F':'待確認'}</td><td>${esc(base.group||'待確認')}</td><td>${formCell(base)}</td><td><button class="row-detail-button" data-act="expand" data-id="${esc(base.id)}" aria-label="${expanded.has(base.id)?'收合':'查看'}第 ${index+1} 筆詳情" aria-expanded="${expanded.has(base.id)}">${icon('more')}</button></td></tr>${expanded.has(base.id)?`<tr class="table-detail"><td colspan="11">${detailHtml(row,windowInfo)}</td></tr>`:''}`;
 }).join('')}</tbody></table></div>`;
}
function measurementDisplay(value){
 if(value==null)return '';
 const digits=(job.measurementSettings?.format||'1000')==='2020'?1:2;
 return Number(value.toFixed(digits))===value?value.toFixed(digits):String(value);
}
function measurementProgress(){const rows=job.rows;return `${rows.length} 筆 · A ${rows.filter(r=>r.a!=null).length} / B ${rows.filter(r=>r.b!=null).length}`;}
function measurementsView(){
 if(!job.rows.length)return empty();
 const rows=currentJobRows(job),settings={...DEFAULT_MEASUREMENT_SETTINGS,...job.measurementSettings};
 return `<div class="measurement-toolbar">${button('生成 A/B','generate-measurements','primary','edit',busy?'disabled':'')}${button('復原','undo','light','undo',undoStack.length&&!busy?'':'disabled')}<span data-measurement-count>${measurementProgress()}</span></div>
 ${job.measurementNotice?`<p class="notice measurement-notice">${esc(job.measurementNotice)}</p>`:''}
 <details class="card measurement-settings"><summary>範圍設定 · ${settings.format}</summary><form id="measurement-settings-form"><div class="field"><label for="measurement-format">格式</label><select id="measurement-format" name="format"><option value="1000" ${settings.format==='1000'?'selected':''}>1000 · 兩位小數</option><option value="2020" ${settings.format==='2020'?'selected':''}>2020 · 一位小數</option></select></div><div class="fields">${[['aMin','A 下限'],['aMax','A 上限'],['bMin','B 下限'],['bMax','B 上限']].map(([key,label])=>`<div class="field"><label for="measurement-${key}">${label}</label><input id="measurement-${key}" name="${key}" inputmode="decimal" value="${settings[key]}" required></div>`).join('')}</div><button type="submit" class="button light">套用範圍</button></form></details>
 <div class="table-scroll measurement-scroll" id="measurement-list" tabindex="0" aria-label="A/B 填寫表"><table class="data-table measurement-table"><colgroup><col style="width:42%"><col style="width:20%"><col style="width:20%"><col style="width:18%"></colgroup><thead><tr><th>設備長碼</th><th>A<small>背景</small></th><th>B<small>淨檢</small></th><th>型式</th></tr></thead><tbody>${rows.map((row,index)=>`<tr class="${rowClasses(row)}"><td class="measurement-code"><small>${index+1}</small><span>${esc(row.e)}</span></td>${['a','b'].map(key=>`<td><input class="measurement-input" data-measurement="${key}" data-id="${esc(row.id)}" inputmode="decimal" autocomplete="off" aria-label="第 ${index+1} 筆 ${key.toUpperCase()}" value="${esc(measurementDisplay(row[key]))}" ${busy?'disabled':''}></td>`).join('')}<td>${formCell(row)}</td></tr>`).join('')}</tbody></table></div>`;
}
function measurementChanged(){document.querySelector('.measurement-toolbar [data-act="undo"]')?.removeAttribute('disabled');job.updated=new Date().toISOString();clearTimeout(saveTimer);void persist();document.querySelectorAll('[data-measurement-count]').forEach(el=>el.textContent=measurementProgress());}
function generateAB(){
 ensureIdle();if(!resultCurrent())throw new Error('請先完成時間試排，再生成 A/B。');
 const rows=currentJobRows(job);if(rows.some(row=>!Number.isInteger(row.time)))throw new Error('時間尚未完整，請重新試排。');
 const generated=generateMeasurements(rows,job.measurementSettings);
 snapshot();storeMeasurements(job,generated);measurementChanged();renderKeepScroll();toast('A/B 已生成，可直接修改；A 會同步同背景段。');
}
function resultsView(){if(busy)return `<div class="card card-pad"><div class="card-label">${icon('refresh','loading-icon')}<h2>正在裝置內試排</h2></div><p class="quiet-note">檢查完整小組切點、上下樓、特殊加時與起訖時間。</p><div class="progress-bar"><i></i></div>${button('取消本次試排','cancel','light w100','stop')}</div>`;
 const current=resultCurrent(),result=current?{...job.result,rows:currentJobRows(job)}:job.result;
 if(!result)return `<div class="notice" style="margin-bottom:16px">尚未試排；時間、間隔與 G 先顯示為 —。</div><div class="sticky-actions">${button('試排全天','generate','primary','rocket',job.rows.length?'':'disabled')}${button('調整設定','to-settings','light','sliders')}</div>${resultDataTable()}`;
 if(!current){const failed=!result.ok,items=(result.errors||result.checks?.filter(c=>!c.ok).map(c=>c.detail)||[]).slice(0,5);return `<div class="notice ${failed?'error':''}" style="margin-bottom:16px"><strong>${failed?'這次尚未排出結果':'設定或標記已變動'}</strong><p>${failed?'這是第一版搜尋結果，不代表這份資料一定無解。':'舊結果不再顯示時間或 G，請重新試排。'}</p>${items.length?`<ul>${items.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:''}</div><div class="sticky-actions">${button('回設定調整','to-settings','primary','sliders')}${button('重新試排','generate','light','refresh')}</div>${resultDataTable()}`;}
 const r=result.summary,windows=windowReport(result.rows,job.settings.mode),minimum=value=>Number.isInteger(value)?`${Math.floor(value/60)} 分`:'—';return `<div class="notice good" style="margin-bottom:16px">試排檢查完成。</div><div class="stat-grid"><div class="result-stat"><span>上午 · ${r.amCount} 筆</span><strong>${r.amReturn!=null?formatClock(r.amReturn):'—'}</strong><small>返回 1F 的時間</small></div><div class="result-stat"><span>下午 · ${r.pmCount} 筆</span><strong>${r.pmReturn!=null?formatClock(r.pmReturn):'—'}</strong><small>返回 1F 的時間</small></div></div><div class="window-summary"><div><span>上午80窗最低</span><strong>${minimum(windows.amMinimum)}</strong></div><div><span>下午80窗最低</span><strong>${minimum(windows.pmMinimum)}</strong></div><div><span>${windows.mode==='outdoor'?'顯示窗口':'低於61分'}</span><strong>${windows.mode==='outdoor'?windows.count:windows.belowThreshold}</strong></div></div><details class="card card-pad validation-details"><summary>驗證明細</summary>${(result.checks||[]).map(c=>`<div class="check-row ${c.ok?'':'fail'}">${icon(c.ok?'check':'info')}<div><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div></div>`).join('')}<p class="inline-hint">${(result.warnings||[]).map(esc).join(' ')}</p></details><div class="sticky-actions">${button('匯出試排 CSV','export-csv','primary','download')}${button('重新試排','generate','light','refresh')}</div>${resultDataTable(result.rows,windows.byId)}`;
}
function asideView(){if(!job.rows.length||tab==='marks')return '';return `<div class="card card-pad"><div class="card-head"><h3>操作</h3></div>${button(busy?'正在試排…':'試排全天','generate','primary w100','rocket',job.rows.length&&!busy?'':'disabled')}${busy?button('取消','cancel','light w100','stop'):''}</div>`;
}

function selectRow(id){if(selection.has(id))selection.delete(id);else selection.add(id);if(!selection.size)paletteOpen=false;renderKeepScroll();}
function applyColor(color){ensureIdle();if(!selection.size)return;snapshot();for(const r of job.rows)if(selection.has(r.id)){if(['yellow','red'].includes(color))r.background=color;else if(color==='floor'){r.floorMark=true;if(r.background==='none')r.background='yellow';}else if(color==='extra')r.extraMark=true;else{r.background='none';r.floorMark=false;r.extraMark=false;}}changed();renderKeepScroll();toast(`已套用到 ${selection.size} 筆，可按復原。`);}
function editRow(id){const r=job.rows.find(x=>x.id===id);showModal('確認解析',`<p>D／E 原始字串不會更動。此處修改的是本卡夾的解析結果。</p><div class="sample-preview">D：${esc(r.d)}<br>E：${esc(r.e)}</div><form id="edit-row-form" data-id="${esc(id)}"><div class="fields">${[['region','區域',r.region],['equipment','設備',r.equipment],['floor','樓層（數字）',r.floor??''],['group','小組',r.group],['form','型式',r.form]].map(([key,label,v])=>`<div class="field"><label for="row-${key}">${label}</label><input id="row-${key}" name="${key}" value="${esc(v)}" ${key==='floor'?'inputmode="numeric"':''} maxlength="100"></div>`).join('')}</div><button class="button primary w100" type="submit">套用解析</button></form>`);}
function remoteDialog(id=null){const existing=job.remotes.find(g=>g.id===id);if(!existing&&!selection.size){toast('先到標記頁選取元件，再加入遠距組合。');changeTab('marks');return;}const g=existing||{name:`遠距組合 ${job.remotes.length+1}`,min:140,max:240,rowIds:[...selection]};showModal(existing?'編輯遠距組合':'建立遠距組合',`<p>共 ${g.rowIds.length} 筆。時間額外加在原本間隔上，背景、樓層與特殊照常計算。</p><form id="remote-form" data-id="${id||''}"><div class="field"><label for="remote-name">組合名稱</label><input id="remote-name" name="name" value="${esc(g.name)}" maxlength="60" required></div><div class="fields"><div class="field"><label for="remote-min">下限 · 分.秒</label><input id="remote-min" name="min" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(g.min)}" required></div><div class="field"><label for="remote-max">上限 · 分.秒</label><input id="remote-max" name="max" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(g.max)}" required></div></div><p class="inline-hint">1.30／130＝1分30秒；2.22＝2分22秒。已有單筆設定者保留。</p><div class="foot-actions">${existing?button('刪除組合','remote-delete','danger','trash',`data-id="${id}" type="button"`):''}<button class="button primary" type="submit">${existing?'儲存組合':'加入組合'}</button></div></form>`);}
function singleRemote(id){const r=job.rows.find(x=>x.id===id),remote=remoteMap(job)[id]||{min:140,max:240};showModal('單筆遠距加時',`<p>${esc(r.d)}<br>只改這一筆，其他組合成員維持原時間。</p><form id="single-remote-form" data-id="${esc(id)}"><div class="fields"><div class="field"><label for="single-min">下限 · 分.秒</label><input id="single-min" name="min" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(remote.min)}"></div><div class="field"><label for="single-max">上限 · 分.秒</label><input id="single-max" name="max" inputmode="decimal" placeholder="1.30 或 130" value="${formatDuration(remote.max)}"></div></div><p class="inline-hint">1.30／130＝1分30秒；2.22＝2分22秒。</p><div class="foot-actions">${button('恢復組合時間','remote-reset','light','undo',`data-id="${esc(id)}" type="button"`)}<button class="button primary" type="submit">套用單筆</button></div></form>`);}
async function shelf(){await persist();showModal('我的卡夾',`<p>卡夾保留在這台裝置；透過匯出、匯入帶到另一台。</p>${jobs.sort((a,b)=>b.updated.localeCompare(a.updated)).map(j=>`<button class="job-card ${j.id===job.id?'active':''}" data-act="load-job" data-id="${esc(j.id)}"><div><strong>${esc(j.name)}</strong><p>${esc(j.rows.length?j.plant:'未選廠別')} · ${j.rows.length} 筆 · ${new Date(j.updated).toLocaleDateString('zh-TW')}</p></div>${icon('chevron')}</button>`).join('')}<div class="shelf-tools">${button('新增空白卡夾','new-job','primary','plus')}${button('匯入卡夾','restore','light','upload')}${button('匯出目前','backup','light','download')}</div>${button('刪除目前卡夾','delete-job','ghost small','trash','style="margin-top:18px"')}`);}
async function openWorkbook(file){if(!file)return;try{ensureIdle();if(file.size>20*1024*1024)throw new Error('檔案超過 20 MB，請先另存需要的工作頁。');showModal('讀取工作頁',`<p>${esc(file.name)}</p><div class="progress-bar"><i></i></div><p>只在本機讀取，不會執行活頁簿的巨集。</p>`);const token=crypto.randomUUID();importData={token,fileName:file.name,rows:[],sheets:[]};importer?.terminate();importer=new Worker('./import-worker.js');importer.onerror=()=>{toast('活頁簿讀取失敗，請重新選擇。');closeModal();};importer.onmessage=({data})=>{if(importData?.token!==token)return;if(data.type==='error'){toast(data.message);closeModal();return;}if(data.type==='sheets'){importData.sheets=data.sheets;importData.visibility=data.visibility;importDialog();requestSheet();}if(data.type==='rows'){if(data.requestId!==importData.requestId)return;importData.rows=data.rows;const box=document.getElementById('import-preview');if(box)box.innerHTML=data.rows.slice(0,3).map(r=>`<p>B：${esc(r.b)}<br>C：${esc(r.c)}</p>`).join('')||'選取的範圍沒有 B／C 資料。';const c=document.getElementById('import-count');if(c)c.textContent=`讀到 ${data.rows.length} 筆`;const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=!data.rows.length;}};const buffer=await file.arrayBuffer();if(importData?.token===token)importer.postMessage({action:'open',buffer},[buffer]);}catch(error){toast(error.message);}}
function importDialog(){const inferred=PLANTS.find(p=>p!=='示範廠'&&importData.fileName.includes(p))||(job.rows.length?job.plant:'');showModal('選擇匯入範圍',`<p>${esc(importData.fileName)}</p><div class="field" style="margin-bottom:12px"><label for="sheet-search">搜尋工作頁</label><input id="sheet-search" type="text" placeholder="份數、中文字或 (區域)"></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="show-hidden">顯示隱藏工作頁</label><div class="field"><label for="import-sheet">工作頁（完整原名）</label><select id="import-sheet">${sheetOptions()}</select></div><div class="fields three"><div class="field"><label for="import-start">從第幾列開始</label><input id="import-start" inputmode="numeric" type="number" min="1" max="100000" value="3"></div><div class="field"><label for="import-amount">最多幾筆</label><input id="import-amount" inputmode="numeric" type="number" min="1" max="448" value="400"></div><div class="field"><label for="import-plant">廠別</label><select id="import-plant"><option value="" ${inferred?'':'selected'}>請選擇廠別</option>${PLANTS.filter(p=>p!=='示範廠').map(p=>`<option ${p===inferred?'selected':''}>${esc(p)}</option>`).join('')}</select></div></div><label class="flex" style="font-size:13px;margin-bottom:14px"><input type="checkbox" id="import-reverse">反轉此廠預設的 D／E 方向</label><div class="import-mapping" id="import-mapping">一般來源 B→D、C→E；油類使用廠別的反轉設定。</div><p class="inline-hint" id="import-count">讀取中…</p><div id="import-preview" class="sample-preview" style="margin-top:10px">準備預覽前三筆。</div><div class="foot-actions">${button('匯入新卡夾','accept-import','primary','arrow','disabled')}</div>`);}
function sheetOptions(query='',includeHidden=false){return (importData.visibility||importData.sheets.map(name=>({name,hidden:0}))).filter(s=>(includeHidden||!s.hidden)&&matchSheetName(s.name,query)).map(s=>`<option value="${esc(s.name)}">${esc(s.name)}${s.hidden===2?' · 深度隱藏':s.hidden?' · 隱藏':''}</option>`).join('');}
let sheetTimer;
function filterSheets(){const select=document.getElementById('import-sheet'),previous=select.value;select.innerHTML=sheetOptions(document.getElementById('sheet-search').value,document.getElementById('show-hidden').checked);if([...select.options].some(o=>o.value===previous)){select.value=previous;return;}importData.rows=[];importData.requestId=(importData.requestId||0)+1;document.querySelector('[data-act="accept-import"]').disabled=true;clearTimeout(sheetTimer);sheetTimer=setTimeout(()=>requestSheet(),250);}
function requestSheet(){if(!importer)return;const sheet=document.getElementById('import-sheet').value;importData.rows=[];const acceptButton=document.querySelector('[data-act="accept-import"]');if(acceptButton)acceptButton.disabled=true;if(!sheet){document.getElementById('import-preview').textContent='沒有符合條件的工作頁，可調整搜尋或顯示隱藏頁。';document.getElementById('import-count').textContent='0 筆';return;}const first=Number(document.getElementById('import-start')?.value),count=Number(document.getElementById('import-amount')?.value);if(!Number.isInteger(first)||first<1||first>100000||!Number.isInteger(count)||count<1||count>448){toast('起始列須為 1～100000，筆數須為 1～448。');return;}const accept=document.querySelector('[data-act="accept-import"]');if(accept)accept.disabled=true;importData.requestId=(importData.requestId||0)+1;document.getElementById('import-count').textContent='正在讀取所選頁面…';importer.postMessage({action:'sheet',name:sheet,first,count,requestId:importData.requestId});}
async function acceptImport(){ensureIdle();const plant=document.getElementById('import-plant').value,reverse=document.getElementById('import-reverse').checked,rows=parseRows(importData.rows,plant,reverse),sheet=document.getElementById('import-sheet').value;if(!PLANTS.includes(plant))throw new Error('請先選擇廠別。');if(!rows.length)throw new Error('沒有資料可匯入。');const name=importData.fileName;await persist();job=blankJob(`${plant} · ${sheet}`);Object.assign(job,{sourceName:name,sheet,plant,rows});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];closeModal();await persist();changeTab('data');toast(`已匯入 ${rows.length} 筆。原有卡夾已保留。`);}
async function loadProject(file){if(!file)return;try{ensureIdle();if(file.size>5*1024*1024)throw new Error('卡夾大於 5 MB，無法匯入。');const data=validateProject(JSON.parse(await file.text()));const errors=validateSettings(data.settings);if(errors.length)throw new Error(errors.join('；'));await persist();job=data;selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');toast('卡夾已匯入；時間結果會重新驗算。');}catch(error){toast(error.message);}}
function download(content,name,mime='application/json'){const blob=new Blob([content],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
function backup(){const visible=currentJobRows(job);const copy={...job,rows:job.rows.map((row,i)=>({...row,background:visible[i].background}))};download(JSON.stringify(copy,null,2),`${job.name.replace(/[\\/:*?"<>|]/g,'_')}.log.json`);toast('卡夾已交給瀏覽器下載，手機可在「檔案」保留。');}
function exportCSV(){if(!resultCurrent())throw new Error('請先完成本次設定的試排。');const lines=[['試排資料（未完成 Excel 正式驗收）'],['序號','元件 D','設備原碼 E','設備','區域','樓層','小組','型式','時段','時間','間隔','背景','樓層標記','額外標記','A 背景','B 淨檢']];currentJobRows(job).forEach((r,i)=>lines.push([i+1,r.d,r.e,r.equipment,r.region,r.floor,r.group,r.form,r.period,formatClock(r.time),formatDuration(r.interval),r.background,r.floorMark,r.extraMark,r.a,r.b]));download('\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n',`${job.name.replace(/[\\/:*?"<>|]/g,'_')}-試排.csv`,'text/csv;charset=utf-8');}
async function generate(){ensureIdle();if(!job.rows.length)throw new Error('請先匯入資料。');const errors=validateSettings(job.settings);if(errors.length)throw new Error(errors.join('；'));busy=true;try{snapshot();job.rows=autocolor(job.rows);changed();tab='results';render();window.scrollTo({top:0,behavior:'instant'});await persist();if(!busy)return;solver=new Worker('./solver-worker.mjs',{type:'module'});}catch(error){busy=false;render();throw error;}const revision=job.revision;
 const finish=()=>{solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;};
 solver.onmessage=({data})=>{finish();if(data.type==='result'&&data.revision===job.revision){job.result={...data.result,revision};saveSoon();render();toast(data.result.ok?'試排完成，可點元件查看間隔組成。':'本次尚未找到方案，詳情已列出。');}else{render();toast(data.message||'資料已變動，結果未套用。');}};
 solver.onerror=()=>{finish();render();toast('試排器未能完成，原有資料與結果保留。');};
 solverTimer=setTimeout(()=>{finish();render();toast('本次試排超過 20 秒，已停止工作程序，原資料保留。');},20000);
 solver.postMessage({rows:job.rows,settings:job.settings,remoteMap:remoteMap(job),seed:crypto.getRandomValues(new Uint32Array(1))[0],revision});
}
function cancel(){solver?.terminate();solver=null;clearTimeout(solverTimer);busy=false;render();toast('已取消試排，資料與標記保留。');}
let guideReturn='settings';
function guideView(){
 const rule=colorTimeGuide(job.settings),range=values=>values.map(formatDuration).join('～');
 const rows=[
  ['yellow','黃底',range(rule.background),'換背景'],
  ['blue','藍底',range(rule.background),'程式補背景，同黃底'],
  ['red','紅底',range(rule.cross),'已含背景＋跨區；換樓層再加移動'],
  ['floor','樓層紅字','背景＋樓層移動','依相差樓層計算，底色保留'],
  ['extra','黃字',range(rule.extra),'無底色、未換樓層時使用；有底色則依底色時間'],
  ['special','粉字 CPRSAI',`＋${formatDuration(rule.special)}`,'型式命中任一字母，每筆只加一次'],
 ];
 return `<div class="color-guide">${rows.map(([color,label,time,note])=>`<article class="card color-guide-row"><span class="guide-swatch guide-${color}" aria-hidden="true">${['floor','extra','special'].includes(color)?'字':''}</span><div><h2>${label}</h2><p>${note}</p></div><strong class="guide-time">${time}</strong></article>`).join('')}<details class="card guide-floors"><summary>樓層紅字 · 含黃底時間</summary><div class="guide-floor-table"><table><thead><tr><th>相差</th><th>上樓</th><th>下樓</th></tr></thead><tbody>${rule.floors.map(f=>`<tr><th>${f.difference} 層</th><td>${range(f.up)}</td><td>${range(f.down)}</td></tr>`).join('')}</tbody></table></div></details><p class="inline-hint guide-note">每段首筆黃底依進場 ${range(rule.entry)}，上樓另加。粉字、遠距另行疊加。</p></div>`;
}
function help(){showModal('資訊',button('操作說明 · 顏色時間','color-guide','light w100','paint')+infoHtml(),'info');refreshUpdateState();void updater?.check(true);}

async function action(name,el){
 const mutating=['generate-measurements','paint','undo','autocolor','remote-add','remote-edit','remote-append','remote-delete','remote-reset','edit-row','edit-distance','setting-choice','new-job','delete-job','load-job','demo','rename','import','restore'];if(mutating.includes(name))ensureIdle();
 const id=el.dataset.id;
 switch(name){
 case 'tab':changeTab(el.dataset.tab);break;
 case 'to-marks':changeTab('marks');break;case 'to-settings':changeTab('settings');break;
 case 'close-modal':closeModal();break;case 'help':help();break;
 case 'color-guide':if(tab!=='guide')guideReturn=tab;if(modal.open)closeModal();changeTab('guide');break;
 case 'guide-back':changeTab(guideReturn);break;
 case 'check-update':if(updater?.state==='recovery')await updater.recover();else await updater?.update();break;
 case 'recover-update':await updater?.recover();break;
 case 'import':document.getElementById('source-file').click();break;
 case 'restore':closeModal();document.getElementById('project-file').click();break;
 case 'accept-import':await acceptImport();break;
 case 'demo':{await persist();const demo=makeDemo();job=blankJob(demo.name);Object.assign(job,demo,{demo:true});selection.clear();expanded.clear();search='';regionFilter='';markFilter='all';undoStack=[];await persist();changeTab('data');toast('這是合成資料，可放心試標記。');break;}
 case 'select':selectRow(id);break;
 case 'expand':expanded.has(id)?expanded.delete(id):expanded.add(id);renderKeepScroll();break;
 case 'select-filter':filtered().forEach(r=>selection.add(r.id));renderKeepScroll();break;
 case 'select-group':{const keys=new Set(job.rows.filter(r=>selection.has(r.id)).map(r=>[r.region,r.equipment,r.group].join('|')));job.rows.forEach(r=>{if(r.group&&keys.has([r.region,r.equipment,r.group].join('|')))selection.add(r.id);});renderKeepScroll();break;}
 case 'deselect':selection.clear();paletteOpen=false;renderKeepScroll();break;
 case 'palette-toggle':paletteOpen=!paletteOpen;renderKeepScroll();break;
 case 'view-mode':viewMode=el.dataset.value;shown=60;rememberUi();renderKeepScroll();break;
 case 'more':shown+=60;renderKeepScroll();break;
 case 'paint':applyColor(el.dataset.color);break;
 case 'undo':if(undoStack.length){job=undoStack.pop();saveSoon();render();toast('已復原前一步。');}break;
 case 'autocolor':snapshot();job.rows=autocolor(job.rows);changed();render();toast('已依設備、樓層、區域檢查標記。');break;
 case 'setting-choice':snapshot();job.settings[el.dataset.key]=el.dataset.value;changed();render();break;
 case 'edit-row':editRow(id);break;case 'edit-distance':singleRemote(id);break;
 case 'remote-add':remoteDialog();break;case 'remote-edit':remoteDialog(id);break;
 case 'remote-members':{const g=job.remotes.find(x=>x.id===id);showModal(esc(g.name),`<p>${g.rowIds.length} 筆 · 點「單筆遠距」可覆寫其中一筆。</p>${g.rowIds.map(rid=>{const r=job.rows.find(x=>x.id===rid),m=remoteMap(job)[rid];return `<div class="job-card"><div><strong>${esc(r.d)}</strong><p>+${formatDuration(m.min)}～${formatDuration(m.max)}${job.overrides[rid]?' · 單筆覆寫':''}</p></div>${button('單筆','edit-distance','light small','',`data-id="${rid}"`)}</div>`;}).join('')}`);break;}
 case 'remote-append':snapshot();for(const g of job.remotes)g.rowIds=g.rowIds.filter(rid=>!selection.has(rid));job.remotes.find(g=>g.id===id).rowIds.push(...selection);selection.clear();changed();render();toast('已加入組合；每筆只套一組遠距。');break;
 case 'remote-delete':if(confirm('移除這個遠距組合？單筆自訂仍會保留。')){snapshot();job.remotes=job.remotes.filter(g=>g.id!==id);changed();closeModal();render();}break;
 case 'remote-reset':snapshot();delete job.overrides[id];changed();closeModal();render();toast('已恢復組合時間。');break;
 case 'generate-measurements':generateAB();break;
 case 'generate':await generate();break;case 'cancel':cancel();break;
 case 'shelf':await shelf();break;case 'backup':backup();break;case 'export-csv':exportCSV();break;
 case 'new-job':await persist();job=blankJob();selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();await persist();changeTab('data');break;
 case 'load-job':await persist();job=structuredClone(jobs.find(j=>j.id===id));selection.clear();undoStack=[];expanded.clear();search='';regionFilter='';markFilter='all';closeModal();changeTab('data');await persist();break;
 case 'delete-job':if(confirm(`只刪除此裝置的「${job.name}」卡夾？原始 XLSX 不會刪除。`)){deletingJob=true;clearTimeout(saveTimer);try{await saveChain.catch(()=>{});await removeJob(job.id);jobs=jobs.filter(j=>j.id!==job.id);job=jobs.length?structuredClone(jobs[0]):blankJob();selection.clear();expanded.clear();undoStack=[];search='';regionFilter='';markFilter='all';paletteOpen=false;closeModal();}finally{deletingJob=false;}await persist();changeTab('data');}break;
 case 'rename':showModal('卡夾名稱',`<form id="rename-form"><div class="field"><label for="job-name">方便你下次找到</label><input id="job-name" name="name" maxlength="100" required value="${esc(job.name)}"></div><div class="foot-actions"><button class="button primary" type="submit">儲存</button></div></form>`);break;
 }
}
let dispatchBusy=false;
document.addEventListener('click',event=>{const el=event.target.closest('[data-act]');if(!el||el.disabled)return;event.preventDefault();const exclusive=['demo','new-job','load-job','delete-job','accept-import','shelf'].includes(el.dataset.act);if(exclusive&&dispatchBusy)return;if(exclusive)dispatchBusy=true;action(el.dataset.act,el).catch(e=>toast(e.message)).finally(()=>{if(exclusive)dispatchBusy=false;});});
document.addEventListener('keydown',event=>{if(event.target.closest('button,input,select,textarea,a'))return;const el=event.target.closest('[role="button"][data-act],tr[data-act],.row-main[data-act="select"]');if(el&&(event.key==='Enter'||event.key===' ')){event.preventDefault();action(el.dataset.act,el).catch(e=>toast(e.message));}});
document.addEventListener('input',event=>{if(event.target.id==='sheet-search'){filterSheets();return;}if(event.target.id==='search'){search=event.target.value;const focus=event.target.selectionStart,scrollY=window.scrollY;render();const input=document.getElementById('search');input.focus({preventScroll:true});input.setSelectionRange(focus,focus);window.scrollTo({top:scrollY,behavior:'instant'});}});
document.addEventListener('change',event=>{const el=event.target;try{
 if(el.dataset.measurement){ensureIdle();const rows=currentJobRows(job),updated=el.dataset.measurement==='a'?setSegmentA(rows,el.dataset.id,el.value):setRowB(rows,el.dataset.id,el.value);snapshot();storeMeasurements(job,updated);measurementChanged();const values=new Map(job.rows.map(row=>[row.id,row]));document.querySelectorAll('[data-measurement]').forEach(input=>{input.value=measurementDisplay(values.get(input.dataset.id)?.[input.dataset.measurement]);});document.querySelector('.measurement-notice')?.remove();return;}
 if(el.id==='region-filter'){regionFilter=el.value;shown=60;renderKeepScroll();}else if(el.id==='mark-filter'){markFilter=el.value;shown=60;renderKeepScroll();}else if(el.id==='context-filter'){showContext=el.checked;rememberUi();renderKeepScroll();}
 else if(el.id==='result-short-code'){showShortCode=el.checked;renderKeepScroll();}
 else if(['import-sheet','import-start','import-amount'].includes(el.id))requestSheet();else if(el.id==='show-hidden')filterSheets();
 else if(el.dataset.setting){ensureIdle();const key=el.dataset.setting;let value;if(el.dataset.kind==='clock')value=formatClock(parseClock(el.value)).slice(0,5);else if(el.dataset.kind==='duration')value=durationInput(el.value);else{value=Number(el.value);if(!Number.isInteger(value)||value<1||value>3600)throw new Error('秒數請填 1～3600 的整數。');}snapshot();job.settings[key]=value;changed();el.value=el.dataset.kind==='duration'?formatDuration(value):value;toast('設定已儲存，原結果需要重新試排。');}
 }catch(error){toast(error.message);if(el.dataset.measurement)el.value=measurementDisplay(job.rows.find(row=>row.id===el.dataset.id)?.[el.dataset.measurement]);if(el.dataset.setting){const v=job.settings[el.dataset.setting];el.value=el.dataset.kind==='duration'?formatDuration(v):v;}}
});
document.addEventListener('submit',event=>{event.preventDefault();try{ensureIdle();const form=event.target,fd=new FormData(form);if(form.id==='edit-row-form'){const floor=Number(fd.get('floor'));if(!Number.isInteger(floor)||floor<1||floor>99||!String(fd.get('region')).trim()||!String(fd.get('equipment')).trim()||!String(fd.get('group')).trim())throw new Error('請填區域、設備、小組，以及 1～99 的樓層。');snapshot();const row=job.rows.find(r=>r.id===form.dataset.id);for(const k of ['region','equipment','group','form'])row[k]=String(fd.get(k)).trim();row.floor=floor;row.issues=[];changed();closeModal();render();}
 else if(['remote-form','single-remote-form'].includes(form.id)){const min=durationInput(fd.get('min')),max=durationInput(fd.get('max'));if(min>max)throw new Error('下限不能大於上限。');snapshot();if(form.id==='single-remote-form')job.overrides[form.dataset.id]={min,max};else{const name=String(fd.get('name')).trim();if(!name)throw new Error('請填組合名稱。');const existing=job.remotes.find(g=>g.id===form.dataset.id);if(existing)Object.assign(existing,{name,min,max});else{for(const g of job.remotes)g.rowIds=g.rowIds.filter(id=>!selection.has(id));job.remotes.push({id:crypto.randomUUID(),name,min,max,rowIds:[...selection]});selection.clear();}}changed();closeModal();render();toast('遠距加時已儲存，重新試排才會套用。');}
 else if(form.id==='measurement-settings-form'){const settings=normalizeMeasurementSettings(Object.fromEntries(fd));snapshot();job.measurementSettings=settings;measurementChanged();renderKeepScroll();toast('範圍已套用；按「生成 A/B」才會更換數值。');}
 else if(form.id==='rename-form'){job.name=String(fd.get('name')).trim()||'未命名卡夾';job.updated=new Date().toISOString();saveSoon();closeModal();render();}
 }catch(error){toast(error.message);}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);persist();}});
window.addEventListener('pagehide',()=>{solver?.terminate();importer?.terminate();});
async function start(){try{jobs=await getJobs();let last;try{last=localStorage.getItem('log-active');viewMode=localStorage.getItem('log-row-view')||'table';showContext=localStorage.getItem('log-filter-context')==='1';}catch{}if(!['table','cards'].includes(viewMode))viewMode='table';job=structuredClone(jobs.find(j=>j.id===last)||jobs.sort((a,b)=>b.updated.localeCompare(a.updated))[0]||blankJob());saveState=jobs.length?'已存於此裝置':'尚未儲存';}catch{job=blankJob();saveState='此瀏覽器無法儲存';}render();
 updater=createUpdater({serviceWorker:navigator.serviceWorker,currentVersion:globalThis.LOG_RELEASE?.version,getLatestVersion:fetchReleaseVersion,isBusy:()=>busy||Boolean(importer),hasOpenEditor:()=>modal.open&&modal.dataset.kind!=='info',canAutoUpdate:()=>updateIdle,
  save:async()=>{clearTimeout(saveTimer);return await persist();},
  onStatus:(_state,message)=>{refreshUpdateState();if(message)toast(message);}
 });
 for(const event of ['pointerdown','touchstart','wheel','keydown','input'])document.addEventListener(event,()=>{updateIdle=false;},{capture:true,passive:true});
 await updater.update({automatic:true});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')updateIdle=true;else updater.update({automatic:true});});
 window.addEventListener('pageshow',event=>{if(event.persisted)updater.update({automatic:true});});
 window.addEventListener('online',()=>updater.check(true));
}

start();
