import {DEFAULT_MANUAL_SETTINGS,candidateRows,activeCandidates} from './manual-time.mjs';
import {formatClock,formatDuration} from './domain.mjs';

export function manualSettingsFor(job){
  return job.manualSettings||{...DEFAULT_MANUAL_SETTINGS,...Object.fromEntries(['amStart','amEnd','pmStart','pmEnd'].map(key=>[key,job.settings[key]])),amCount:Math.min(job.rows.length,job.result?.summary?.amCount??Math.ceil(job.rows.length*.6))};
}

export function manualTimeView(job,state,{esc,button}){
  const settings=manualSettingsFor(job),plan=job.manualPlan;
  const field=(key,label,numeric=false)=>`<div class="field"><label for="manual-${key}">${label}</label><input id="manual-${key}" name="${key}" data-manual-setting="${key}" inputmode="numeric" type="text" value="${esc(settings[key])}" autocomplete="off" required></div>`;
  const config=`<form id="manual-settings-form"><div class="fields">${field('base','基礎（秒）',true)}${field('rand','Rand（加 0～幾秒）',true)}</div><div class="manual-config-times"><h3>上午候選時段</h3><div class="fields">${field('amStart','第一個時刻')}${field('amEnd','最後界線')}</div><h3>下午候選時段</h3><div class="fields">${field('pmStart','第一個時刻')}${field('pmEnd','最後界線')}</div></div><div class="foot-actions">${button('取用時間設定','manual-use-settings','light small','clock','type="button"')}<button class="button primary" type="submit">${plan?'重建候選':'產生候選'}</button></div><p class="inline-hint">只有產生／重建會重抽。上午、下午共用間隔，各自刪除。</p></form>`;
  let html=`<div class="manual-page">${button('返回時間設定','to-settings','light small','undo')}<details class="card manual-config" ${plan?'':'open'}><summary>基礎 ${settings.base} ＋ Rand ${settings.rand}</summary>${config}</details>`;
  if(!plan)return html+'<div class="notice">設定基礎、Rand 與時段，產生候選後即可多選刪除。</div></div>';
  const am=candidateRows(plan,'am'),pm=candidateRows(plan,'pm'),activeAm=activeCandidates(plan,'am'),activePm=activeCandidates(plan,'pm');
  const amCount=plan.settings.amCount,pmCount=job.rows.length-amCount,enough=amCount>=0&&pmCount>=0&&activeAm.length>=amCount&&activePm.length>=pmCount;
  const configChanged=JSON.stringify(settings)!==JSON.stringify(plan.settings);
  const applied=job.manualResult?.planRevision===job.manualRevision;
  html+=`${configChanged?'<div class="notice">設定已變更，重建後才會更換候選。</div>':''}<div class="card manual-assignment"><label for="manual-cut">上午套用筆數</label><div class="flex"><input id="manual-cut" type="number" inputmode="numeric" min="0" max="${job.rows.length}" value="${amCount}"><span>下午 ${Math.max(0,pmCount)} 筆</span></div><div class="manual-capacity"><span class="${activeAm.length<amCount?'insufficient':''}">上午剩 ${activeAm.length}／需 ${amCount}</span><span class="${activePm.length<pmCount?'insufficient':''}">下午剩 ${activePm.length}／需 ${Math.max(0,pmCount)}</span></div><div class="manual-capacity"><span>末筆 ${amCount>0&&activeAm[amCount-1]?formatClock(activeAm[amCount-1].time):'—'}</span><span>末筆 ${pmCount>0&&activePm[pmCount-1]?formatClock(activePm[pmCount-1].time):'—'}</span></div><div class="foot-actions">${button('套用至結果','manual-apply','primary','check',enough&&job.rows.length?'':'disabled')}${button('查看結果','manual-results','light','chart')}</div><p class="inline-hint">${applied?'這組候選已套用。':'候選尚未套用，原結果保留。'} 刪時間，不刪元件。</p></div>`;
  const list=state.period==='am'?am:pm;
  const count=Math.max(am.length,pm.length),limited=Math.min(count,state.shown);
  const amOrd=new Map(activeAm.map((c,i)=>[c.index,i])),pmOrd=new Map(activePm.map((c,i)=>[c.index,amCount+i]));
  const cell=(row,period)=>{
    if(!row)return '<td class="manual-empty">—</td>';
    const selected=state.period===period&&state.selection.has(row.index),active=state.period===period;
    const ordinal=(period==='am'?amOrd:pmOrd).get(row.index),targetCount=period==='am'?amCount:pmCount;
    const used=ordinal!=null&&(period==='am'?ordinal<amCount:ordinal<job.rows.length)&&targetCount>0;
    const target=used?job.rows[ordinal]:null;
    return `<td class="${active?'manual-active':''} ${row.excluded?'manual-excluded':''} ${selected?'manual-selected':''}"><button class="manual-time-button ${target?.background&&target.background!=='none'?'bg-'+target.background:''}" data-act="manual-select" data-period="${period}" data-index="${row.index}" aria-pressed="${selected}" aria-label="${period==='am'?'上午':'下午'}候選 ${row.index+1}，${formatClock(row.time)}${row.excluded?'，已刪除':''}"><span class="manual-check">${selected?'✓':row.excluded?'×':''}</span><span><strong>${formatClock(row.time)}</strong><small>${row.excluded?'已刪除':row.interval===0?'起點':'＋'+formatDuration(row.interval)}</small>${target?`<small class="manual-target">第 ${ordinal+1} 筆 ${esc(target.equipment||target.e)}</small>`:'<small class="manual-target">備用</small>'}</span></button></td>`;
  };
  html+=`<div class="manual-toolbar"><div class="segmented" aria-label="手動時間半日">${['am','pm'].map(p=>`<button class="segment ${state.period===p?'active':''}" data-act="manual-period" data-period="${p}" aria-pressed="${state.period===p}">${p==='am'?'上午':'下午'}</button>`).join('')}</div><button class="button light small ${state.rangeMode?'manual-range-active':''}" data-act="manual-range-mode" aria-pressed="${state.rangeMode}">連選</button>${button('復原','manual-undo','light small','undo',state.canUndo?'':'disabled')}</div><p class="manual-help">${state.rangeMode?(state.anchor===null?'點第一筆，再點最後一筆。':`已定第 ${state.anchor+1} 筆，再點最後一筆。`):'點時間多選；刪除後顯示累加間隔。'}</p><details class="manual-range-form"><summary>按筆號選一段</summary><form id="manual-range-form"><input name="first" aria-label="起始候選筆號" type="number" inputmode="numeric" min="1" max="${list.length}" placeholder="起筆" required><span>～</span><input name="last" aria-label="結束候選筆號" type="number" inputmode="numeric" min="1" max="${list.length}" placeholder="末筆" required><button class="button light small" type="submit">選取</button></form></details><div class="table-scroll manual-scroll" id="manual-list"><table class="manual-table"><thead><tr><th>#</th><th>上午</th><th>原間隔</th><th>下午</th></tr></thead><tbody>${Array.from({length:limited},(_,i)=>`<tr><td>${i+1}</td>${cell(am[i],'am')}<td class="manual-step">${i?plan.steps[i]+'秒':'—'}</td>${cell(pm[i],'pm')}</tr>`).join('')}</tbody></table></div>${limited<count?button(`再顯示 ${Math.min(200,count-limited)} 筆`,'manual-more','light more-rows'):''}${state.selection.size?`<div class="manual-dock"><span>已選 ${state.selection.size}</span>${button('刪除','manual-delete','danger small','',state.selection.size?'':'disabled')}${button('還原','manual-restore','light small','',state.selection.size?'':'disabled')}${button('清選','manual-clear','light small','',state.selection.size?'':'disabled')}</div>`:''}</div>`;
  return html;
}
