import {DEFAULT_MANUAL_SETTINGS,activeCandidates} from './manual-time.mjs';
import {manualHalfRows,previewManualDeletion} from './manual-preview.mjs';
import {formatClock,formatDuration,isSpecial} from './domain.mjs';

export function manualSettingsFor(job){
  return job.manualSettings||{...DEFAULT_MANUAL_SETTINGS,...Object.fromEntries(['amStart','amEnd','pmStart','pmEnd'].map(key=>[key,job.settings[key]])),amCount:Math.min(job.rows.length,job.result?.summary?.amCount??Math.ceil(job.rows.length*.6))};
}

export function manualTimeView(job,state,{esc,button}){
  const settings=manualSettingsFor(job),plan=job.manualPlan;
  const field=(key,label,numeric=false)=>`<div class="field"><label for="manual-${key}">${label}</label><input id="manual-${key}" name="${key}" data-manual-setting="${key}" inputmode="numeric" type="text" value="${esc(settings[key])}" autocomplete="off" required></div>`;
  const config=`<form id="manual-settings-form"><div class="fields">${field('base','基礎（秒）',true)}${field('rand','Rand（加 0～幾秒）',true)}</div><div class="manual-config-times"><h3>上午候選時段</h3><div class="fields">${field('amStart','第一個時刻')}${field('amEnd','最後界線')}</div><h3>下午候選時段</h3><div class="fields">${field('pmStart','第一個時刻')}${field('pmEnd','最後界線')}</div></div><div class="foot-actions">${button('取用時間設定','manual-use-settings','light small','clock','type="button"')}<button class="button primary" type="submit">${plan?'重建候選':'產生候選'}</button></div><p class="inline-hint">只有產生／重建會重抽。上午、下午各自抽樣；刪除不重抽。</p></form>`;
  let html=`<div class="manual-page">${button('返回時間設定','to-settings','light small','undo')}<details class="card manual-config" ${plan?'':'open'}><summary>基礎 ${settings.base} ＋ Rand ${settings.rand}</summary>${config}</details>`;
  if(!plan)return html+'<div class="notice">設定基礎、Rand 與時段，產生候選後即可多選刪除。</div></div>';
  const activeAm=activeCandidates(plan,'am'),activePm=activeCandidates(plan,'pm');
  const amCount=plan.settings.amCount,pmCount=job.rows.length-amCount,enough=amCount>=0&&pmCount>=0&&activeAm.length>=amCount&&activePm.length>=pmCount;
  const configChanged=JSON.stringify(settings)!==JSON.stringify(plan.settings);
  const applied=job.manualResult?.planRevision===job.manualRevision;
  html+=`${configChanged?'<div class="notice">設定已變更，重建後才會更換候選。</div>':''}<div class="card manual-assignment"><label for="manual-cut">上午套用筆數</label><div class="flex"><input id="manual-cut" type="number" inputmode="numeric" min="0" max="${job.rows.length}" value="${amCount}"><span>下午 ${Math.max(0,pmCount)} 筆</span></div><div class="manual-capacity"><span class="${activeAm.length<amCount?'insufficient':''}">上午剩 ${activeAm.length}／需 ${amCount}</span><span class="${activePm.length<pmCount?'insufficient':''}">下午剩 ${activePm.length}／需 ${Math.max(0,pmCount)}</span></div><div class="manual-capacity"><span>末筆 ${amCount>0&&activeAm[amCount-1]?formatClock(activeAm[amCount-1].time):'—'}</span><span>末筆 ${pmCount>0&&activePm[pmCount-1]?formatClock(activePm[pmCount-1].time):'—'}</span></div><div class="foot-actions">${button('套用至結果','manual-apply','primary','check',enough&&job.rows.length?'':'disabled')}${button('查看結果','manual-results','light','chart')}</div><p class="inline-hint">${applied?'這組候選已套用。':'候選尚未套用，原結果保留。'} 刪時間，不刪元件。</p></div>`;
  const list=manualHalfRows(job,plan,state.period),limited=Math.min(list.length,state.shown);
  const rangeLabel=guide=>guide&&!guide.error?formatDuration(guide.min)+'～'+formatDuration(guide.max):guide?.error||'—';
  const verdict=row=>!row.target?'備用':row.guide?.error?'待確認':row.deficit?'還差 '+formatDuration(row.deficit):row.excess?'超過 '+formatDuration(row.excess):'範圍內';
  const rowHtml=row=>{
    const selected=state.selection.has(row.index),target=row.target;
    const bg=target?(row.first&&target.background!=='red'?'yellow':target.background):'none';
    const previousFloor=row.first?1:job.rows[row.sourceIndex-1]?.floor;
    const floorText=target?.floor==null?'—':previousFloor!=null&&previousFloor!==target.floor?`${previousFloor}→${target.floor}F`:`${target.floor}F`;
    const classes=[row.excluded?'manual-excluded':'',selected?'manual-selected':'','bg-'+bg,target?.floorMark?'floor-mark':'',target?.extraMark?'extra-mark':''].join(' ');
    return `<tr class="${classes}" data-act="manual-select" data-period="${state.period}" data-index="${row.index}"><td>${row.index+1}</td><td><button class="manual-time-button" data-act="manual-select" data-period="${state.period}" data-index="${row.index}" aria-pressed="${selected}" aria-label="${state.period==='am'?'上午':'下午'}候選 ${row.index+1}，${formatClock(row.time)}${row.excluded?'，已刪除':''}"><span class="manual-check">${selected?'✓':row.excluded?'×':''}</span><span><strong>${formatClock(row.time)}</strong><small>${row.excluded?'已刪除':'間隔 '+formatDuration(row.interval)}</small><small>${target?'元件 '+(row.sourceIndex+1):row.excluded?'':'備用'}</small></span></button></td><td class="manual-floor ${target?.floorMark?'floor-change':''}">${esc(floorText)}</td><td>${target?`<span class="${isSpecial(target)?'special-form':''}">${esc(target.form||'—')}${isSpecial(target)?'<small>+1:00</small>':''}</span>`:'—'}</td><td class="manual-equipment">${esc(target?.equipment||'—')}</td><td class="manual-rule" title="${esc(row.guide?.parts?.join('；')||'')}">${esc(rangeLabel(row.guide))}</td><td class="manual-verdict ${row.deficit||row.excess?'outside':''}">${row.excluded?'—':verdict(row)}</td><td>${row.step?row.step+'秒':'—'}</td><td class="manual-source ${target?.floorMark?'floor-change':target?.extraMark?'extra-change':''}">${esc(target?.e||'—')}</td></tr>`;
  };
  const preview=state.selection.size?previewManualDeletion(job,plan,state.period,[...state.selection]):null;
  const changeHtml=row=>`<div class="manual-preview-line"><strong>${row.target?'元件 '+(row.sourceIndex+1)+' · '+esc(row.target.equipment||''):'候選 '+(row.index+1)+' · 備用'}</strong><span>${row.target?esc(row.target.floor)+'F · '+esc(row.target.form||'—')+' · ':''}${formatDuration(row.beforeInterval)} → <b>${formatDuration(row.interval)}</b>（${row.added<0?'減少':'增加'} ${formatDuration(Math.abs(row.added))}）</span>${row.target?`<small>需 ${esc(rangeLabel(row.guide))} · ${verdict(row)}</small>`:''}</div>`;
  html+=`<div class="manual-toolbar"><div class="segmented" aria-label="手動時間半日">${['am','pm'].map(p=>`<button class="segment ${state.period===p?'active':''}" data-act="manual-period" data-period="${p}" aria-pressed="${state.period===p}">${p==='am'?'上午':'下午'}</button>`).join('')}</div><button class="button light small ${state.rangeMode?'manual-range-active':''}" data-act="manual-range-mode" aria-pressed="${state.rangeMode}">連選</button>${button('復原','manual-undo','light small','undo',state.canUndo?'':'disabled')}</div><p class="manual-help">${state.rangeMode?(state.anchor===null?'點第一筆，再點最後一筆。':`已定第 ${state.anchor+1} 筆，再點最後一筆。`):'點選後預覽累加；左右滑看完整設備與所需時間。'}</p>${plan.schema===1?'<p class="manual-legacy">這份沿用舊共用亂數；重建候選才改為上午、下午各自抽樣。</p>':''}<details class="manual-range-form"><summary>按筆號選一段</summary><form id="manual-range-form"><input name="first" aria-label="起始候選筆號" type="number" inputmode="numeric" min="1" max="${list.length}" placeholder="起筆" required><span>～</span><input name="last" aria-label="結束候選筆號" type="number" inputmode="numeric" min="1" max="${list.length}" placeholder="末筆" required><button class="button light small" type="submit">選取</button></form></details><div class="table-scroll manual-scroll" id="manual-list" tabindex="0" aria-label="${state.period==='am'?'上午':'下午'}手動候選，左右與上下滑動"><table class="manual-table"><thead><tr><th>#</th><th>時間／間隔</th><th>樓層</th><th>型式</th><th>設備</th><th>需間隔</th><th>差額</th><th>原秒</th><th>完整設備碼</th></tr></thead><tbody>${list.slice(0,limited).map(rowHtml).join('')}${limited<list.length?'<tr data-manual-more-sentinel><td colspan="9">滑動載入更多…</td></tr>':''}</tbody></table></div>${preview?`<div class="manual-dock"><div class="manual-deletion-preview"><span>刪除預覽 · ${preview.count} 筆</span>${preview.affected.slice(0,2).map(changeHtml).join('')}${preview.affected.length>2?`<details><summary>另 ${preview.affected.length-2} 處累加</summary>${preview.affected.slice(2).map(changeHtml).join('')}</details>`:''}${!preview.affected.length?'<small>所選為已刪候選或尾端備用，沒有後續間隔可累加。</small>':''}${preview.insufficient?`<strong class="manual-shortage">刪後剩 ${preview.available}／需 ${preview.needed}，將無法完整套用。</strong>`:''}</div><div class="manual-dock-actions"><span>已選 ${state.selection.size}</span>${button('刪除','manual-delete','danger small','',preview.count?'':'disabled')}${button('還原','manual-restore','light small')}${button('清選','manual-clear','light small')}</div></div>`:''}</div>`;
  return html;
}
