const KEY='log-device-settings';
export function deviceSettings(storage){try{const v=JSON.parse(storage.getItem(KEY));return {historyLimit:[20,50,100,200].includes(v?.historyLimit)?v.historyLimit:20};}catch{return {historyLimit:20};}}
export function saveDeviceSettings(storage,value){if(![20,50,100,200].includes(value.historyLimit))throw new Error('紀錄筆數無效');storage.setItem(KEY,JSON.stringify(value));return value;}
export function appendRecord(job,kind,detail=''){
  job.activity=(Array.isArray(job.activity)?job.activity:[]).slice(-99);
  job.activity.push({at:new Date().toISOString(),kind:String(kind).slice(0,100),detail:String(detail).slice(0,1000)});
}
export function settingsPage(job,state,{esc,button}){
  const bytes=n=>Number.isFinite(n)?(n/1024/1024).toFixed(2)+' MB':'尚未取得';
  const report=job.importReport,history=state.history;
  return `<div class="stack"><div class="card card-pad"><h2>記憶體與本機儲存</h2><p>本次可復原 ${history.length} 步 · 約 ${bytes(state.historyBytes)}。重開網站會清除本次復原步驟；卡夾仍會保存。</p><div class="field"><label for="history-limit">保留最近幾步</label><select id="history-limit">${[20,50,100,200].map(n=>`<option value="${n}" ${state.historyLimit===n?'selected':''}>${n} 步</option>`).join('')}</select></div><p class="inline-hint">較多步驟會使用較多記憶體；超過上限時移除最舊步驟。</p><p>網站儲存估計 ${bytes(state.usage)}${state.quota?' ／ '+bytes(state.quota):''}。這是儲存空間，瀏覽器未提供完整 RAM 使用量。</p><div class="foot-actions">${button('重新檢查空間','settings-estimate','light small')}${button('釋放復原記憶體','settings-clear-memory','light small','trash')}${button('清除舊版快取','settings-clear-cache','light small','trash')}${button('管理卡夾','shelf','light small','folder')}</div><p class="inline-hint">釋放復原記憶體不刪卡夾、目前時間及指定時間。清除舊版快取保留目前版本。</p></div><div class="card card-pad"><h2>紀錄</h2><div class="foot-actions">${button('手動時間復原紀錄','manual-history','light small','undo',history.length?'':'disabled')}${button('清除本卡夾紀錄','settings-clear-records','light small','trash')}</div>${report?`<details open><summary>最近匯入 · ${report.count} 筆</summary><p>來源第 ${report.first??'—'}～${report.last??'—'} 列。空白後仍有資料會繼續匯入，不補造資料。</p>${report.gaps.length?`<p class="notice">斷層 ${report.gaps.length} 處：</p><ul>${report.gaps.map(g=>`<li>Excel 第 ${g.from}${g.to===g.from?'':'～'+g.to} 列空白；後段已接續匯入。</li>`).join('')}</ul>`:'<p>沒有中間空白斷層。</p>'}${report.partial.length?`<p class="notice">來源只有一欄有值：第 ${report.partial.join('、')} 列，請在資料頁確認。</p>`:''}</details>`:'<p class="inline-hint">目前卡夾尚無匯入掃描紀錄。</p>'}<div class="device-records">${[...(job.activity||[])].reverse().map(item=>`<article><b>${esc(item.kind)}</b><small>${esc(new Date(item.at).toLocaleString('zh-TW',{hour12:false}))}</small><p>${esc(item.detail)}</p></article>`).join('')||'<p>尚無操作紀錄。</p>'}</div><p class="inline-hint">只記錄本卡夾的操作摘要，最多100筆；不記錄取件鑰匙或TXT內容。</p></div></div>`;
}
